-- +goose Up

-- EL BANCO DE PLATOS: que ES cada plato, para poder fotografiarlo.
--
-- Hasta ahora la guarnicion de una foto la ponia el TIPO DE NEGOCIO, asi que en
-- una cevicheria los 74 platos salian con camote, choclo y cancha al lado — el
-- sudado, el postre y la gaseosa de litro incluidos. El camote es del CEVICHE,
-- no de la cevicheria. Esta tabla es donde vive esa diferencia.
--
-- La semilla se cosecho UNA VEZ de https://api-comida-peru.luisgagocasas.com/api
-- (25 regiones, ?limit=100), datos CC BY 4.0 — la atribucion va en el aviso
-- legal. No es una dependencia: si esa API desaparece manana, esto sigue igual.
-- 509 platos, 419 nombres unicos.
--
-- Lo que la cosecha NO da, y es lo que de verdad decide la foto: como se VE el
-- plato servido. Wikipedia dice del ceviche "raw fish marinated in lime juice";
-- eso es la receta, no la foto. Los cuatro campos en ingles (aspecto,
-- recipiente, guarnicion, jamas) se escriben y se validan uno a uno con
-- cmd/fotocheck, y por eso nacen vacios aqui.
CREATE TABLE plato_tipico (
    clave      text PRIMARY KEY,
    nombre     text NOT NULL,

    -- Que cocina es. Vacio en lo cosechado; se llena en el canon comercial, que
    -- es lo que aparece en las cartas de verdad.
    cocina     text NOT NULL DEFAULT '',

    -- entrada|fondo|sopa|postre|bebida|guarnicion|otro.
    --
    -- Es el campo que llego gratis con la cosecha y arregla lo mas visible sin
    -- escribir una sola descripcion: una bebida no lleva guarnicion de plato de
    -- fondo, y una sopa va en bol, no en plato llano.
    curso      text NOT NULL DEFAULT 'fondo',

    -- Los cuatro que deciden la foto. En INGLES a proposito, como porcion.go y
    -- formato.go: es el idioma del generador y cambiarlo habria que medirlo.
    aspecto    text NOT NULL DEFAULT '',
    recipiente text NOT NULL DEFAULT '',
    guarnicion text NOT NULL DEFAULT '',

    -- Lo que el plato NO es. No es opcional en la practica: es la clausula que
    -- ya salva al pollo a la brasa de salir rostizado de supermercado.
    jamas      text NOT NULL DEFAULT '',

    -- Lo que dispara el emparejamiento con un nombre impreso. Lo cosechado trae
    -- solo su propio slug; el canon comercial trae los cortos ("ceviche"), que
    -- son los que de verdad aciertan.
    patrones   jsonb NOT NULL DEFAULT '[]',

    -- Materia prima de la cosecha para escribir los cuatro de arriba, y para
    -- que la IA los redacte en la siguiente fase.
    ingredientes jsonb NOT NULL DEFAULT '[]',

    -- Puntero a Wikimedia Commons. NO se descarga ni se sirve: es la pista para
    -- el dia que el canon lleve foto de referencia, que es el techo de calidad.
    imagen_url text NOT NULL DEFAULT '',
    region     text NOT NULL DEFAULT '',

    -- De donde salio y si alguien la miro. Sin esto el banco se degrada en
    -- silencio segun crece, y el banco es el activo.
    origen     text    NOT NULL DEFAULT 'cosecha',  -- cosecha|canon|ia|mano
    revisado   boolean NOT NULL DEFAULT false,

    creado_at      timestamptz NOT NULL DEFAULT now(),
    actualizado_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO plato_tipico (clave, nombre, curso, ingredientes, imagen_url, region) VALUES
    ('aceitunas-tacnenas', 'Aceitunas Tacneñas', 'guarnicion', '["Aceituna negra", "Salmuera"]', 'https://i.ytimg.com/vi/Example_Aceitunas.jpg', 'Tacna'),
    ('adobo-arequipeno', 'Adobo Arequipeño', 'fondo', '["Lomo de cerdo", "Concho de chicha de jora", "Ají panca", "Cebolla roja", "Rocoto entero"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Adobo_arequipe%C3%B1o.jpg/800px-Adobo_arequipe%C3%B1o.jpg', 'Arequipa'),
    ('adobo-ayacuchano', 'Adobo Ayacuchano', 'fondo', '["Carne de cerdo", "Chicha de jora", "Ají panca", "Cebolla", "Comino"]', 'https://i.ytimg.com/vi/Example_AdoboAyacucho.jpg', 'Ayacucho'),
    ('adobo-cusqueno', 'Adobo Cusqueño', 'fondo', '["Carne de cerdo", "Chicha de jora", "Ají panca", "Rocoto", "Cebolla"]', 'https://i.ytimg.com/vi/Example_AdoboCusco.jpg', 'Cusco'),
    ('adobo-de-cerdo-iqueno', 'Adobo de Cerdo Iqueño', 'fondo', '["Cerdo", "Vinagre", "Ají panca", "Garbanzos (opcional)"]', 'https://i.ytimg.com/vi/Example_AdoboIca.jpg', 'Ica'),
    ('adobo-tacneno', 'Adobo Tacneño', 'fondo', '["Chancho (cerdo)", "Vinagre", "Ají panca", "Palillo", "Zapallo de carga"]', 'https://i.ytimg.com/vi/Example_AdoboTacna.jpg', 'Tacna'),
    ('aguadito-de-mariscos', 'Aguadito de Mariscos', 'sopa', '["Arroz", "Culantro", "Mix de mariscos", "Chicha de jora"]', 'https://i.ytimg.com/vi/Example_Aguadito.jpg', 'Moquegua'),
    ('aguajina', 'Aguajina', 'bebida', '["Aguaje (fruto)", "Agua", "Azúcar"]', 'https://i.ytimg.com/vi/Example_Aguajina.jpg', 'Ucayali'),
    ('ahumeado-de-pescado', 'Ahumeado de Pescado', 'fondo', '["Pescado (Gamitana o Paco)", "Sal", "Hojas de plátano"]', 'https://i.ytimg.com/vi/Example_Ahumado.jpg', 'Ucayali'),
    ('aji-de-gallina', 'Ají de Gallina', 'fondo', '["Pechuga de gallina deshilachada", "Ají amarillo molido", "Pan de molde (o galletas)", "Leche evaporada", "Pecanas", "Queso parmesano"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Aj%C3%AD_de_gallina_-_Lima%2C_Peru.jpg/800px-Aj%C3%AD_de_gallina_-_Lima%2C_Peru.jpg', 'Lima'),
    ('aji-de-lacayote', 'Ají de Lacayote', 'fondo', '["Lacayote (calabaza)", "Papas", "Ají amarillo", "Queso", "Huacatay"]', 'https://i.ytimg.com/vi/Example_Lacayote.jpg', 'Arequipa'),
    ('albondigas-de-pulpa-de-cangrejo', 'Albóndigas de Pulpa de Cangrejo', 'fondo', '["Pulpa de cangrejo", "Pan rallado", "Huevo", "Salsa de tomate"]', 'https://i.ytimg.com/vi/Example_AlbondigasCangrejo.jpg', 'Tumbes'),
    ('alfajor-de-penco', 'Alfajor de Penco', 'postre', '["Harina", "Yemas", "Anís", "Manjar blanco", "Coco rallado"]', 'https://i.ytimg.com/vi/Example_AlfajorPenco.jpg', 'Moquegua'),
    ('alfajores-de-trujillo', 'Alfajores de Trujillo', 'postre', '["Harina", "Manteca", "Manjar blanco", "Azúcar impalpable"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Alfajor_peruano.jpg/800px-Alfajor_peruano.jpg', 'La Libertad'),
    ('alwish-luli-guiso-de-arvejas', 'Alwish Luli (Guiso de Arvejas)', 'fondo', '["Arvejas secas", "Carne de cerdo", "Papas", "Hierbabuena"]', 'https://i.ytimg.com/vi/Example_AlwishLuli.jpg', 'Junín'),
    ('antecoco', 'Antecoco', 'postre', '["Coco rallado", "Leche", "Azúcar", "Maicena"]', 'https://i.ytimg.com/vi/Example_Antecoco.jpg', 'Tumbes'),
    ('anticuchos-de-corazon', 'Anticuchos de Corazón', 'entrada', '["Corazón de res", "Ají panca", "Vinagre", "Ajos", "Comino", "Orégano"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Anticuchos_peruanos.jpg/800px-Anticuchos_peruanos.jpg', 'Lima'),
    ('api-de-calabaza', 'Api de Calabaza', 'postre', '["Calabaza madura", "Chancaca", "Leche", "Canela", "Harina de maíz"]', 'https://i.ytimg.com/vi/Example_ApiCalabaza.jpg', 'Áncash'),
    ('arroz-a-la-chiclayana', 'Arroz a la Chiclayana', 'fondo', '["Arroz", "Pollo", "Arvejas", "Pimiento", "Zapallo loche"]', 'https://i.ytimg.com/vi/Example_ArrozChiclayana.jpg', 'Lambayeque'),
    ('arroz-chaufa', 'Arroz Chaufa', 'fondo', '["Arroz cocido (del día anterior)", "Pollo/Cerdo", "Huevos", "Cebolla china", "Sillao", "Kion"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Arroz_chaufa.jpg/800px-Arroz_chaufa.jpg', 'Lima'),
    ('arroz-con-conchas-negras', 'Arroz con Conchas Negras', 'fondo', '["Arroz", "Conchas negras", "Ají panca", "Pimiento", "Arvejas"]', 'https://i.ytimg.com/vi/Example_ArrozConchas.jpg', 'Tumbes'),
    ('arroz-con-mariscos', 'Arroz con Mariscos', 'fondo', '["Arroz", "Mix de mariscos", "Ají panca", "Ají amarillo", "Arvejas"]', 'https://upload.wikimedia.org/wikipedia/commons/2/25/Arroz_con_Mariscos.jpg', 'Callao'),
    ('arroz-con-pato-a-la-chepenana', 'Arroz con Pato a la Chepenana', 'fondo', '["Pato", "Arroz", "Culantro", "Cerveza negra", "Chicha de jora"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Arroz_con_pato_peruano.jpg/800px-Arroz_con_pato_peruano.jpg', 'La Libertad'),
    ('arroz-con-pato-a-la-chiclayana', 'Arroz con Pato a la Chiclayana', 'fondo', '["Pato tierno", "Arroz", "Zapallo loche", "Culantro", "Cerveza negra", "Chicha de jora"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Arroz_con_pato_peruano.jpg/800px-Arroz_con_pato_peruano.jpg', 'Lambayeque'),
    ('arroz-con-pato-a-la-tacnena', 'Arroz con Pato a la Tacneña', 'fondo', '["Pato", "Arroz", "Ají panca", "Cerveza negra"]', 'https://i.ytimg.com/vi/Example_ArrozPatoTacna.jpg', 'Tacna'),
    ('arroz-de-trigo', 'Arroz de Trigo', 'guarnicion', '["Trigo pelado", "Aceite", "Ajos", "Sal"]', 'https://i.ytimg.com/vi/Example_ArrozTrigo.jpg', 'Cajamarca'),
    ('arroz-zambito', 'Arroz Zambito', 'postre', '["Arroz", "Chancaca (panela)", "Leche", "Coco rallado", "Pasas", "Pecanas"]', 'https://i.ytimg.com/vi/Example_ArrozZambito.jpg', 'Lima'),
    ('arvejas-con-carne', 'Arvejas con Carne', 'fondo', '["Arvejas secas partidas", "Carne de res", "Papas", "Ají panca"]', 'https://i.ytimg.com/vi/Example_ArvejasCarne.jpg', 'Pasco'),
    ('asado-de-picuro', 'Asado de Picuro', 'fondo', '["Picuro (Majaz)", "Sacha culantro", "Ajos", "Sillao", "Vinagre"]', 'https://i.ytimg.com/vi/Example_PicuroAsado.jpg', 'Madre de Dios'),
    ('atamalado', 'Atamalado', 'fondo', '["Frijol negro (o zarandaja)", "Arroz", "Pescado frito", "Chancaca (opcional)"]', 'https://i.ytimg.com/vi/Example_Atamalado.jpg', 'Piura'),
    ('avispa-juane', 'Avispa Juane', 'fondo', '["Arroz", "Carne de cerdo molida", "Gallina", "Huevos", "Hojas de bijao"]', 'https://i.ytimg.com/vi/Example_AvispaJuane.jpg', 'San Martín'),
    ('bienmesabe', 'Bienmesabe', 'postre', '["Zapallo loche", "Chancaca", "Leche", "Canela"]', 'https://i.ytimg.com/vi/Example_Bienmesabe.jpg', 'Tumbes'),
    ('bisteck-de-alpaca', 'Bisteck de Alpaca', 'fondo', '["Lomo de alpaca", "Arroz", "Papas fritas", "Ensalada"]', 'https://i.ytimg.com/vi/Example_BisteckAlpaca.jpg', 'Huancavelica'),
    ('bisteck-de-higado', 'Bisteck de Hígado', 'fondo', '["Hígado de res", "Vinagre", "Cebolla", "Yuca"]', 'https://i.ytimg.com/vi/Example_Higado.jpg', 'Amazonas'),
    ('bisteck-de-venado', 'Bisteck de Venado', 'fondo', '["Carne de venado", "Vinagre", "Ajos", "Cebolla"]', 'https://i.ytimg.com/vi/Example_Venado.jpg', 'Madre de Dios'),
    ('brochetas-de-suri', 'Brochetas de Suri', 'entrada', '["Suri (gusano de palma)", "Sal", "Ajos"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Suri_food.jpg/800px-Suri_food.jpg', 'Loreto'),
    ('bunuelos-de-yuca', 'Buñuelos de Yuca', 'postre', '["Yuca sancochada", "Harina", "Huevo", "Levadura", "Miel de chancaca"]', 'https://i.ytimg.com/vi/Example_Bunuelos.jpg', 'Arequipa'),
    ('butifarra', 'Butifarra', 'otro', '["Jamón del País (cerdo)", "Pan francés crocante", "Salsa criolla (cebolla)", "Lechuga", "Mostaza"]', 'https://i.ytimg.com/vi/Example_Butifarra.jpg', 'Lima'),
    ('cacharrada', 'Cacharrada', 'fondo', '["7 carnes (anchura, chinchulines, criadilla, venas, molleja, hígado, corazón)", "Papas", "Ají panca"]', 'https://i.ytimg.com/vi/Example_Cacharrada.jpg', 'Moquegua'),
    ('cachema-encebollada', 'Cachema Encebollada', 'fondo', '["Pescado Cachema (seco o fresco)", "Cebolla", "Tomate", "Vinagre", "Ají"]', 'https://i.ytimg.com/vi/Example_CachemaEncebollada.jpg', 'Piura'),
    ('cachina', 'Cachina', 'bebida', '["Jugo de uva fermentado (mosto)"]', 'https://i.ytimg.com/vi/Example_Cachina.jpg', 'Ica'),
    ('cafe-de-villa-rica', 'Café de Villa Rica', 'bebida', '["Granos de café selecto", "Agua"]', 'https://i.ytimg.com/vi/Example_CafeVillaRica.jpg', 'Pasco'),
    ('caldo-de-bolas', 'Caldo de Bolas', 'sopa', '["Plátano verde", "Carne de res molida", "Huevo duro", "Pasas", "Hueso de res"]', 'https://i.ytimg.com/vi/Example_CaldoBolas.jpg', 'Tumbes'),
    ('caldo-de-cabeza', 'Caldo de Cabeza', 'sopa', '["Cabeza de carnero", "Papas blancas", "Mote", "Hierbabuena", "Paico"]', 'https://i.ytimg.com/vi/Example_CaldoCabezaPasco.jpg', 'Pasco'),
    ('caldo-de-cabeza-de-carnero', 'Caldo de Cabeza de Carnero', 'sopa', '["Cabeza de carnero", "Hierbabuena", "Papa", "Mote"]', 'https://i.ytimg.com/vi/Example_CaldoCabeza.jpg', 'Cajamarca'),
    ('caldo-de-cabeza-huarjata', 'Caldo de Cabeza (Huarjata)', 'sopa', '["Cabeza de cordero/cerdo", "Chuño negro", "Papas", "Arroz"]', 'https://i.ytimg.com/vi/Example_Huarjata.jpg', 'Puno'),
    ('caldo-de-carachama', 'Caldo de Carachama', 'sopa', '["Carachama (pez)", "Sacha culantro", "Ajos", "Yuca"]', 'https://i.ytimg.com/vi/Example_Carachama.jpg', 'Madre de Dios'),
    ('caldo-de-gallina-de-chacra', 'Caldo de Gallina de Chacra', 'sopa', '["Gallina negra", "Kion", "Papas amarillas", "Huevos", "Fideos"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Caldo_de_gallina_peruano.jpg/800px-Caldo_de_gallina_peruano.jpg', 'Huánuco'),
    ('caldo-de-siete-carnes', 'Caldo de Siete Carnes', 'sopa', '["Res", "Cerdo", "Carnero", "Gallina", "Charqui", "Cabrito", "Pato"]', 'https://i.ytimg.com/vi/Example_SieteCarnes.jpg', 'Piura'),
    ('caldo-verde', 'Caldo Verde', 'sopa', '["Papas", "Queso", "Hierbas (Ruda, Paico, Muña)", "Huevo"]', 'https://i.ytimg.com/vi/Example_CaldoVerdePasco.jpg', 'Pasco'),
    ('cangrejo-reventado', 'Cangrejo Reventado', 'fondo', '["Cangrejos", "Huevos", "Algas (yuyo)", "Ají panca", "Ajos"]', 'https://i.ytimg.com/vi/Example_CangrejoReventado.jpg', 'La Libertad'),
    ('carapulcra-chinchana', 'Carapulcra Chinchana', 'fondo', '["Papa seca (papa cristalizada)", "Carne de cerdo", "Ají panca", "Maní", "Clavo de olor"]', 'https://i.ytimg.com/vi/Example_CarapulcraChincha.jpg', 'Ica'),
    ('carbonara-albondigas-de-yuca', 'Carbonara (Albóndigas de Yuca)', 'fondo', '["Yuca", "Queso", "Huevos", "Aceite"]', 'https://i.ytimg.com/vi/Example_CarbonaraPozuzo.jpg', 'Pasco'),
    ('carne-alinada', 'Carne Aliñada', 'fondo', '["Carne de cerdo", "Vinagre", "Achiote", "Comino", "Chifles"]', 'https://i.ytimg.com/vi/Example_CarneAlinada.jpg', 'Piura'),
    ('carne-arrollada', 'Carne Arrollada', 'fondo', '["Carne de res (sábana)", "Carne molida", "Huevo duro", "Pasas", "Aceitunas"]', 'https://i.ytimg.com/vi/Example_CarneArrollada.jpg', 'Amazonas'),
    ('carnero-al-palo', 'Carnero al Palo', 'fondo', '["Carnero entero", "Sal", "Ajos", "Cerveza o chicha", "Limón"]', 'https://i.ytimg.com/vi/Example_CarneroPalo.jpg', 'Huancavelica'),
    ('cau-cau', 'Cau Cau', 'fondo', '["Mondongo (panza) precocido", "Papas en cubos", "Palillo (cúrcuma)", "Hierbabuena", "Ají amarillo"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Cau_cau.jpg/800px-Cau_cau.jpg', 'Lima'),
    ('cau-cau-de-mariscos', 'Cau Cau de Mariscos', 'fondo', '["Mix de mariscos", "Papas en cubos", "Palillo (cúrcuma)", "Hierbabuena"]', 'https://i.ytimg.com/vi/Example_CauCauMariscos.jpg', 'Callao'),
    ('cauche-de-queso', 'Cauche de Queso', 'fondo', '["Queso fresco serrano", "Cebolla", "Tomate", "Ají amarillo", "Huacatay", "Leche"]', 'https://i.ytimg.com/vi/Example_Cauche.jpg', 'Arequipa'),
    ('causa-en-lapa-causa-moche', 'Causa en Lapa (Causa Moche)', 'entrada', '["Papa amarilla", "Ají amarillo", "Limón", "Pescado frito/guisado", "Yuca"]', 'https://i.ytimg.com/vi/Example_CausaMoche.jpg', 'La Libertad'),
    ('causa-ferrenafana', 'Causa Ferreñafana', 'entrada', '["Papa batida", "Pescado salado (frito o sancochado)", "Cebolla", "Ají amarillo", "Camote", "Plátano sancochado"]', 'https://i.ytimg.com/vi/Example_CausaFerrenafe.jpg', 'Lambayeque'),
    ('causa-limena', 'Causa Limeña', 'entrada', '["Papa amarilla prensada", "Ají amarillo", "Limón", "Aceite", "Pollo deshilachado", "Mayonesa", "Palta"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Causa_lime%C3%B1a.jpg/800px-Causa_lime%C3%B1a.jpg', 'Lima'),
    ('cazuela-de-gallina', 'Cazuela de Gallina', 'sopa', '["Gallina", "Zapallo", "Arroz", "Papa", "Apio", "Choclo"]', 'https://i.ytimg.com/vi/Example_CazuelaTacna.jpg', 'Tacna'),
    ('cecina-shilpida', 'Cecina Shilpida', 'fondo', '["Cecina de cerdo (seca)", "Huevos", "Cebolla", "Tomate", "Ají"]', 'https://i.ytimg.com/vi/Example_CecinaShilpida.jpg', 'Cajamarca'),
    ('ceviche-clasico', 'Ceviche Clásico', 'fondo', '["Pescado fresco (Lenguado/Corvina)", "Limón sutil", "Ají limo", "Cebolla roja", "Culantro", "Camote", "Choclo"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Ceviche_de_pescado.jpg/800px-Ceviche_de_pescado.jpg', 'Lima'),
    ('ceviche-de-chochos', 'Ceviche de Chochos', 'entrada', '["Chochos (tarwi) desamargados", "Limón", "Cebolla", "Tomate", "Cancha", "Culantro"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Ceviche_de_chochos.jpg/800px-Ceviche_de_chochos.jpg', 'Áncash'),
    ('ceviche-de-conchas-negras', 'Ceviche de Conchas Negras', 'entrada', '["Conchas negras vivas", "Limón de Chulucanas", "Ají limo", "Cebolla roja", "Cancha", "Chifles"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Ceviche_de_conchas_negras.jpg/800px-Ceviche_de_conchas_negras.jpg', 'Tumbes'),
    ('ceviche-de-jurel', 'Ceviche de Jurel', 'entrada', '["Jurel", "Limón", "Cebolla", "Ají", "Cochayuyo"]', 'https://i.ytimg.com/vi/Example_CevicheJurel.jpg', 'Moquegua'),
    ('ceviche-de-mero', 'Ceviche de Mero', 'entrada', '["Mero murique", "Limón de Tambogrande", "Ají limo", "Cebolla roja", "Zarandaja (frijol)"]', 'https://i.ytimg.com/vi/Example_CevicheMero.jpg', 'Piura'),
    ('ceviche-de-pato', 'Ceviche de Pato', 'fondo', '["Pato", "Limón", "Ají mirasol", "Cebolla", "Ajos"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Ceviche_de_pato.jpg/800px-Ceviche_de_pato.jpg', 'Lambayeque'),
    ('ceviche-de-pejerrey', 'Ceviche de Pejerrey', 'entrada', '["Pejerrey", "Limón", "Ají limo", "Cebolla"]', 'https://i.ytimg.com/vi/Example_CevichePejerrey.jpg', 'Ica'),
    ('ceviche-mixto', 'Ceviche Mixto', 'entrada', '["Pescado", "Pulpo", "Calamar", "Langostino", "Conchas negras"]', 'https://i.ytimg.com/vi/Example_CevicheMixto.jpg', 'Tumbes'),
    ('chairito-tacneno', 'Chairito Tacneño', 'sopa', '["Chuño molido", "Carne de res", "Zapallo", "Habas"]', 'https://i.ytimg.com/vi/Example_Chairito.jpg', 'Tacna'),
    ('chairo', 'Chairo', 'sopa', '["Chuño negro chancado", "Carne de res", "Cecina", "Tripas", "Mote", "Verduras"]', 'https://upload.wikimedia.org/wikipedia/commons/7/7c/Chairo_soup.jpg', 'Arequipa'),
    ('chairo-puneno', 'Chairo Puneño', 'sopa', '["Chuño negro chancado", "Carne de cordero", "Chalona (carne seca)", "Zanahoria", "Mote"]', 'https://upload.wikimedia.org/wikipedia/commons/7/7c/Chairo_soup.jpg', 'Puno'),
    ('champus', 'Champús', 'postre', '["Mote pelado", "Piña", "Naranja", "Chancaca", "Hojas de guanábana"]', 'https://i.ytimg.com/vi/Example_Champus.jpg', 'Lambayeque'),
    ('chapanas', 'Chapanas', 'postre', '["Yuca rallada", "Chancaca", "Anís", "Pasas", "Hojas de plátano"]', 'https://i.ytimg.com/vi/Example_Chapanas.jpg', 'Ica'),
    ('chapo', 'Chapo', 'bebida', '["Plátano maduro (bellaco)", "Agua", "Leche (opcional)"]', 'https://i.ytimg.com/vi/Example_Chapo.jpg', 'Ucayali'),
    ('chaque-de-tripas', 'Chaque de Tripas', 'sopa', '["Tripas de res", "Carne", "Papas", "Verduras", "Trigo"]', 'https://i.ytimg.com/vi/Example_Chaque.jpg', 'Arequipa'),
    ('charqui-con-papas', 'Charqui con Papas', 'fondo', '["Charqui (carne seca de res o alpaca)", "Papa", "Cebolla", "Ají"]', 'https://i.ytimg.com/vi/Example_Charqui.jpg', 'Áncash'),
    ('charquican', 'Charquicán', 'fondo', '["Charqui (carne seca)", "Papas", "Ají panca", "Cebolla"]', 'https://i.ytimg.com/vi/Example_Charquican.jpg', 'Tacna'),
    ('chicha-de-guinapo', 'Chicha de Guiñapo', 'bebida', '["Maíz negro germinado (guiñapo)", "Agua", "Azúcar"]', 'https://i.ytimg.com/vi/Example_Guinapo.jpg', 'Arequipa'),
    ('chicha-de-higo', 'Chicha de Higo', 'bebida', '["Higos maduros", "Agua", "Chancaca"]', 'https://i.ytimg.com/vi/Example_ChichaHigo.jpg', 'San Martín'),
    ('chicha-de-jora', 'Chicha de Jora', 'bebida', '["Maíz de jora", "Chancaca", "Agua"]', 'https://upload.wikimedia.org/wikipedia/commons/e/e2/Chicha_de_jora_cusque%C3%B1a.jpg', 'Lambayeque'),
    ('chicha-de-jora-ancashina', 'Chicha de Jora Ancashina', 'bebida', '["Jora (maíz germinado)", "Chancaca", "Agua", "Clavo de olor"]', 'https://upload.wikimedia.org/wikipedia/commons/e/e2/Chicha_de_jora_cusque%C3%B1a.jpg', 'Áncash'),
    ('chicha-de-quinua', 'Chicha de Quinua', 'bebida', '["Quinua", "Piña", "Manzana", "Canela", "Clavo"]', 'https://i.ytimg.com/vi/Example_ChichaQuinua.jpg', 'Puno'),
    ('chicha-morada', 'Chicha Morada', 'bebida', '["Maíz morado", "Piña", "Manzana", "Canela", "Clavo", "Limón"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Chicha_morada.jpg/800px-Chicha_morada.jpg', 'Lima'),
    ('chicharron-ayacuchano', 'Chicharrón Ayacuchano', 'fondo', '["Cerdo", "Papas", "Mote", "Ensalada de cebolla"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Chicharr%C3%B3n_peruano.jpg/800px-Chicharr%C3%B3n_peruano.jpg', 'Ayacucho'),
    ('chicharron-colorado', 'Chicharrón Colorado', 'fondo', '["Carne de cerdo", "Ají panca", "Achiote"]', 'https://i.ytimg.com/vi/Example_ChicharronColorado.jpg', 'Junín'),
    ('chicharron-con-mote', 'Chicharrón con Mote', 'fondo', '["Cerdo", "Mote pelado", "Salsa criolla"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Chicharr%C3%B3n_peruano.jpg/800px-Chicharr%C3%B3n_peruano.jpg', 'Huánuco'),
    ('chicharron-cusqueno', 'Chicharrón Cusqueño', 'fondo', '["Carne de cerdo con piel", "Hierbabuena", "Mote", "Papas", "Cebolla"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Chicharr%C3%B3n_peruano.jpg/800px-Chicharr%C3%B3n_peruano.jpg', 'Cusco'),
    ('chicharron-de-alpaca', 'Chicharrón de Alpaca', 'fondo', '["Carne de alpaca", "Chuño", "Maíz tostado", "Sal"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Chicharr%C3%B3n_de_alpaca.jpg/800px-Chicharr%C3%B3n_de_alpaca.jpg', 'Puno'),
    ('chicharron-de-cerdo', 'Chicharrón de Cerdo', 'fondo', '["Cerdo", "Sal", "Maíz tostado", "Papas"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Chicharr%C3%B3n_peruano.jpg/800px-Chicharr%C3%B3n_peruano.jpg', 'Moquegua'),
    ('chicharron-de-cerdo-con-maiz-tostado', 'Chicharrón de Cerdo con Maíz Tostado', 'fondo', '["Cerdo", "Maíz tostado (cancha)", "Papas"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Chicharr%C3%B3n_peruano.jpg/800px-Chicharr%C3%B3n_peruano.jpg', 'Tacna'),
    ('chicharron-de-lagarto', 'Chicharrón de Lagarto', 'fondo', '["Cola de lagarto (Yacaré)", "Harina", "Aceite", "Yuca"]', 'https://i.ytimg.com/vi/Example_Lagarto.jpg', 'Madre de Dios'),
    ('chicharron-de-oxapampa', 'Chicharrón de Oxapampa', 'fondo', '["Cerdo", "Yuca", "Salsa criolla", "Mote"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Chicharr%C3%B3n_peruano.jpg/800px-Chicharr%C3%B3n_peruano.jpg', 'Pasco'),
    ('chicharron-de-pota', 'Chicharrón de Pota', 'entrada', '["Pota (calamar gigante)", "Harina", "Huevo", "Mostaza", "Yuca"]', 'https://i.ytimg.com/vi/Example_ChicharronPota.jpg', 'Callao'),
    ('chifles', 'Chifles', 'entrada', '["Plátano verde", "Aceite", "Sal", "Cancha (opcional)", "Cecina (opcional)"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Chifles.jpg/800px-Chifles.jpg', 'Piura'),
    ('chilcano-de-carachama', 'Chilcano de Carachama', 'sopa', '["Carachama (pez prehistórico)", "Sacha culantro", "Ajos", "Yuca"]', 'https://i.ytimg.com/vi/Example_Carachama.jpg', 'Ucayali'),
    ('chilcano-de-pescado', 'Chilcano de Pescado', 'sopa', '["Espinazo y cabeza de pescado", "Cebolla china", "Apio", "Kion (jengibre)"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Chilcano_de_pescado.jpg/800px-Chilcano_de_pescado.jpg', 'Callao'),
    ('chilcano-de-pisco', 'Chilcano de Pisco', 'bebida', '["Pisco", "Ginger Ale", "Limón", "Hielo"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Chilcano.jpg/800px-Chilcano.jpg', 'Ica'),
    ('chimbango-de-tres-higos', 'Chimbango de Tres Higos', 'bebida', '["Higos negros, blancos y rojos", "Agua", "Pisco"]', 'https://i.ytimg.com/vi/Example_Chimbango.jpg', 'Moquegua'),
    ('chinguirito', 'Chinguirito', 'entrada', '["Pez guitarra seco (deshilachado)", "Limón", "Ají limo", "Cebolla roja", "Zarandaja"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Chinguirito.jpg/800px-Chinguirito.jpg', 'Lambayeque'),
    ('chinguirito-bebida', 'Chinguirito (Bebida)', 'bebida', '["Agua de coco (pipa)", "Aguardiente de caña"]', 'https://i.ytimg.com/vi/Example_ChinguiritoBebida.jpg', 'Tumbes'),
    ('chirimpico', 'Chirimpico', 'fondo', '["Menudencia de cabrito (hígado, sangre, tripas)", "Zapallo loche", "Culantro", "Ají verde"]', 'https://i.ytimg.com/vi/Example_Chirimpico.jpg', 'Lambayeque'),
    ('chiriuchu', 'Chiriuchu', 'fondo', '["Cuy al horno", "Gallina sancochada", "Cecina", "Torreja de maíz", "Cochayuyo (algas)", "Queso", "Rocoto"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Chiriuchu.jpg/800px-Chiriuchu.jpg', 'Cusco'),
    ('choclo-con-queso', 'Choclo con Queso', 'entrada', '["Choclo gigante (Urubamba)", "Queso paria o fresco", "Anís"]', 'https://upload.wikimedia.org/wikipedia/commons/1/1d/Choclo_con_queso.jpg', 'Cusco'),
    ('choclo-con-queso-pachia', 'Choclo con Queso (Pachía)', 'entrada', '["Choclo de Pachía", "Queso fresco", "Anís"]', 'https://upload.wikimedia.org/wikipedia/commons/1/1d/Choclo_con_queso.jpg', 'Tacna'),
    ('chocotejas', 'Chocotejas', 'postre', '["Chocolate", "Manjar blanco", "Pecanas", "Pasas borrachas"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Tejas_dulce.jpg/800px-Tejas_dulce.jpg', 'Ica'),
    ('choritos-a-la-chalaca', 'Choritos a la Chalaca', 'entrada', '["Choros (mejillones)", "Cebolla roja", "Tomate", "Maíz (choclo)", "Limón", "Ají limo"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Choritos_a_la_chalaca.jpg/800px-Choritos_a_la_chalaca.jpg', 'Callao'),
    ('choritos-a-la-chalaca-version-picante', 'Choritos a la Chalaca (Versión Picante)', 'entrada', '["Choros", "Rocoto", "Limón", "Cebolla"]', 'https://i.ytimg.com/vi/Example_ChoritosPicante.jpg', 'Callao'),
    ('chorizo-ayacuchano', 'Chorizo Ayacuchano', 'fondo', '["Carne de cerdo molida", "Ají panca", "Vinagre", "Ajos", "Tripas"]', 'https://i.ytimg.com/vi/Example_Chorizo.jpg', 'Ayacucho'),
    ('chorizo-regional', 'Chorizo Regional', 'otro', '["Carne de cerdo", "Achiote", "Ajos", "Tripa fina"]', 'https://i.ytimg.com/vi/Example_ChorizoSanMartin.jpg', 'San Martín'),
    ('chumbeque', 'Chumbeque', 'postre', '["Harina", "Yemas", "Manteca", "Miel de frutas", "Achiote"]', 'https://i.ytimg.com/vi/Example_Chumbeque.jpg', 'Piura'),
    ('chuno-cola', 'Chuño Cola', 'sopa', '["Harina de chuño negro", "Carne", "Papas", "Verduras"]', 'https://i.ytimg.com/vi/Example_ChunoColaPuno.jpg', 'Puno'),
    ('chuno-pasi', 'Chuño Pasi', 'guarnicion', '["Chuño negro (remojado)", "Huevos", "Queso", "Manteca"]', 'https://i.ytimg.com/vi/Example_ChunoPasi.jpg', 'Huancavelica'),
    ('chupe-de-camarones', 'Chupe de Camarones', 'sopa', '["Camarones de río", "Papa amarilla", "Arroz", "Leche", "Queso", "Huacatay"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Chupe_de_camarones.jpg/800px-Chupe_de_camarones.jpg', 'Arequipa'),
    ('chupe-de-cangrejo', 'Chupe de Cangrejo', 'sopa', '["Cangrejos del manglar", "Leche", "Huevo", "Zapallo", "Fideos", "Orégano"]', 'https://i.ytimg.com/vi/Example_ChupeCangrejo.jpg', 'Tumbes'),
    ('chupe-de-pallares', 'Chupe de Pallares', 'sopa', '["Pallares verdes", "Leche", "Queso", "Huevo", "Pescado (opcional)"]', 'https://i.ytimg.com/vi/Example_ChupePallares.jpg', 'Ica'),
    ('chupe-de-quinua', 'Chupe de Quinua', 'sopa', '["Quinua", "Verduras", "Queso", "Leche", "Huevo"]', 'https://i.ytimg.com/vi/Example_ChupeQuinua.jpg', 'Puno'),
    ('chupe-verde-yacu-chupe', 'Chupe Verde (Yacu Chupe)', 'sopa', '["Papas", "Queso fresco", "Huevos", "Muña", "Paico", "Ruda"]', 'https://i.ytimg.com/vi/Example_ChupeVerde.jpg', 'Junín'),
    ('clarito', 'Clarito', 'bebida', '["Chicha de jora (parte superior)"]', 'https://i.ytimg.com/vi/Example_Clarito.jpg', 'Tumbes'),
    ('cocktail-de-langostinos', 'Cocktail de Langostinos', 'entrada', '["Langostinos", "Salsa Golf (Mayonesa + Ketchup)", "Palta", "Lechuga"]', 'https://i.ytimg.com/vi/Example_CocktailLangostinos.jpg', 'Tumbes'),
    ('coctel-de-algarrobina', 'Coctel de Algarrobina', 'bebida', '["Algarrobina (jarabe de algarrobo)", "Pisco", "Leche", "Yema de huevo", "Hielo"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Cocktail_de_Algarrobina.jpg/800px-Cocktail_de_Algarrobina.jpg', 'Piura'),
    ('conejo-al-horno', 'Conejo al Horno', 'fondo', '["Conejo", "Ají panca", "Vinagre", "Ajos"]', 'https://i.ytimg.com/vi/Example_Conejo.jpg', 'Lambayeque'),
    ('conserva-de-higos', 'Conserva de Higos', 'postre', '["Higos maduros", "Azúcar", "Clavo de olor"]', 'https://i.ytimg.com/vi/Example_Higos.jpg', 'Cajamarca'),
    ('copus', 'Copús', 'fondo', '["Cabeza de cerdo", "Carnero", "Plátanos maduros", "Camotes"]', 'https://i.ytimg.com/vi/Example_Copus.jpg', 'Piura'),
    ('cordero-al-palo', 'Cordero al Palo', 'fondo', '["Cordero entero", "Sal", "Ajos", "Cerveza", "Limón"]', 'https://i.ytimg.com/vi/Example_CorderoPalo.jpg', 'Junín'),
    ('cordero-de-candarave', 'Cordero de Candarave', 'fondo', '["Cordero de Candarave", "Sal", "Carbón / Leña"]', 'https://i.ytimg.com/vi/Example_CorderoCandarave.jpg', 'Tacna'),
    ('costillar-dorado', 'Costillar Dorado', 'fondo', '["Costillar de cordero", "Ajos", "Vinagre tinto", "Sal", "Comino"]', 'https://i.ytimg.com/vi/Example_Costillar.jpg', 'Arequipa'),
    ('costillar-frito', 'Costillar Frito', 'fondo', '["Costillar de cordero", "Ajos", "Sal", "Aceite"]', 'https://i.ytimg.com/vi/Example_CostillarCusco.jpg', 'Cusco'),
    ('cuchicanca', 'Cuchicanca', 'fondo', '["Cerdo (lechón)", "Vinagre", "Ají mirasol", "Ajos"]', 'https://i.ytimg.com/vi/Example_Cuchicanca.jpg', 'Áncash'),
    ('cutacho', 'Cutacho', 'guarnicion', '["Plátano verde", "Maní", "Culantro", "Cebolla"]', 'https://i.ytimg.com/vi/Example_Cutacho.jpg', 'San Martín'),
    ('cuy-al-horno', 'Cuy al Horno', 'fondo', '["Cuy entero", "Huacatay", "Comino", "Ajos", "Papas"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Cuy_al_horno.jpg/800px-Cuy_al_horno.jpg', 'Cusco'),
    ('cuy-chactado', 'Cuy Chactado', 'fondo', '["Cuy entero", "Maíz molido", "Aceite", "Ajos", "Sal"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Cuy_chactado.jpg/800px-Cuy_chactado.jpg', 'Ayacucho'),
    ('cuy-colorado', 'Cuy Colorado', 'fondo', '["Cuy", "Ají panca (colorado)", "Maní", "Papas", "Arroz"]', 'https://i.ytimg.com/vi/Example_CuyColorado.jpg', 'Huancavelica'),
    ('cuy-frito', 'Cuy Frito', 'fondo', '["Cuy", "Harina de maíz", "Aceite", "Papas", "Salsa criolla"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Cuy_chactado.jpg/800px-Cuy_chactado.jpg', 'Tacna'),
    ('cuy-frito-con-papas', 'Cuy Frito con Papas', 'fondo', '["Cuy entero", "Papas", "Ají panca", "Ajos"]', 'https://upload.wikimedia.org/wikipedia/commons/1/16/Cuy_chactado.jpg', 'Amazonas'),
    ('cuy-frito-con-picante-de-papa', 'Cuy Frito con Picante de Papa', 'fondo', '["Cuy entero", "Papa", "Ají panca", "Maní", "Ajos"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Cuy_frito_con_picante_de_papas.jpg/800px-Cuy_frito_con_picante_de_papas.jpg', 'Cajamarca'),
    ('cuy-frito-moqueguano', 'Cuy Frito Moqueguano', 'fondo', '["Cuy entero", "Maíz molido (chuchoca)", "Papas", "Ensalada", "Aceite"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Cuy_chactado.jpg/800px-Cuy_chactado.jpg', 'Moquegua'),
    ('cuy-guisado-huamachuco', 'Cuy Guisado (Huamachuco)', 'fondo', '["Cuy", "Ají panca", "Papas", "Arroz de trigo"]', 'https://i.ytimg.com/vi/Example_CuyGuisado.jpg', 'La Libertad'),
    ('cuy-relleno', 'Cuy Relleno', 'fondo', '["Cuy entero", "Vísceras del cuy", "Huacatay", "Cebolla", "Maní", "Menta"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Cuy_Relleno.jpg/800px-Cuy_Relleno.jpg', 'Apurímac'),
    ('datiles-rellenos', 'Dátiles Rellenos', 'postre', '["Dátiles", "Nueces", "Manjar blanco", "Azúcar"]', 'https://i.ytimg.com/vi/Example_Datiles.jpg', 'Lambayeque'),
    ('dulce-de-alcayota', 'Dulce de Alcayota', 'postre', '["Alcayota (calabaza blanca)", "Azúcar", "Clavo", "Canela"]', 'https://i.ytimg.com/vi/Example_Alcayota.jpg', 'Ica'),
    ('dulce-de-castana', 'Dulce de Castaña', 'postre', '["Castañas amazónicas", "Leche condensada", "Azúcar"]', 'https://i.ytimg.com/vi/Example_DulceCastana.jpg', 'Madre de Dios'),
    ('dulce-de-caya-oca', 'Dulce de Caya (Oca)', 'postre', '["Oca (tubérculo)", "Azúcar", "Canela"]', 'https://i.ytimg.com/vi/Example_DulceOca.jpg', 'Junín'),
    ('dulce-de-grosella', 'Dulce de Grosella', 'postre', '["Grosellas", "Azúcar", "Canela"]', 'https://i.ytimg.com/vi/Example_DulceGrosella.jpg', 'Amazonas'),
    ('dulce-de-nispero', 'Dulce de Níspero', 'postre', '["Nísperos de palo", "Azúcar", "Canela"]', 'https://i.ytimg.com/vi/Example_Nispero.jpg', 'Apurímac'),
    ('dulce-de-papaya', 'Dulce de Papaya', 'postre', '["Papaya verde", "Azúcar", "Clavo de olor", "Canela"]', 'https://i.ytimg.com/vi/Example_DulcePapaya.jpg', 'Huánuco'),
    ('dulce-de-pechiche', 'Dulce de Pechiche', 'postre', '["Pechiche (fruto local)", "Chancaca", "Clavo de olor"]', 'https://i.ytimg.com/vi/Example_Pechiche.jpg', 'Tumbes'),
    ('empanadas-de-queso', 'Empanadas de Queso', 'otro', '["Harina", "Manteca", "Queso", "Azúcar impalpable"]', 'https://i.ytimg.com/vi/Example_EmpanadaQueso.jpg', 'Huánuco'),
    ('enrollado-de-mero', 'Enrollado de Mero', 'fondo', '["Filete de mero", "Langostinos", "Salsa de mariscos", "Mantequilla"]', 'https://i.ytimg.com/vi/Example_EnrolladoMero.jpg', 'Tumbes'),
    ('ensalada-de-chonta', 'Ensalada de Chonta', 'entrada', '["Chonta (palmito fresco)", "Limón", "Aceite", "Tomate"]', 'https://i.ytimg.com/vi/Example_Chonta.jpg', 'Ucayali'),
    ('ensalada-de-pallares', 'Ensalada de Pallares', 'entrada', '["Pallares cocidos", "Cebolla", "Tomate", "Vinagre", "Ají limo"]', 'https://i.ytimg.com/vi/Example_EnsaladaPallares.jpg', 'Ica'),
    ('ensalada-de-pata-de-burro', 'Ensalada de Pata de Burro', 'entrada', '["Caracol ''Pata de Burro''", "Limón", "Cebolla", "Culantro"]', 'https://i.ytimg.com/vi/Example_PataBurro.jpg', 'Tumbes'),
    ('escabeche-de-pescado', 'Escabeche de Pescado', 'fondo', '["Filete de pescado frito", "Cebolla roja", "Ají amarillo", "Vinagre tinto", "Ají panca"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Escabeche_de_pescado.jpg/800px-Escabeche_de_pescado.jpg', 'Lima'),
    ('escribano', 'Escribano', 'entrada', '["Papas sancochadas", "Tomate", "Rocoto", "Vinagre", "Aceite"]', 'https://i.ytimg.com/vi/Example_Escribano.jpg', 'Arequipa'),
    ('espesado', 'Espesado', 'sopa', '["Choclo molido", "Carne de pecho de res", "Zapallo loche", "Culantro", "Caigua"]', 'https://i.ytimg.com/vi/Example_Espesado.jpg', 'Lambayeque'),
    ('estofado-de-carnero', 'Estofado de Carnero', 'fondo', '["Carne de carnero", "Ají panca", "Chicha de jora", "Papas", "Arvejas"]', 'https://i.ytimg.com/vi/Example_EstofadoCarnero.jpg', 'Cajamarca'),
    ('frejol-colado', 'Frejol Colado', 'postre', '["Frijoles negros o canarios", "Azúcar (chancaca)", "Clavo de olor", "Ajonjolí", "Leche"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Frejol_colado.jpg/800px-Frejol_colado.jpg', 'Ica'),
    ('fricase-puneno', 'Fricasé Puneño', 'fondo', '["Cerdo", "Mote", "Chuño", "Ají amarillo", "Pan molido"]', 'https://i.ytimg.com/vi/Example_Fricase.jpg', 'Puno'),
    ('frito-cajamarquino', 'Frito Cajamarquino', 'fondo', '["Vísceras de cerdo", "Carne de cerdo", "Papa sancochada", "Achiote", "Mote"]', 'https://i.ytimg.com/vi/Example_FritoCajamarquino.jpg', 'Cajamarca'),
    ('frito-chiclayano', 'Frito Chiclayano', 'fondo', '["Costillas de cerdo", "Vinagre", "Ají panca", "Yuca"]', 'https://i.ytimg.com/vi/Example_FritoChiclayano.jpg', 'Lambayeque'),
    ('frito-trujillano', 'Frito Trujillano', 'fondo', '["Costillas de cerdo", "Vinagre", "Ají panca", "Ajos", "Yuca"]', 'https://i.ytimg.com/vi/Example_FritoTrujillano.jpg', 'La Libertad'),
    ('frutillada', 'Frutillada', 'bebida', '["Chicha de jora", "Frutillas (fresas)", "Harina de maíz (para espesar)"]', 'https://i.ytimg.com/vi/Example_Frutillada.jpg', 'Cusco'),
    ('gamitana-frita', 'Gamitana Frita', 'fondo', '["Pescado Gamitana", "Harina", "Aceite", "Patacones"]', 'https://i.ytimg.com/vi/Example_Gamitana.jpg', 'Loreto'),
    ('gelatina-de-patita', 'Gelatina de Patita', 'postre', '["Pata de res", "Azúcar", "Canela", "Clavo", "Limón"]', 'https://i.ytimg.com/vi/Example_GelatinaPatita.jpg', 'Junín'),
    ('goulash-con-spatzle', 'Goulash con Spätzle', 'fondo', '["Carne de res", "Paprika", "Tomate", "Harina (para el Spätzle)", "Huevo"]', 'https://i.ytimg.com/vi/Example_GoulashPozuzo.jpg', 'Pasco'),
    ('guarapo', 'Guarapo', 'bebida', '["Caña de azúcar"]', 'https://i.ytimg.com/vi/Example_Guarapo.jpg', 'Huánuco'),
    ('guargueros', 'Guargüeros', 'postre', '["Harina", "Yemas", "Pisco", "Manjar blanco"]', 'https://i.ytimg.com/vi/Example_Guargueros.jpg', 'Moquegua'),
    ('guiso-de-quinua', 'Guiso de Quinua', 'fondo', '["Quinua", "Queso", "Papas", "Achiote"]', 'https://i.ytimg.com/vi/Example_GuisoQuinua.jpg', 'Huancavelica'),
    ('habas-tostadas-puspu', 'Habas Tostadas (Puspu)', 'entrada', '["Habas secas", "Sal", "Grasa de cerdo (opcional)"]', 'https://i.ytimg.com/vi/Example_HabasTostadas.jpg', 'Junín'),
    ('hojaldrilla', 'Hojaldrilla', 'postre', '["Harina", "Manteca", "Miel"]', 'https://i.ytimg.com/vi/Example_Hojaldrilla.jpg', 'Moquegua'),
    ('huatia', 'Huatia', 'fondo', '["Papas nativas", "Ocas", "Habas", "Queso (opcional)"]', 'https://upload.wikimedia.org/wikipedia/commons/e/eb/Huatia.jpg', 'Puno'),
    ('human-caldo-caldo-de-cabeza', 'Human Caldo (Caldo de Cabeza)', 'sopa', '["Cabeza de carnero", "Papas", "Mote", "Paico"]', 'https://i.ytimg.com/vi/Example_HumanCaldo.jpg', 'Junín'),
    ('humitas', 'Humitas', 'entrada', '["Choclo molido", "Manteca", "Queso", "Panca"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Humita.jpg/800px-Humita.jpg', 'Junín'),
    ('humitas-cajamarquinas', 'Humitas Cajamarquinas', 'entrada', '["Choclo", "Manteca", "Queso (saladas)", "Pasas y azúcar (dulces)"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Humita.jpg/800px-Humita.jpg', 'Cajamarca'),
    ('humitas-de-maiz', 'Humitas de Maíz', 'entrada', '["Choclo tierno", "Manteca", "Sal (o azúcar)", "Queso"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Humita.jpg/800px-Humita.jpg', 'Huánuco'),
    ('humitas-de-queso', 'Humitas de Queso', 'entrada', '["Choclo tierno", "Manteca", "Queso fresco", "Panca de choclo"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Humita.jpg/800px-Humita.jpg', 'Ayacucho'),
    ('humitas-de-tacna', 'Humitas de Tacna', 'entrada', '["Maíz tierno", "Manteca", "Pasas", "Canela"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Humita.jpg/800px-Humita.jpg', 'Tacna'),
    ('humitas-dulces', 'Humitas Dulces', 'entrada', '["Choclo tierno", "Azúcar", "Pasas", "Canela"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Humita.jpg/800px-Humita.jpg', 'Amazonas'),
    ('inchicapi', 'Inchicapi', 'sopa', '["Gallina", "Maní tostado molido", "Harina de maíz", "Sacha culantro", "Yuca"]', 'https://i.ytimg.com/vi/Example_InchicapiUca.jpg', 'Ucayali'),
    ('inchicapi-de-gallina', 'Inchicapi de Gallina', 'sopa', '["Gallina", "Maní pelado", "Harina de maíz", "Sacha culantro", "Yuca"]', 'https://i.ytimg.com/vi/Example_Inchicapi.jpg', 'San Martín'),
    ('ispis-fritos', 'Ispis Fritos', 'entrada', '["Ispis (pececillos del lago)", "Harina de maíz", "Aceite", "Mote"]', 'https://i.ytimg.com/vi/Example_Ispis.jpg', 'Puno'),
    ('jaka-cashqui', 'Jaka Cashqui', 'sopa', '["Cuy", "Papa", "Queso", "Habas", "Fideos"]', 'https://i.ytimg.com/vi/Example_JakaCashqui.jpg', 'Áncash'),
    ('jalea-mixta', 'Jalea Mixta', 'fondo', '["Pescado", "Langostinos", "Calamares", "Yuca", "Harina"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Jalea_peruana.jpg/800px-Jalea_peruana.jpg', 'Callao'),
    ('jamon-de-otuzco', 'Jamón de Otuzco', 'entrada', '["Pierna de cerdo", "Sal", "Achiote", "Pimienta"]', 'https://i.ytimg.com/vi/Example_JamonOtuzco.jpg', 'La Libertad'),
    ('jamon-huaracino', 'Jamón Huaracino', 'entrada', '["Pierna de cerdo", "Sal", "Ajos", "Achiote"]', 'https://i.ytimg.com/vi/Example_JamonHuaracino.jpg', 'Áncash'),
    ('juane-de-gallina', 'Juane de Gallina', 'fondo', '["Arroz", "Gallina", "Huevo", "Aceitunas", "Palillo (cúrcuma)", "Hojas de bijao"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Juane_peruano.jpg/800px-Juane_peruano.jpg', 'Ucayali'),
    ('juane-de-yuca', 'Juane de Yuca', 'fondo', '["Yuca rallada", "Gallina", "Huevo", "Hojas de bijao", "Manteca"]', 'https://i.ytimg.com/vi/Example_JuaneYuca.jpg', 'Amazonas'),
    ('jugo-de-maca', 'Jugo de Maca', 'bebida', '["Raíz de maca fresca o seca", "Agua", "Azúcar", "Leche (opcional)"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Maca_roots.jpg/800px-Maca_roots.jpg', 'Junín'),
    ('kamchi-cancha', 'Kamchi (Cancha)', 'guarnicion', '["Maíz seco para tostar", "Aceite", "Sal"]', 'https://i.ytimg.com/vi/Example_Cancha.jpg', 'Junín'),
    ('kankacho', 'Kankacho', 'fondo', '["Cordero", "Cerveza negra", "Ají panca", "Papas nativas", "Moraya"]', 'https://upload.wikimedia.org/wikipedia/commons/6/66/Kankacho.jpg', 'Puno'),
    ('kapchi-de-chuno', 'Kapchi de Chuño', 'guarnicion', '["Chuño remojado", "Queso fresco", "Leche", "Huevos", "Palillo"]', 'https://i.ytimg.com/vi/Example_Kapchi.jpg', 'Apurímac'),
    ('kapchi-de-setas', 'Kapchi de Setas', 'fondo', '["Setas silvestres", "Habas verdes", "Papas", "Leche", "Queso", "Huacatay"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Kapchi_de_habas.jpg/800px-Kapchi_de_habas.jpg', 'Cusco'),
    ('king-kong', 'King Kong', 'postre', '["Harina", "Yemas", "Manjar blanco", "Dulce de piña", "Dulce de maní"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/King_Kong_San_Roque.jpg/800px-King_Kong_San_Roque.jpg', 'Lambayeque'),
    ('langosta-a-la-parrilla', 'Langosta a la Parrilla', 'fondo', '["Langosta verde de Tumbes", "Mantequilla", "Ajo", "Perejil"]', 'https://i.ytimg.com/vi/Example_Langosta.jpg', 'Tumbes'),
    ('lawa-de-choclo', 'Lawa de Choclo', 'sopa', '["Choclo maduro molido", "Caldo de carne", "Papas", "Huacatay", "Huevo"]', 'https://i.ytimg.com/vi/Example_Lawa.jpg', 'Cusco'),
    ('leche-de-monja', 'Leche de Monja', 'bebida', '["Huevos", "Pisco", "Limón", "Azúcar"]', 'https://i.ytimg.com/vi/Example_LecheMonja.jpg', 'Moquegua'),
    ('leche-de-tigre', 'Leche de Tigre', 'entrada', '["Jugo de limón", "Fumet de pescado", "Ají limo", "Culantro", "Trozos de pescado"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Leche_de_tigre.jpg/800px-Leche_de_tigre.jpg', 'Callao'),
    ('lechon-al-horno', 'Lechón al Horno', 'fondo', '["Cerdo entero o trozado", "Ají panca", "Ajos", "Sal", "Pimienta"]', 'https://i.ytimg.com/vi/Example_LechonCusco.jpg', 'Cusco'),
    ('lechon-al-horno-orcotuna', 'Lechón al Horno (Orcotuna)', 'fondo', '["Cerdo tierno", "Ají panca", "Ajos", "Comino", "Sal"]', 'https://i.ytimg.com/vi/Example_LechonOrcotuna.jpg', 'Junín'),
    ('licor-de-damasco', 'Licor de Damasco', 'bebida', '["Damascos", "Pisco", "Azúcar"]', 'https://i.ytimg.com/vi/Example_LicorDamasco.jpg', 'Tacna'),
    ('licor-de-mora', 'Licor de Mora', 'bebida', '["Moras silvestres", "Aguardiente", "Azúcar"]', 'https://i.ytimg.com/vi/Example_LicorMora.jpg', 'Amazonas'),
    ('llunca-cashqui', 'Llunca Cashqui', 'sopa', '["Trigo resbalado (llunca)", "Gallina", "Papa", "Huacatay", "Orégano"]', 'https://i.ytimg.com/vi/Example_Llunca.jpg', 'Áncash'),
    ('locro-de-gallina', 'Locro de Gallina', 'fondo', '["Gallina de chacra", "Papas amarillas", "Ají mirasol", "Cebolla"]', 'https://i.ytimg.com/vi/Example_LocroGallina.jpg', 'Huánuco'),
    ('locro-de-pecho', 'Locro de Pecho', 'fondo', '["Pecho de res", "Papas harinosas", "Ají panca", "Ajos"]', 'https://i.ytimg.com/vi/Example_LocroPecho.jpg', 'Arequipa'),
    ('lomo-saltado', 'Lomo Saltado', 'fondo', '["Lomo fino de res", "Cebolla roja gruesa", "Tomate grueso", "Sillao (soya)", "Vinagre", "Ají amarillo", "Papas fritas"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Lomo_saltado.jpg/800px-Lomo_saltado.jpg', 'Lima'),
    ('macerado-de-damasco', 'Macerado de Damasco', 'bebida', '["Damascos", "Pisco", "Azúcar"]', 'https://i.ytimg.com/vi/Example_MaceradoDamasco.jpg', 'Moquegua'),
    ('machacado-de-membrillo', 'Machacado de Membrillo', 'postre', '["Membrillo", "Azúcar"]', 'https://i.ytimg.com/vi/Example_MachacadoMembrillo.jpg', 'La Libertad'),
    ('maduro-relleno', 'Maduro Relleno', 'entrada', '["Plátano maduro (amarillo)", "Carne molida o Queso", "Maní"]', 'https://i.ytimg.com/vi/Example_MaduroRelleno.jpg', 'San Martín'),
    ('majado-de-yuca', 'Majado de Yuca', 'fondo', '["Yuca", "Chicharrón de cerdo", "Cebolla", "Ají amarillo", "Canchita"]', 'https://i.ytimg.com/vi/Example_MajadoYuca.jpg', 'Piura'),
    ('majado-de-yuca-con-chicharron', 'Majado de Yuca con Chicharrón', 'fondo', '["Yuca", "Chicharrón de cerdo", "Cebolla", "Ají amarillo"]', 'https://i.ytimg.com/vi/Example_MajadoYuca.jpg', 'Tumbes'),
    ('majarisco', 'Majarisco', 'fondo', '["Plátano verde (bellaco)", "Langostinos", "Calamares", "Conchas", "Ají amarillo", "Culantro"]', 'https://i.ytimg.com/vi/Example_Majarisco.jpg', 'Tumbes'),
    ('majas-asado', 'Majás Asado', 'fondo', '["Majás (picuro)", "Sacha culantro", "Yuca"]', 'https://i.ytimg.com/vi/Example_Majas.jpg', 'San Martín'),
    ('majaz-asado', 'Majaz Asado', 'fondo', '["Majaz (Picuro)", "Sacha culantro", "Ajos", "Yuca"]', 'https://i.ytimg.com/vi/Example_Majaz.jpg', 'Ucayali'),
    ('malarrabia', 'Malarrabia', 'fondo', '["Plátano maduro", "Queso fresco de cabra", "Achiote", "Pescado salpreso", "Arroz", "Menestra"]', 'https://i.ytimg.com/vi/Example_Malarrabia.jpg', 'Piura'),
    ('malaya-dorada', 'Malaya Dorada', 'fondo', '["Malaya (falda de res)", "Ají panca", "Ajos", "Vinagre"]', 'https://i.ytimg.com/vi/Example_Malaya.jpg', 'Arequipa'),
    ('mancha-pecho', 'Mancha Pecho', 'fondo', '["Carapulcra chinchana", "Sopa seca", "Cerdo", "Albahaca", "Ají panca"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Carapulcra.jpg/800px-Carapulcra.jpg', 'Ica'),
    ('manias', 'Manías', 'guarnicion', '["Arroz", "Pata de cerdo", "Pimentón", "Cebolla"]', 'https://i.ytimg.com/vi/Example_Manias.jpg', 'Lambayeque'),
    ('manjar-blanco', 'Manjar Blanco', 'postre', '["Leche fresca de vaca", "Azúcar", "Canela"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Manjar_blanco_peruano.jpg/800px-Manjar_blanco_peruano.jpg', 'Cajamarca'),
    ('masato', 'Masato', 'bebida', '["Yuca", "Agua", "Azúcar (opcional)"]', 'https://upload.wikimedia.org/wikipedia/commons/9/98/Masato.jpg', 'Ucayali'),
    ('mazamorra-de-airampo', 'Mazamorra de Airampo', 'postre', '["Semillas de airampo", "Frutas secas", "Manzana", "Fécula de camote"]', 'https://i.ytimg.com/vi/Example_Airampo.jpg', 'Arequipa'),
    ('mazamorra-de-calabaza', 'Mazamorra de Calabaza', 'postre', '["Calabaza madura", "Chancaca", "Canela", "Leche", "Harina"]', 'https://i.ytimg.com/vi/Example_MazamorraCalabaza.jpg', 'Junín'),
    ('mazamorra-de-llipta', 'Mazamorra de Llipta', 'postre', '["Maíz morado (harina)", "Agua de ceniza (lipta)", "Hierbas aromáticas"]', 'https://i.ytimg.com/vi/Example_Llipta.jpg', 'Ayacucho'),
    ('mazamorra-de-quinua', 'Mazamorra de Quinua', 'postre', '["Harina de quinua", "Leche", "Canela", "Azúcar", "Pasas"]', 'https://i.ytimg.com/vi/Example_MazamorraQuinua.jpg', 'Puno'),
    ('mazamorra-de-tocosh', 'Mazamorra de Tocosh', 'postre', '["Tocosh (papa fermentada)", "Azúcar", "Canela", "Clavo", "Naranja"]', 'https://i.ytimg.com/vi/Example_TocoshPasco.jpg', 'Pasco'),
    ('mazamorra-morada', 'Mazamorra Morada', 'postre', '["Maíz morado", "Piña", "Membrillo", "Harina de camote", "Canela", "Clavo"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Mazamorra_morada.jpg/800px-Mazamorra_morada.jpg', 'Lima'),
    ('mercado-viejo-jugo', 'Mercado Viejo (Jugo)', 'bebida', '["Frutillas (fresas)", "Leche", "Huevo (opcional)", "Azúcar"]', 'https://i.ytimg.com/vi/Example_JugoMercado.jpg', 'Tacna'),
    ('mermelada-de-quito-quito', 'Mermelada de Quito Quito', 'postre', '["Quito Quito (fruto local)", "Azúcar", "Canela"]', 'https://i.ytimg.com/vi/Example_QuitoQuito.jpg', 'Pasco'),
    ('miel-con-quesillo', 'Miel con Quesillo', 'postre', '["Quesillo (queso fresco sin sal)", "Chancaca (miel de caña)"]', 'https://i.ytimg.com/vi/Example_MielQuesillo.jpg', 'Amazonas'),
    ('migadito', 'Migadito', 'sopa', '["Pan remojado", "Menudencia de cerdo o ave", "Papas", "Achiote"]', 'https://i.ytimg.com/vi/Example_Migadito.jpg', 'Lambayeque'),
    ('mollejitas-al-sillao', 'Mollejitas al Sillao', 'entrada', '["Mollejas de pollo", "Sillao", "Vinagre", "Limón", "Yuca"]', 'https://i.ytimg.com/vi/Example_Mollejitas.jpg', 'La Libertad'),
    ('mondongo-ayacuchano', 'Mondongo Ayacuchano', 'sopa', '["Mote pelado", "Carne de res", "Mondongo (panza)", "Tocino", "Hierbabuena"]', 'https://i.ytimg.com/vi/Example_Mondongo.jpg', 'Ayacucho'),
    ('mondongo-huancavelicano', 'Mondongo Huancavelicano', 'sopa', '["Mote (maíz pelado)", "Carne de res", "Carne de carnero", "Mondongo", "Cabeza de vacuno"]', 'https://i.ytimg.com/vi/Example_MondongoH.jpg', 'Huancavelica'),
    ('moqueguano-de-camarones', 'Moqueguano de Camarones', 'fondo', '["Camarones de río", "Maíz molido", "Leche", "Rocoto", "Huacatay"]', 'https://i.ytimg.com/vi/Example_MoqueguanoCamaron.jpg', 'Moquegua'),
    ('morusa-de-pallares', 'Morusa de Pallares', 'guarnicion', '["Pallares secos", "Tocino o cerdo", "Leche", "Queso", "Mantequilla"]', 'https://i.ytimg.com/vi/Example_Morusa.jpg', 'Ica'),
    ('muchame-de-atun', 'Muchame de Atún', 'entrada', '["Atún seco o en conserva (originalmente delfín, hoy prohibido)", "Palta", "Tomate", "Galletas de soda", "Aceite de oliva"]', 'https://i.ytimg.com/vi/Example_Muchame.jpg', 'Callao'),
    ('muyuchi', 'Muyuchi', 'postre', '["Leche fresca", "Maní", "Ajonjolí", "Coco", "Canela"]', 'https://i.ytimg.com/vi/Example_Muyuchi.jpg', 'Ayacucho'),
    ('natilla-piurana', 'Natilla Piurana', 'postre', '["Leche de cabra", "Chancaca", "Harina de arroz"]', 'https://i.ytimg.com/vi/Example_Natilla.jpg', 'Piura'),
    ('nina-juane', 'Nina Juane', 'fondo', '["Pescado fresco", "Huevo batido", "Sacha culantro", "Hojas de bijao"]', 'https://i.ytimg.com/vi/Example_NinaJuane.jpg', 'Ucayali'),
    ('nogada-de-camarones', 'Nogada de Camarones', 'fondo', '["Camarones", "Nueces (nogal)", "Leche", "Pan", "Cebolla"]', 'https://i.ytimg.com/vi/Example_Nogada.jpg', 'Moquegua'),
    ('ocopa-arequipena', 'Ocopa Arequipeña', 'entrada', '["Ají mirasol", "Huacatay", "Maní tostado", "Queso fresco", "Galletas de animalito"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Ocopa.jpg/800px-Ocopa.jpg', 'Arequipa'),
    ('olluquito-con-charqui', 'Olluquito con Charqui', 'fondo', '["Olluco", "Charqui de alpaca", "Papas", "Perejil"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Olluquito_con_charqui.jpg/800px-Olluquito_con_charqui.jpg', 'Huancavelica'),
    ('pacamuto', 'Pacamuto', 'fondo', '["Carne de res", "Cebolla", "Pimiento", "Palos de brocheta"]', 'https://i.ytimg.com/vi/Example_Pacamuto.jpg', 'Madre de Dios'),
    ('pachamanca-a-la-olla-estilo-huanca', 'Pachamanca a la Olla (Estilo Huanca)', 'fondo', '["Carne de cerdo", "Carnero", "Papas", "Habas", "Camote", "Chincho", "Huacatay"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Pachamanca.jpg/800px-Pachamanca.jpg', 'Junín'),
    ('pachamanca-ancashina', 'Pachamanca Ancashina', 'fondo', '["Cerdo", "Pollo", "Cuy", "Papas", "Ocas", "Habas", "Chincho"]', 'https://upload.wikimedia.org/wikipedia/commons/9/96/Pachamanca.jpg', 'Áncash'),
    ('pachamanca-ayacuchana', 'Pachamanca Ayacuchana', 'fondo', '["Cerdo", "Cordero", "Pollo", "Papas", "Habas", "Humitas", "Chincho"]', 'https://upload.wikimedia.org/wikipedia/commons/9/96/Pachamanca.jpg', 'Ayacucho'),
    ('pachamanca-cerrena', 'Pachamanca Cerreña', 'fondo', '["Carnero", "Res", "Papas nativas", "Habas", "Chincho", "Piedras calientes"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Pachamanca.jpg/800px-Pachamanca.jpg', 'Pasco'),
    ('pachamanca-huancavelicana', 'Pachamanca Huancavelicana', 'fondo', '["Carnero", "Alpaca", "Cerdo", "Papas nativas", "Ocas", "Habas", "Chincho"]', 'https://upload.wikimedia.org/wikipedia/commons/9/96/Pachamanca.jpg', 'Huancavelica'),
    ('pachamanca-huanuquena', 'Pachamanca Huanuqueña', 'fondo', '["Carne de cerdo (preferida)", "Chincho (hierba)", "Papas", "Camotes", "Humitas"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Pachamanca.jpg/800px-Pachamanca.jpg', 'Huánuco'),
    ('paiche-a-la-loretana', 'Paiche a la Loretana', 'fondo', '["Paiche fresco", "Cebolla", "Tomate", "Ají dulce", "Palillo"]', 'https://i.ytimg.com/vi/Example_PaicheLoretana.jpg', 'Loreto'),
    ('paiche-frito', 'Paiche Frito', 'fondo', '["Filete de paiche fresco", "Sal", "Aceite", "Yuca"]', 'https://i.ytimg.com/vi/Example_PaicheFrito.jpg', 'Ucayali'),
    ('palta-rellena', 'Palta Rellena', 'entrada', '["Palta fuerte de Moquegua", "Pollo deshilachado", "Mayonesa", "Verduras"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Palta_rellena.jpg/800px-Palta_rellena.jpg', 'Moquegua'),
    ('pan-chapla', 'Pan Chapla', 'otro', '["Harina de trigo", "Levadura", "Anís", "Azúcar"]', 'https://i.ytimg.com/vi/Example_PanChapla.jpg', 'Ayacucho'),
    ('pan-chuta', 'Pan Chuta', 'otro', '["Harina de trigo", "Afrecho", "Azúcar", "Anís", "Chicha"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Pan_Chuta.jpg/800px-Pan_Chuta.jpg', 'Cusco'),
    ('pan-con-chimbombo', 'Pan con Chimbombo', 'otro', '["Pescado (cojinova o bonito)", "Pan francés", "Cebolla", "Camote frito"]', 'https://i.ytimg.com/vi/Example_Chimbombo.jpg', 'Callao'),
    ('pan-con-pejerrey-arrebosado', 'Pan con Pejerrey (Arrebosado)', 'fondo', '["Pejerrey", "Huevo", "Harina", "Pan francés", "Salsa criolla"]', 'https://i.ytimg.com/vi/Example_PanPejerrey.jpg', 'Callao'),
    ('pan-de-agua-pan-de-piso', 'Pan de Agua (Pan de Piso)', 'otro', '["Harina", "Agua", "Sal", "Levadura"]', 'https://i.ytimg.com/vi/Example_PanPiso.jpg', 'Cajamarca'),
    ('pan-de-anis-concepcion', 'Pan de Anís (Concepción)', 'otro', '["Harina", "Anís en grano", "Manteca", "Agua"]', 'https://i.ytimg.com/vi/Example_PanAnis.jpg', 'Junín'),
    ('pan-de-arroz', 'Pan de Arroz', 'otro', '["Harina de arroz", "Almidón de yuca", "Manteca", "Agua"]', 'https://i.ytimg.com/vi/Example_PanArroz.jpg', 'San Martín'),
    ('pan-de-maiz-brot', 'Pan de Maíz (Brot)', 'otro', '["Harina de maíz", "Harina de trigo", "Manteca", "Huevos"]', 'https://i.ytimg.com/vi/Example_PanMaiz.jpg', 'Pasco'),
    ('pan-de-torata', 'Pan de Torata', 'otro', '["Trigo", "Manteca", "Levadura", "Agua"]', 'https://i.ytimg.com/vi/Example_PanTorata.jpg', 'Moquegua'),
    ('pan-de-yema-chachapoyas', 'Pan de Yema (Chachapoyas)', 'otro', '["Harina de trigo", "Yemas de huevo", "Manteca", "Azúcar"]', 'https://i.ytimg.com/vi/Example_PanYema.jpg', 'Amazonas'),
    ('pan-marraqueta', 'Pan Marraqueta', 'otro', '["Harina", "Agua", "Sal", "Levadura"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Marraqueta.jpg/800px-Marraqueta.jpg', 'Tacna'),
    ('pango-de-pescado', 'Pango de Pescado', 'fondo', '["Pescado seco (paiche o bagre)", "Plátano verde", "Sacha culantro"]', 'https://i.ytimg.com/vi/Example_Pango.jpg', 'Ucayali'),
    ('panquitas-de-life', 'Panquitas de Life', 'fondo', '["Life (pez de río)", "Saronja", "Ají", "Panca de maíz"]', 'https://i.ytimg.com/vi/Example_Panquitas.jpg', 'Lambayeque'),
    ('papa-a-la-huancaina', 'Papa a la Huancaína', 'entrada', '["Papa blanca", "Ají amarillo", "Queso fresco", "Leche", "Aceite", "Galletas de soda"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Papa_a_la_Huancaina.jpg/800px-Papa_a_la_Huancaina.jpg', 'Junín'),
    ('papa-rellena', 'Papa Rellena', 'entrada', '["Papa blanca sancochada", "Carne molida", "Cebolla", "Huevo duro", "Pasas", "Aceituna", "Harina"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Papa_rellena.jpg/800px-Papa_rellena.jpg', 'Lima'),
    ('papas-con-uchullachua', 'Papas con Uchullachua', 'entrada', '["Papas nativas", "Ají", "Huacatay", "Queso"]', 'https://i.ytimg.com/vi/Example_Uchullachua.jpg', 'Apurímac'),
    ('parihuela-chalaca', 'Parihuela Chalaca', 'sopa', '["Pescado entero (tramboyo o cabrilla)", "Cangrejos", "Mariscos variados", "Chicha de jora", "Ají panca"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Parihuela.jpg/800px-Parihuela.jpg', 'Callao'),
    ('parihuela-tumbesina', 'Parihuela Tumbesina', 'sopa', '["Pescado", "Conchas negras", "Cangrejo", "Langostinos", "Chicha"]', 'https://i.ytimg.com/vi/Example_ParihuelaTumbes.jpg', 'Tumbes'),
    ('parrillada-de-carne-ahumada', 'Parrillada de Carne Ahumada', 'fondo', '["Carne de res ahumada", "Chorizo", "Yuca", "Plátano asado", "Ensalada"]', 'https://i.ytimg.com/vi/Example_CarneAhumada.jpg', 'Pasco'),
    ('parrillada-de-pancita', 'Parrillada de Pancita', 'entrada', '["Panza de res (librillo)", "Ají panca", "Vinagre", "Ajos", "Papas"]', 'https://i.ytimg.com/vi/Example_Pancita.jpg', 'Moquegua'),
    ('pastel-de-choclo-tacneno', 'Pastel de Choclo Tacneño', 'fondo', '["Choclo molido", "Maní", "Pasas", "Carne molida (opcional)", "Azúcar"]', 'https://i.ytimg.com/vi/Example_PastelChocloTacna.jpg', 'Tacna'),
    ('pastel-de-papa', 'Pastel de Papa', 'guarnicion', '["Papa blanca en láminas", "Queso paria", "Leche evaporada", "Huevos", "Anís"]', 'https://i.ytimg.com/vi/Example_PastelPapa.jpg', 'Arequipa'),
    ('pastel-de-tallarin', 'Pastel de Tallarín', 'fondo', '["Tallarines", "Leche", "Huevos", "Queso paria", "Mantequilla"]', 'https://i.ytimg.com/vi/Example_PastelTallarin.jpg', 'Arequipa'),
    ('patachi', 'Patachi', 'sopa', '["Trigo pelado", "Carne de cerdo", "Tocino", "Habas", "Arvejas"]', 'https://i.ytimg.com/vi/Example_PatachiHuanuco.jpg', 'Huánuco'),
    ('patarashca', 'Patarashca', 'fondo', '["Pescado entero (Boquichico/Palometa)", "Hojas de bijao", "Sacha culantro", "Ají dulce", "Cebolla"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Patarashca.jpg/800px-Patarashca.jpg', 'Ucayali'),
    ('patarashca-de-suri', 'Patarashca de Suri', 'entrada', '["Suris", "Hojas de bijao", "Sacha culantro"]', 'https://i.ytimg.com/vi/Example_PatarashcaSuri.jpg', 'Loreto'),
    ('patasca-cerrena', 'Patasca Cerreña', 'sopa', '["Mote pelado", "Mondongo", "Carne de carnero", "Hierbabuena"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Patasca.jpg/800px-Patasca.jpg', 'Pasco'),
    ('patasca-mondongo', 'Patasca (Mondongo)', 'sopa', '["Mote pelado", "Mondongo (panza)", "Carne de res", "Hierbabuena", "Pecho de carnero"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Patasca.jpg/800px-Patasca.jpg', 'Junín'),
    ('patasca-moqueguana', 'Patasca Moqueguana', 'sopa', '["Mote", "Mondongo", "Carne de cerdo", "Carne de res", "Hierbabuena", "Ají"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Patasca.jpg/800px-Patasca.jpg', 'Moquegua'),
    ('patasca-tacnena', 'Patasca Tacneña', 'sopa', '["Mote", "Cabeza de chancho", "Mondongo", "Carne de res", "Hierbabuena"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Patasca.jpg/800px-Patasca.jpg', 'Tacna'),
    ('pato-guisado', 'Pato Guisado', 'fondo', '["Pato", "Ají panca", "Ají mirasol", "Chicha de jora"]', 'https://i.ytimg.com/vi/Example_PatoGuisado.jpg', 'La Libertad'),
    ('pavo-con-tallarines', 'Pavo con Tallarines', 'fondo', '["Pavo", "Tallarines", "Sillao", "Achiote", "Menudencia"]', 'https://i.ytimg.com/vi/Example_PavoTallarines.jpg', 'Piura'),
    ('pebre-arequipeno', 'Pebre Arequipeño', 'sopa', '["Lomos de cordero", "Chuño blanco remojado", "Arroz", "Cecina"]', 'https://i.ytimg.com/vi/Example_Pebre.jpg', 'Arequipa'),
    ('pecan-caldo', 'Pecan Caldo', 'sopa', '["Cabeza de carnero", "Mondongo", "Mote", "Hierbabuena", "Paico"]', 'https://i.ytimg.com/vi/Example_PecanCaldo.jpg', 'Áncash'),
    ('pepian-de-cuy', 'Pepián de Cuy', 'fondo', '["Cuy frito", "Maíz molido (choclo maduro)", "Ají panca", "Maní"]', 'https://i.ytimg.com/vi/Example_PepianCuy.jpg', 'Apurímac'),
    ('pepian-de-pava', 'Pepián de Pava', 'fondo', '["Pava", "Arroz molido (o maíz)", "Culantro", "Ají amarillo"]', 'https://i.ytimg.com/vi/Example_PepianPava.jpg', 'Lambayeque'),
    ('pepian-de-pavo', 'Pepián de Pavo', 'fondo', '["Pavo", "Choclo maduro molido", "Culantro", "Ají panca"]', 'https://i.ytimg.com/vi/Example_PepianPavoPiura.jpg', 'Piura'),
    ('pescado-a-la-trujillana', 'Pescado a la Trujillana', 'fondo', '["Filete de pescado", "Salsa de huevos", "Cebolla", "Ají amarillo"]', 'https://i.ytimg.com/vi/Example_PescadoTrujillana.jpg', 'La Libertad'),
    ('pescado-a-lo-macho', 'Pescado a lo Macho', 'fondo', '["Filete de pescado frito", "Salsa de mariscos", "Crema de leche", "Ají"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Pescado_a_lo_macho.jpg/800px-Pescado_a_lo_macho.jpg', 'Callao'),
    ('pescado-en-salsa-de-castana', 'Pescado en Salsa de Castaña', 'fondo', '["Pescado (Doncella o Paco)", "Castañas amazónicas", "Leche", "Cebolla", "Ajos"]', 'https://i.ytimg.com/vi/Example_PescadoCastana.jpg', 'Madre de Dios'),
    ('pesque-de-quinua', 'Pesque de Quinua', 'fondo', '["Quinua blanca lavada", "Leche fresca", "Queso", "Mantequilla", "Anís"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Pesque_de_quinua.jpg/800px-Pesque_de_quinua.jpg', 'Puno'),
    ('picadillo-de-paiche', 'Picadillo de Paiche', 'fondo', '["Paiche seco-salado", "Cebolla", "Tomate", "Ají dulce", "Pimienta"]', 'https://i.ytimg.com/vi/Example_PicadilloPaiche.jpg', 'Ucayali'),
    ('picante-a-la-tacnena', 'Picante a la Tacneña', 'fondo', '["Mondongo (panza)", "Pata de res", "Charqui", "Ají panca", "Papas", "Orégano"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Picante_a_la_tacne%C3%B1a.jpg/800px-Picante_a_la_tacne%C3%B1a.jpg', 'Tacna'),
    ('picante-de-camarones', 'Picante de Camarones', 'fondo', '["Camarones de río (Sama)", "Ají panca", "Papa", "Cochayuyo"]', 'https://i.ytimg.com/vi/Example_PicanteCamarones.jpg', 'Tacna'),
    ('picante-de-cochayuyo', 'Picante de Cochayuyo', 'guarnicion', '["Cochayuyo (algas de río/lago)", "Papas", "Ají amarillo", "Cebolla"]', 'https://i.ytimg.com/vi/Example_Cochayuyo.jpg', 'Áncash'),
    ('picante-de-cuy', 'Picante de Cuy', 'fondo', '["Cuy", "Ají panca", "Maní", "Papas", "Arroz"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Picante_de_cuy.jpg/800px-Picante_de_cuy.jpg', 'Pasco'),
    ('picante-de-cuy-cuy-colorado', 'Picante de Cuy (Cuy Colorado)', 'fondo', '["Cuy", "Ají panca (colorado)", "Maní molido", "Ajos", "Papas"]', 'https://i.ytimg.com/vi/Example_CuyColoradoJunin.jpg', 'Junín'),
    ('picante-de-cuy-guisado', 'Picante de Cuy (Guisado)', 'fondo', '["Cuy trozado", "Ají panca", "Papas", "Maní"]', 'https://i.ytimg.com/vi/Example_PicanteCuy.jpg', 'Cajamarca'),
    ('picante-de-llullucha', 'Picante de Llullucha', 'fondo', '["Llullucha (algas de lagunas altoandinas)", "Papas", "Ají amarillo", "Cebolla"]', 'https://i.ytimg.com/vi/Example_Llullucha.jpg', 'Huancavelica'),
    ('picante-de-mariscos', 'Picante de Mariscos', 'fondo', '["Mariscos variados", "Ají panca", "Ají amarillo", "Vino blanco"]', 'https://i.ytimg.com/vi/Example_PicanteMariscos.jpg', 'Ica'),
    ('picante-de-pallares-verdes', 'Picante de Pallares Verdes', 'fondo', '["Pallares verdes (tiernos)", "Ají amarillo", "Leche", "Queso", "Arroz"]', 'https://i.ytimg.com/vi/Example_PicantePallares.jpg', 'Ica'),
    ('picante-de-queso-mishkina', 'Picante de Queso (Mishkina)', 'fondo', '["Queso mantecoso", "Ají mirasol", "Papas", "Leche", "Huevo"]', 'https://i.ytimg.com/vi/Example_PicanteQueso.jpg', 'Huánuco'),
    ('picante-de-tarwi', 'Picante de Tarwi', 'fondo', '["Tarwi (chocho) molido", "Papas", "Ají amarillo", "Queso"]', 'https://i.ytimg.com/vi/Example_PicanteTarwi.jpg', 'Apurímac'),
    ('picarones', 'Picarones', 'postre', '["Zapallo macre", "Camote", "Harina", "Levadura", "Miel de chancaca"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Picarones_Lima.jpg/800px-Picarones_Lima.jpg', 'Lima'),
    ('pisco-sour', 'Pisco Sour', 'bebida', '["Pisco Quebranta", "Limón", "Jarabe de goma", "Clara de huevo", "Amargo de Angostura"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Pisco_Sour_2010.jpg/800px-Pisco_Sour_2010.jpg', 'Ica'),
    ('platano-relleno', 'Plátano Relleno', 'entrada', '["Plátano palillo (maduro)", "Carne molida", "Cebolla", "Huevo"]', 'https://i.ytimg.com/vi/Example_PlatanoRelleno.jpg', 'Amazonas'),
    ('pollo-a-la-brasa', 'Pollo a la Brasa', 'fondo', '["Pollo entero", "Sillao", "Cerveza negra", "Romero", "Ajos", "Ají panca"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Pollo_a_la_brasa_peruano.jpg/800px-Pollo_a_la_brasa_peruano.jpg', 'Lima'),
    ('ponche-de-habas', 'Ponche de Habas', 'bebida', '["Harina de habas tostadas", "Leche", "Huevo", "Pisco (opcional)"]', 'https://i.ytimg.com/vi/Example_PoncheHabas.jpg', 'Puno'),
    ('ponche-de-maca', 'Ponche de Maca', 'bebida', '["Maca fresca (Meseta de Bombón)", "Leche", "Huevo", "Azúcar", "Vainilla"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Maca_roots.jpg/800px-Maca_roots.jpg', 'Pasco'),
    ('ponche-de-mani', 'Ponche de Maní', 'bebida', '["Maní tostado", "Ajonjolí", "Leche", "Clavo de olor", "Canela"]', 'https://i.ytimg.com/vi/Example_PoncheMani.jpg', 'Ayacucho'),
    ('poroto-con-pato', 'Poroto con Pato', 'fondo', '["Pato", "Frijol (poroto)", "Culantro", "Zapallo"]', 'https://i.ytimg.com/vi/Example_PorotoPato.jpg', 'Cajamarca'),
    ('poroto-shirumbi', 'Poroto Shirumbi', 'sopa', '["Frijol huasca (poroto)", "Patas de cerdo", "Yuca", "Arroz", "Sacha culantro"]', 'https://i.ytimg.com/vi/Example_PorotoShirumbi.jpg', 'San Martín'),
    ('prestinos', 'Prestiños', 'postre', '["Harina de trigo", "Yemas de huevo", "Manteca", "Chancaca"]', 'https://i.ytimg.com/vi/Example_Prestinos.jpg', 'Huánuco'),
    ('puca-picante', 'Puca Picante', 'fondo', '["Papas", "Maní tostado", "Beterraga (remolacha)", "Chicharrón de cerdo", "Ají panca"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Puca_picante.jpg/800px-Puca_picante.jpg', 'Ayacucho'),
    ('puchero-ancashino', 'Puchero Ancashino', 'fondo', '["Carne de res", "Carne de cerdo", "Col", "Papa", "Camote", "Yuca", "Jamón"]', 'https://i.ytimg.com/vi/Example_Puchero.jpg', 'Áncash'),
    ('puchero-ayacuchano', 'Puchero Ayacuchano', 'fondo', '["Carne de res", "Tocino", "Col", "Garbanzos", "Camote", "Yuca", "Durazno"]', 'https://i.ytimg.com/vi/Example_PucheroAyacucho.jpg', 'Ayacucho'),
    ('pulpo-al-olivo', 'Pulpo al Olivo', 'entrada', '["Pulpo cocido", "Aceituna de botija", "Mayonesa", "Limón", "Aceite de oliva"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Pulpo_al_olivo.jpg/800px-Pulpo_al_olivo.jpg', 'Callao'),
    ('purtumute', 'Purtumute', 'guarnicion', '["Frijoles", "Mote (maíz)", "Culantro", "Ajos"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Purtumute.jpg/800px-Purtumute.jpg', 'Amazonas'),
    ('puspu-habas-tostadas', 'Puspu (Habas Tostadas)', 'entrada', '["Habas secas", "Sal", "Agua"]', 'https://i.ytimg.com/vi/Example_Puspu.jpg', 'Huancavelica'),
    ('qapchi', 'Qapchi', 'entrada', '["Queso fresco (cachipa)", "Rocoto", "Cebolla china", "Huacatay", "Papas"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Qapchi.jpg/800px-Qapchi.jpg', 'Ayacucho'),
    ('qapchi-de-chuno', 'Qapchi de Chuño', 'entrada', '["Chuño", "Queso", "Rocoto", "Huacatay", "Leche"]', 'https://i.ytimg.com/vi/Example_QapchiChuno.jpg', 'Huancavelica'),
    ('qapchi-de-queso', 'Qapchi de Queso', 'entrada', '["Queso fresco", "Rocoto", "Huacatay", "Leche", "Papa sancochada"]', 'https://i.ytimg.com/vi/Example_Qapchi.jpg', 'Apurímac'),
    ('quesillo-con-miel', 'Quesillo con Miel', 'postre', '["Quesillo (cuajada fresca)", "Miel de caña (chancaca)"]', 'https://i.ytimg.com/vi/Example_QuesilloMiel.jpg', 'Cajamarca'),
    ('queso-cauche', 'Queso Cauche', 'fondo', '["Queso fresco", "Cebolla", "Papa", "Huacatay", "Leche"]', 'https://i.ytimg.com/vi/Example_QuesoCauche.jpg', 'Puno'),
    ('queso-helado', 'Queso Helado', 'postre', '["Leche fresca", "Leche condensada", "Coco rallado", "Canela", "Clavo"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Queso_helado.jpg/800px-Queso_helado.jpg', 'Arequipa'),
    ('quispino', 'Quispiño', 'otro', '["Harina de quinua", "Cal (lejía natural)", "Agua", "Manteca"]', 'https://i.ytimg.com/vi/Example_Quispino.jpg', 'Puno'),
    ('refresco-de-camu-camu', 'Refresco de Camu Camu', 'bebida', '["Camu Camu (fruta)", "Agua", "Azúcar"]', 'https://i.ytimg.com/vi/Example_CamuCamu.jpg', 'Ucayali'),
    ('refresco-de-copoazu', 'Refresco de Copoazú', 'bebida', '["Pulpa de Copoazú", "Agua", "Azúcar"]', 'https://i.ytimg.com/vi/Example_Copoazu.jpg', 'Madre de Dios'),
    ('relleno-de-tripas-kachi', 'Relleno de Tripas (Kachi)', 'entrada', '["Tripas de cerdo o carnero", "Sangre", "Papa picada", "Hierbabuena", "Ají"]', 'https://i.ytimg.com/vi/Example_RellenoTripa.jpg', 'Apurímac'),
    ('relleno-piurano', 'Relleno Piurano', 'otro', '["Tripas de cerdo", "Sangre", "Camote", "Hierbabuena", "Aji"]', 'https://i.ytimg.com/vi/Example_RellenoPiurano.jpg', 'Piura'),
    ('revuelto-de-habas', 'Revuelto de Habas', 'fondo', '["Habas peladas", "Cebolla", "Ají amarillo", "Huevos", "Huacatay"]', 'https://i.ytimg.com/vi/Example_RevueltoHabas.jpg', 'Arequipa'),
    ('rocoto-relleno', 'Rocoto Relleno', 'fondo', '["Rocoto", "Carne de res picada", "Queso paria", "Leche", "Maní", "Pasas"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Rocoto_relleno_2.JPG/800px-Rocoto_relleno_2.JPG', 'Arequipa'),
    ('rocoto-relleno-cusqueno', 'Rocoto Relleno Cusqueño', 'fondo', '["Rocoto", "Carne molida", "Maní", "Pasas", "Huevo", "Harina"]', 'https://i.ytimg.com/vi/Example_RocotoCusco.jpg', 'Cusco'),
    ('rosquitas-de-almidon', 'Rosquitas de Almidón', 'entrada', '["Almidón de yuca", "Huevo", "Manteca"]', 'https://i.ytimg.com/vi/Example_RosquitasYuca.jpg', 'San Martín'),
    ('rosquitas-de-manteca', 'Rosquitas de Manteca', 'entrada', '["Harina", "Manteca de cerdo", "Sal", "Agua"]', 'https://i.ytimg.com/vi/Example_Rosquitas.jpg', 'Cajamarca'),
    ('rumo-juane', 'Rumo Juane', 'fondo', '["Yuca rallada", "Paiche (pescado)", "Huevo", "Bijao"]', 'https://i.ytimg.com/vi/Example_RumoJuane.jpg', 'San Martín'),
    ('sajta-de-pollo', 'Sajta de Pollo', 'fondo', '["Pollo", "Tunta (chuño blanco)", "Ají amarillo", "Cebolla", "Arvejas"]', 'https://i.ytimg.com/vi/Example_Sajta.jpg', 'Puno'),
    ('salchicha-pozucina', 'Salchicha Pozucina', 'otro', '["Carne de cerdo", "Especias secretas", "Tripa"]', 'https://i.ytimg.com/vi/Example_SalchichaPozuzo.jpg', 'Pasco'),
    ('salsa-de-cocona', 'Salsa de Cocona', 'guarnicion', '["Cocona", "Ají charapita", "Cebolla", "Sal", "Limón"]', 'https://i.ytimg.com/vi/Example_Cocona.jpg', 'Ucayali'),
    ('sancochado', 'Sancochado', 'sopa', '["Carne de res (pecho)", "Papas", "Camote", "Yuca", "Choclo", "Col", "Zanahoria"]', 'https://i.ytimg.com/vi/Example_Sancochado.jpg', 'Lima'),
    ('sancochado-puneno', 'Sancochado Puneño', 'fondo', '["Carne de res", "Cordero", "Papas", "Chuño", "Repollo"]', 'https://i.ytimg.com/vi/Example_SancochadoPuno.jpg', 'Puno'),
    ('sandwich-de-pavo', 'Sándwich de Pavo', 'entrada', '["Pavo horneado", "Pan francés", "Jugo del asado", "Cebolla"]', 'https://i.ytimg.com/vi/Example_SandwichPavo.jpg', 'La Libertad'),
    ('sangrecita-criolla', 'Sangrecita Criolla', 'fondo', '["Sangre de pollo", "Cebolla china", "Ají amarillo", "Yuca"]', 'https://i.ytimg.com/vi/Example_Sangrecita.jpg', 'La Libertad'),
    ('sarza-de-patitas', 'Sarza de Patitas', 'entrada', '["Patitas de cerdo", "Cebolla", "Tomate", "Perejil", "Vinagre"]', 'https://i.ytimg.com/vi/Example_SarzaPatitas.jpg', 'Apurímac'),
    ('sarza-de-sencca', 'Sarza de Sencca', 'entrada', '["Sencca (hocico de res)", "Cebolla", "Tomate", "Perejil", "Vinagre"]', 'https://i.ytimg.com/vi/Example_Sencca.jpg', 'Arequipa'),
    ('seco-de-cabrito-a-la-nortena', 'Seco de Cabrito a la Norteña', 'fondo', '["Cabrito de leche", "Zapallo loche", "Culantro", "Chicha de jora", "Frijoles"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Seco_de_cabrito.jpg/800px-Seco_de_cabrito.jpg', 'Piura'),
    ('seco-de-cabrito-con-frijoles', 'Seco de Cabrito con Frijoles', 'fondo', '["Cabrito de leche", "Zapallo loche", "Chicha de jora", "Culantro", "Frijol canario"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Seco_de_cabrito.jpg/800px-Seco_de_cabrito.jpg', 'Lambayeque'),
    ('seco-de-chavelo', 'Seco de Chavelo', 'fondo', '["Plátano verde (bellaco)", "Carne aliñada (cecina)", "Chicha de jora", "Cebolla", "Tomate", "Ají panca"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Seco_de_Chavelo.jpg/800px-Seco_de_Chavelo.jpg', 'Piura'),
    ('shakvi-shacwi', 'Shakvi (Shacwi)', 'fondo', '["Harina de arveja", "Harina de habas", "Carne (opcional)", "Papas"]', 'https://i.ytimg.com/vi/Example_Shacwi.jpg', 'Áncash'),
    ('shambar', 'Shambar', 'sopa', '["Trigo shambar (resbalado)", "Pellejo de cerdo", "Costilla ahumada", "Habas", "Frijoles", "Hierbabuena"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Shambar.jpg/800px-Shambar.jpg', 'La Libertad'),
    ('shipasmute', 'Shipasmute', 'sopa', '["Choclo tierno", "Frijol verde", "Culantro", "Maní"]', 'https://i.ytimg.com/vi/Example_Shipasmute.jpg', 'Amazonas'),
    ('sivinche-de-camarones', 'Sivinche de Camarones', 'entrada', '["Colitas de camarón", "Vinagre", "Ají panca", "Cebolla", "Ajos"]', 'https://i.ytimg.com/vi/Example_Sivinche.jpg', 'Arequipa'),
    ('solterito-de-cucho', 'Solterito de Cucho', 'guarnicion', '["Cochayuyo (algas)", "Zanahoria", "Cebolla", "Tomate", "Limón"]', 'https://i.ytimg.com/vi/Example_SolteritoCucho.jpg', 'Cusco'),
    ('solterito-de-queso', 'Solterito de Queso', 'guarnicion', '["Habas verdes", "Choclo", "Queso fresco", "Cebolla", "Tomate", "Aceitunas", "Rocoto"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Solterito_arequipe%C3%B1o.jpg/800px-Solterito_arequipe%C3%B1o.jpg', 'Arequipa'),
    ('sopa-de-chochoca', 'Sopa de Chochoca', 'sopa', '["Harina de maíz fermentado (chochoca)", "Carne de res", "Papa", "Apio"]', 'https://i.ytimg.com/vi/Example_ChochocaCajamarca.jpg', 'Cajamarca'),
    ('sopa-de-moron', 'Sopa de Morón', 'sopa', '["Cebada partida (morón)", "Carne de cordero", "Papas", "Apio"]', 'https://i.ytimg.com/vi/Example_SopaMoron.jpg', 'Huancavelica'),
    ('sopa-de-pan', 'Sopa de Pan', 'sopa', '["Pan frío (tipo piso)", "Caldo de carne", "Huevo", "Queso"]', 'https://i.ytimg.com/vi/Example_SopaPan.jpg', 'Cajamarca'),
    ('sopa-de-pelotas-knodelsuppe', 'Sopa de Pelotas (Knödelsuppe)', 'sopa', '["Arroz", "Carne molida", "Huevo", "Caldo de gallina"]', 'https://i.ytimg.com/vi/Example_SopaPelotas.jpg', 'Pasco'),
    ('sopa-seca', 'Sopa Seca', 'guarnicion', '["Tallarines", "Albahaca", "Achiote", "Perejil", "Pollo o gallina"]', 'https://i.ytimg.com/vi/Example_SopaSeca.jpg', 'Ica'),
    ('sopa-teologa', 'Sopa Teóloga', 'fondo', '["Pava", "Gallina", "Pan", "Leche", "Azafrán/Cúrcuma", "Garbanzos"]', 'https://i.ytimg.com/vi/Example_SopaTeologa.jpg', 'La Libertad'),
    ('strudel-de-platano', 'Strudel de Plátano', 'postre', '["Harina", "Plátano de seda", "Azúcar", "Canela", "Mantequilla"]', 'https://i.ytimg.com/vi/Example_StrudelPlatano.jpg', 'Pasco'),
    ('sudado-de-cachema', 'Sudado de Cachema', 'fondo', '["Pescado Cachema entero", "Chicha de jora", "Tomate", "Cebolla", "Ají amarillo"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Sudado_de_pescado.jpg/800px-Sudado_de_pescado.jpg', 'Piura'),
    ('sudado-de-doncella', 'Sudado de Doncella', 'fondo', '["Pescado Doncella", "Tomate", "Cebolla", "Ají dulce", "Sacha culantro"]', 'https://i.ytimg.com/vi/Example_SudadoDoncella.jpg', 'Madre de Dios'),
    ('sudado-de-machas', 'Sudado de Machas', 'fondo', '["Machas (marisco)", "Cebolla", "Tomate", "Vino blanco", "Vinagre"]', 'https://i.ytimg.com/vi/Example_SudadoMachas.jpg', 'Moquegua'),
    ('sudado-de-mero', 'Sudado de Mero', 'fondo', '["Mero murique (pescado fino)", "Chicha de jora", "Tomate", "Cebolla", "Ají"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Sudado_de_pescado.jpg/800px-Sudado_de_pescado.jpg', 'Tumbes'),
    ('sudado-de-pescado', 'Sudado de Pescado', 'fondo', '["Pescado entero", "Tomate", "Cebolla", "Chicha de jora", "Ají amarillo"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Sudado_de_pescado.jpg/800px-Sudado_de_pescado.jpg', 'Callao'),
    ('sudado-de-pescado-a-la-nortena', 'Sudado de Pescado a la Norteña', 'fondo', '["Pescado (Mero/Ojo de Uva)", "Chicha de jora", "Tomate", "Ají amarillo"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Sudado_de_pescado.jpg/800px-Sudado_de_pescado.jpg', 'Lambayeque'),
    ('suri-a-la-parrilla', 'Suri a la Parrilla', 'entrada', '["Suri (gusano de palma)", "Sal", "Ajos"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Suri_food.jpg/800px-Suri_food.jpg', 'Ucayali'),
    ('suspiro-a-la-limena', 'Suspiro a la Limeña', 'postre', '["Leche condensada", "Leche evaporada", "Yemas", "Oporto", "Claras de huevo"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Suspiro_de_Lime%C3%B1a.jpg/800px-Suspiro_de_Lime%C3%B1a.jpg', 'Lima'),
    ('tacacho-con-cecina', 'Tacacho con Cecina', 'fondo', '["Plátano verde (bellaco)", "Manteca de cerdo", "Chicharrón picado", "Cecina (cerdo ahumado)"]', 'https://upload.wikimedia.org/wikipedia/commons/f/f5/Tacacho_con_Cecina.jpg', 'Ucayali'),
    ('tacu-tacu', 'Tacu Tacu', 'fondo', '["Frijoles canarios (sobras)", "Arroz cocido", "Cebolla", "Ají amarillo", "Aceite de oliva"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Tacu-tacu.jpg/800px-Tacu-tacu.jpg', 'Lima'),
    ('tacu-tacu-con-mariscos', 'Tacu Tacu con Mariscos', 'fondo', '["Frijoles canario", "Arroz", "Mariscos", "Salsa madre (roja)"]', 'https://i.ytimg.com/vi/Example_TacuTacuMariscos.jpg', 'Callao'),
    ('tajadon', 'Tajadón', 'postre', '["Yemas de huevo", "Azúcar", "Pisco", "Pasas"]', 'https://i.ytimg.com/vi/Example_Tajadon.jpg', 'La Libertad'),
    ('tallarin-hecho-en-casa', 'Tallarín Hecho en Casa', 'fondo', '["Harina", "Huevos", "Gallina (estofado)", "Achiote"]', 'https://i.ytimg.com/vi/Example_TallarinCasa.jpg', 'Apurímac'),
    ('tallarines-verdes', 'Tallarines Verdes', 'fondo', '["Fideos espagueti", "Albahaca", "Espinaca", "Queso fresco", "Leche", "Pecanas"]', 'https://i.ytimg.com/vi/Example_TallarinesVerdes.jpg', 'Lima'),
    ('tamal-cajamarquino', 'Tamal Cajamarquino', 'entrada', '["Harina de maíz", "Manteca", "Cerdo", "Ají panca", "Hojas de plátano"]', 'https://i.ytimg.com/vi/Example_TamalCajamarca.jpg', 'Cajamarca'),
    ('tamales-a-la-amazonense', 'Tamales a la Amazonense', 'entrada', '["Maíz", "Carne de cerdo o pollo", "Ají panca", "Hojas de achira"]', 'https://i.ytimg.com/vi/Example_Tamal.jpg', 'Amazonas'),
    ('tamales-ancashinos', 'Tamales Ancashinos', 'entrada', '["Maíz pelado", "Manteca", "Relleno de carne", "Hojas de panca"]', 'https://i.ytimg.com/vi/Example_Tamales.jpg', 'Áncash'),
    ('tamales-chinchanos', 'Tamales Chinchanos', 'fondo', '["Maíz blanco", "Ají panca", "Cerdo", "Huevo", "Aceituna"]', 'https://i.ytimg.com/vi/Example_TamalChincha.jpg', 'Ica'),
    ('tamales-cusquenos', 'Tamales Cusqueños', 'entrada', '["Maíz blanco gigante", "Manteca", "Anís", "Pasas (dulces) o Carne (salados)"]', 'https://i.ytimg.com/vi/Example_TamalCusco.jpg', 'Cusco'),
    ('tamalitos-verdes', 'Tamalitos Verdes', 'entrada', '["Choclo tierno", "Culantro", "Cebolla", "Aceite"]', 'https://i.ytimg.com/vi/Example_TamalitosVerdes.jpg', 'Piura'),
    ('tarwi-guiso', 'Tarwi (Guiso)', 'fondo', '["Tarwi (chocho) pelado", "Papas", "Queso", "Leche"]', 'https://i.ytimg.com/vi/Example_Tarwi.jpg', 'Cusco'),
    ('tejas-iquenas', 'Tejas Iqueñas', 'postre', '["Manjar blanco", "Pecanas (o frutas confitadas)", "Baño de fondant (azúcar)"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Tejas_dulce.jpg/800px-Tejas_dulce.jpg', 'Ica'),
    ('teqte', 'Teqte', 'fondo', '["Arvejas", "Queso", "Leche", "Huevos", "Papas", "Hierbas"]', 'https://i.ytimg.com/vi/Example_Teqte.jpg', 'Ayacucho'),
    ('teqte-tecre', 'Teqte (Tecre)', 'fondo', '["Papas", "Queso", "Leche", "Arvejas", "Habas", "Paico"]', 'https://i.ytimg.com/vi/Example_Teqte.jpg', 'Huancavelica'),
    ('thimpo-de-carachi', 'Thimpo de Carachi', 'sopa', '["Carachi (pez del Titicaca)", "Muña", "Chuño", "Papa", "Cebolla"]', 'https://i.ytimg.com/vi/Example_Thimpo.jpg', 'Puno'),
    ('tilapia-frita', 'Tilapia Frita', 'fondo', '["Tilapia (piscigranja)", "Harina", "Patacones", "Ensalada"]', 'https://i.ytimg.com/vi/Example_Tilapia.jpg', 'San Martín'),
    ('timbuche', 'Timbuche', 'sopa', '["Pescado boquichico", "Sacha culantro", "Agua", "Sal"]', 'https://i.ytimg.com/vi/Example_Timbuche.jpg', 'San Martín'),
    ('timbuche-caldo-de-carachama', 'Timbuche (Caldo de Carachama)', 'sopa', '["Carachama (pez)", "Sacha culantro", "Ajos", "Agua", "Plátano verde (opcional)"]', 'https://i.ytimg.com/vi/Example_Carachama.jpg', 'Loreto'),
    ('timbuche-caldo-de-levantamuertos', 'Timbuche (Caldo de Levantamuertos)', 'sopa', '["Pescado fresco (menudo)", "Sacha culantro", "Huevos", "Agua"]', 'https://i.ytimg.com/vi/Example_Timbuche.jpg', 'Ucayali'),
    ('timpu-puchero-cusqueno', 'Timpu (Puchero Cusqueño)', 'fondo', '["Pecho de res", "Cabeza de cordero", "Tocino", "Col", "Garbanzos", "Camote", "Yuca", "Durazno", "Pera"]', 'https://i.ytimg.com/vi/Example_Timpu.jpg', 'Cusco'),
    ('timpusca-de-peras', 'Timpusca de Peras', 'sopa', '["Peras pequeñas (de agua)", "Carne de res", "Chuño", "Trigo", "Cochayuyo"]', 'https://i.ytimg.com/vi/Example_Timpusca.jpg', 'Arequipa'),
    ('tiqi-tique', 'Tiqi (Tique)', 'fondo', '["Carne de alpaca", "Quesillo", "Leche", "Papas", "Ají"]', 'https://i.ytimg.com/vi/Example_Tiqi.jpg', 'Huancavelica'),
    ('tiradito-chalaco', 'Tiradito Chalaco', 'entrada', '["Pescado en láminas", "Crema de ají amarillo", "Limón", "Choclo"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Tiradito.jpg/800px-Tiradito.jpg', 'Callao'),
    ('torrejas-de-quinua', 'Torrejas de Quinua', 'entrada', '["Quinua cocida", "Huevo", "Harina", "Cebolla", "Queso"]', 'https://i.ytimg.com/vi/Example_Torrejas.jpg', 'Puno'),
    ('tortilla-de-camarones', 'Tortilla de Camarones', 'fondo', '["Camarones de río (Chinchipe/Pisco)", "Huevo", "Harina", "Cebolla"]', 'https://i.ytimg.com/vi/Example_TortillaCamaron.jpg', 'Ica'),
    ('tortilla-de-langostinos', 'Tortilla de Langostinos', 'fondo', '["Langostinos frescos", "Huevos", "Cebolla china", "Harina (opcional)"]', 'https://i.ytimg.com/vi/Example_TortillaLangostinos.jpg', 'Tumbes'),
    ('tortilla-de-raya', 'Tortilla de Raya', 'fondo', '["Raya seca salada", "Huevos", "Cebolla china", "Ají panca", "Ajos"]', 'https://i.ytimg.com/vi/Example_TortillaRaya.jpg', 'Lambayeque'),
    ('tortilla-de-rayas', 'Tortilla de Rayas', 'fondo', '["Raya seca o fresca", "Huevos", "Cebolla china", "Ajos"]', 'https://i.ytimg.com/vi/Example_TortillaRaya.jpg', 'Callao'),
    ('trucha-a-la-parrilla', 'Trucha a la Parrilla', 'fondo', '["Trucha entera deshuesada", "Mantequilla", "Ajos", "Orégano"]', 'https://i.ytimg.com/vi/Example_TruchaParrilla.jpg', 'Junín'),
    ('trucha-frita', 'Trucha Frita', 'fondo', '["Trucha del Titicaca", "Harina", "Papas doradas", "Ensalada criolla"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Trucha_frita.jpg/800px-Trucha_frita.jpg', 'Puno'),
    ('trucha-frita-con-papas', 'Trucha Frita con Papas', 'fondo', '["Trucha de río", "Harina", "Papas", "Ensalada"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Trucha_frita.jpg/800px-Trucha_frita.jpg', 'Apurímac'),
    ('turron-de-cajamarca', 'Turrón de Cajamarca', 'postre', '["Miel de caña", "Clara de huevo", "Nueces o maní"]', 'https://i.ytimg.com/vi/Example_TurronCajamarca.jpg', 'Cajamarca'),
    ('turron-de-dona-pepa', 'Turrón de Doña Pepa', 'postre', '["Harina", "Manteca", "Ajonjolí", "Anís", "Miel de frutas", "Grageas"]', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Turron_de_Do%C3%B1a_Pepa.jpg/800px-Turron_de_Do%C3%B1a_Pepa.jpg', 'Lima'),
    ('uman-caldo', 'Uman Caldo', 'sopa', '["Cabeza de carnero", "Moraya", "Arroz", "Paico"]', 'https://i.ytimg.com/vi/Example_UmanCaldo.jpg', 'Apurímac'),
    ('uman-caldo-caldo-de-cabeza', 'Uman Caldo (Caldo de Cabeza)', 'sopa', '["Cabeza de carnero", "Papas", "Chuño", "Hierbabuena"]', 'https://i.ytimg.com/vi/Example_UmanCaldoAya.jpg', 'Ayacucho'),
    ('uvachado', 'Uvachado', 'bebida', '["Uva borgoña (isabella)", "Aguardiente de caña", "Miel"]', 'https://i.ytimg.com/vi/Example_Uvachado.jpg', 'San Martín'),
    ('vino-de-chacra', 'Vino de Chacra', 'bebida', '["Uva negra criolla", "Uva italia"]', 'https://i.ytimg.com/vi/Example_VinoChacra.jpg', 'Tacna'),
    ('voladores', 'Voladores', 'postre', '["Harina", "Yemas", "Pisco", "Manjar", "Mermelada de piña"]', 'https://i.ytimg.com/vi/Example_Voladores.jpg', 'Moquegua'),
    ('wawa-caldo', 'Wawa Caldo', 'sopa', '["Feto de ovino o cordero muy tierno", "Hierbabuena", "Papas"]', 'https://i.ytimg.com/vi/Example_WawaCaldo.jpg', 'Áncash'),
    ('yuyo-picante', 'Yuyo Picante', 'guarnicion', '["Hojas de mostaza silvestre (yuyo)", "Papas", "Ají panca"]', 'https://i.ytimg.com/vi/Example_YuyoPicante.jpg', 'Ayacucho'),
    ('zapallo-relleno', 'Zapallo Relleno', 'fondo', '["Zapallo redondo", "Carne picada", "Queso", "Papas", "Arvejas"]', 'https://i.ytimg.com/vi/Example_ZapalloRelleno.jpg', 'Tacna'),
    ('zarapatera', 'Zarapatera', 'fondo', '["Tortuga (motelo)", "Plátano verde rallado", "Mishquina (guisador)", "Sacha culantro"]', 'https://i.ytimg.com/vi/Example_Zarapatera.jpg', 'Ucayali'),
    ('zarapatera-sopa-de-motelo', 'Zarapatera (Sopa de Motelo)', 'sopa', '["Motelo (tortuga)", "Plátano rallado", "Culantro"]', 'https://i.ytimg.com/vi/Example_Zarapatera.jpg', 'Madre de Dios'),
    ('zarza-de-patitas', 'Zarza de Patitas', 'entrada', '["Patitas de cerdo", "Cebolla", "Perejil", "Tomate", "Vinagre"]', 'https://i.ytimg.com/vi/Example_ZarzaPatitasCusco.jpg', 'Cusco');

-- Que plato tipico es este plato de la carta, y quien lo decidio.
--
-- Se resuelve al leer, cuando la carta entra, y se guarda: emparejar en cada
-- foto seria repetir el mismo trabajo y ademas dejaria que el resultado cambiara
-- solo al ampliar el catalogo.
ALTER TABLE plato
    ADD COLUMN plato_tipico   text NOT NULL DEFAULT '',
    ADD COLUMN tipico_origen  text NOT NULL DEFAULT '';  -- regla|ia|dueno

-- +goose Down
ALTER TABLE plato DROP COLUMN tipico_origen, DROP COLUMN plato_tipico;
DROP TABLE plato_tipico;
