// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: foto.sql

package cartadb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const baseDeFoto = `-- name: BaseDeFoto :many
SELECT categoria, recipiente, fondo, referencias
  FROM base_foto
 WHERE restaurante_id = $1
   AND categoria IN ('', $2::text)
 ORDER BY categoria
`

type BaseDeFotoParams struct {
	RestauranteID uuid.UUID
	Categoria     string
}

type BaseDeFotoRow struct {
	Categoria   string
	Recipiente  string
	Fondo       string
	Referencias []byte
}

// LA BASE DE UNA CATEGORIA, en una sola consulta.
//
// Devuelve como mucho dos filas: la general (categoria=”) y la de esta
// categoria si existe. El plegado campo por campo se hace en Go con
// domain.Receta.Sobre, no aqui: en SQL habria que escribir un COALESCE por
// columna y el dia que la receta gane una ranura habria que acordarse de esto.
//
// El ORDER BY pone la general PRIMERO para que quien recorre sepa cual es cual
// sin comparar cadenas: ” ordena antes que cualquier nombre de categoria.
func (q *Queries) BaseDeFoto(ctx context.Context, arg BaseDeFotoParams) ([]BaseDeFotoRow, error) {
	rows, err := q.db.Query(ctx, baseDeFoto, arg.RestauranteID, arg.Categoria)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BaseDeFotoRow{}
	for rows.Next() {
		var i BaseDeFotoRow
		if err := rows.Scan(
			&i.Categoria,
			&i.Recipiente,
			&i.Fondo,
			&i.Referencias,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bloquearImportacion = `-- name: BloquearImportacion :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 0))
`

// Toma el lock de esta importacion. Se llama ANTES de ReclamarFoto, dentro de la
// misma transaccion, y se suelta solo al terminarla.
//
// hashtextextended da un bigint a partir del uuid; la colision entre dos
// importaciones distintas solo costaria que sus claims se serialicen entre si,
// que es una perdida de paralelismo despreciable y nunca un dato incorrecto.
func (q *Queries) BloquearImportacion(ctx context.Context, importacionID string) error {
	_, err := q.db.Exec(ctx, bloquearImportacion, importacionID)
	return err
}

const guardarAjusteFoto = `-- name: GuardarAjusteFoto :exec
UPDATE plato SET foto_ajuste = $1 WHERE id = $2
`

type GuardarAjusteFotoParams struct {
	Ajuste  string
	PlatoID uuid.UUID
}

// El ajuste del dueno para la foto de UN plato. Lo escribe en el lapiz de la
// tarjeta y se aplica en la siguiente generacion.
//
// Guardar y regenerar son DOS pasos separados a proposito: el dueno puede
// corregir el texto tres veces antes de gastar los $0.0336, y el boton de
// regenerar que ya existe sirve igual sin duplicar la logica de encolado.
func (q *Queries) GuardarAjusteFoto(ctx context.Context, arg GuardarAjusteFotoParams) error {
	_, err := q.db.Exec(ctx, guardarAjusteFoto, arg.Ajuste, arg.PlatoID)
	return err
}

const guardarBaseDeFoto = `-- name: GuardarBaseDeFoto :exec
INSERT INTO base_foto (id, restaurante_id, categoria, recipiente, fondo, referencias)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (restaurante_id, categoria) DO UPDATE
   SET recipiente     = EXCLUDED.recipiente,
       fondo          = EXCLUDED.fondo,
       referencias    = EXCLUDED.referencias,
       actualizado_at = now()
`

type GuardarBaseDeFotoParams struct {
	ID            uuid.UUID
	RestauranteID uuid.UUID
	Categoria     string
	Recipiente    string
	Fondo         string
	Referencias   []byte
}

func (q *Queries) GuardarBaseDeFoto(ctx context.Context, arg GuardarBaseDeFotoParams) error {
	_, err := q.db.Exec(ctx, guardarBaseDeFoto,
		arg.ID,
		arg.RestauranteID,
		arg.Categoria,
		arg.Recipiente,
		arg.Fondo,
		arg.Referencias,
	)
	return err
}

const guardarReferenciasDePlato = `-- name: GuardarReferenciasDePlato :exec
UPDATE plato SET foto_referencias = $1 WHERE id = $2
`

type GuardarReferenciasDePlatoParams struct {
	Referencias []byte
	PlatoID     uuid.UUID
}

func (q *Queries) GuardarReferenciasDePlato(ctx context.Context, arg GuardarReferenciasDePlatoParams) error {
	_, err := q.db.Exec(ctx, guardarReferenciasDePlato, arg.Referencias, arg.PlatoID)
	return err
}

const guardarTiposDeRestaurante = `-- name: GuardarTiposDeRestaurante :exec
UPDATE restaurante SET tipos = $1 WHERE id = $2
`

type GuardarTiposDeRestauranteParams struct {
	Tipos []byte
	ID    uuid.UUID
}

func (q *Queries) GuardarTiposDeRestaurante(ctx context.Context, arg GuardarTiposDeRestauranteParams) error {
	_, err := q.db.Exec(ctx, guardarTiposDeRestaurante, arg.Tipos, arg.ID)
	return err
}

const guardarVistaDeBase = `-- name: GuardarVistaDeBase :exec
INSERT INTO base_foto (id, restaurante_id, categoria, vista_clave)
VALUES ($1, $2, $3, $4)
ON CONFLICT (restaurante_id, categoria) DO UPDATE
   SET vista_clave    = EXCLUDED.vista_clave,
       actualizado_at = now()
`

type GuardarVistaDeBaseParams struct {
	ID            uuid.UUID
	RestauranteID uuid.UUID
	Categoria     string
	VistaClave    string
}

// El INSERT crea la fila si el dueno pidio la vista antes de guardar nada: la
// base queda vacia, que es lo mismo que no tenerla.
func (q *Queries) GuardarVistaDeBase(ctx context.Context, arg GuardarVistaDeBaseParams) error {
	_, err := q.db.Exec(ctx, guardarVistaDeBase,
		arg.ID,
		arg.RestauranteID,
		arg.Categoria,
		arg.VistaClave,
	)
	return err
}

const importacionDePlato = `-- name: ImportacionDePlato :one
SELECT importacion_id FROM plato WHERE id = $1
`

// El token pertenece a la IMPORTACION, pero los endpoints de foto reciben un
// plato. Esto resuelve de quien es antes de comprobar nada.
func (q *Queries) ImportacionDePlato(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, importacionDePlato, id)
	var importacion_id uuid.UUID
	err := row.Scan(&importacion_id)
	return importacion_id, err
}

const marcarFotoConEstado = `-- name: MarcarFotoConEstado :exec
UPDATE plato
   SET foto_estado         = $1,
       foto_actualizada_at = now()
 WHERE id = $2
`

type MarcarFotoConEstadoParams struct {
	Estado  string
	PlatoID uuid.UUID
}

func (q *Queries) MarcarFotoConEstado(ctx context.Context, arg MarcarFotoConEstadoParams) error {
	_, err := q.db.Exec(ctx, marcarFotoConEstado, arg.Estado, arg.PlatoID)
	return err
}

const marcarFotoLista = `-- name: MarcarFotoLista :exec
UPDATE plato
   SET foto_estado         = 'lista',
       foto_origen         = $1,
       foto_clave          = $2,
       foto_actualizada_at = now()
 WHERE id = $3
`

type MarcarFotoListaParams struct {
	Origen  string
	Clave   string
	PlatoID uuid.UUID
}

func (q *Queries) MarcarFotoLista(ctx context.Context, arg MarcarFotoListaParams) error {
	_, err := q.db.Exec(ctx, marcarFotoLista, arg.Origen, arg.Clave, arg.PlatoID)
	return err
}

const marcarFotosPendientes = `-- name: MarcarFotosPendientes :exec
UPDATE plato
   SET foto_estado = 'pendiente', foto_intentos = 0, foto_actualizada_at = now()
 WHERE id = ANY($1::uuid[])
`

// Los intentos vuelven a CERO al encolar.
//
// foto_intentos existe para frenar a un plato que falla en bucle contra la misma
// pared, no para topear cuantas veces el dueno puede pedir su foto a proposito.
// Sin este reset, corregir el texto con el lapiz dos veces dejaba el plato en
// intentos=2 y el claim lo rechazaba en silencio para siempre.
//
// Lo que si topea el gasto sigue en pie y es el que importa: el presupuesto por
// importacion, que se reserva antes de cada llamada pagada.
func (q *Queries) MarcarFotosPendientes(ctx context.Context, ids []uuid.UUID) error {
	_, err := q.db.Exec(ctx, marcarFotosPendientes, ids)
	return err
}

const platoParaFoto = `-- name: PlatoParaFoto :one
SELECT p.id, p.importacion_id, p.nombre, p.descripcion, p.foto_estado, p.foto_origen
  FROM plato p
 WHERE p.id = $1
`

type PlatoParaFotoRow struct {
	ID            uuid.UUID
	ImportacionID uuid.UUID
	Nombre        string
	Descripcion   string
	FotoEstado    string
	FotoOrigen    string
}

// El plato con su importacion, que es lo que el worker necesita para saber a que
// presupuesto cargarle la foto.
func (q *Queries) PlatoParaFoto(ctx context.Context, platoID uuid.UUID) (PlatoParaFotoRow, error) {
	row := q.db.QueryRow(ctx, platoParaFoto, platoID)
	var i PlatoParaFotoRow
	err := row.Scan(
		&i.ID,
		&i.ImportacionID,
		&i.Nombre,
		&i.Descripcion,
		&i.FotoEstado,
		&i.FotoOrigen,
	)
	return i, err
}

const platosGenerables = `-- name: PlatosGenerables :many
SELECT p.id
  FROM plato p
 WHERE p.importacion_id = $1
   AND p.foto_origen <> 'propia'
   AND (
        p.foto_estado IN ('vacia', 'error')
        OR ($2::uuid[] IS NOT NULL AND p.foto_estado = 'lista')
       )
   AND ($2::uuid[] IS NULL OR p.id = ANY($2::uuid[]))
 ORDER BY p.orden_categoria, p.orden, p.id
`

type PlatosGenerablesParams struct {
	ImportacionID uuid.UUID
	SoloEstos     []uuid.UUID
}

// Los platos a los que tiene sentido generarles foto.
//
// Se saltan SIEMPRE los que tienen foto propia: la que subio el dueno es mejor
// que cualquier cosa que generemos, y pisarla seria destruir trabajo suyo.
//
// UNA FOTO YA HECHA SE REGENERA SOLO SI LA PIDEN POR SU NOMBRE. Esa es la
// diferencia entre las dos ramas y no es un detalle:
//
//	solo_estos NULL  ("generar todas")  -> vacia y error. Nunca 'lista', porque
//	                 darle dos veces al boton pagaria de nuevo las 60 fotos que
//	                 ya estaban.
//	solo_estos lleno ("regenerar este") -> tambien 'lista'. Es una peticion
//	                 explicita del dueno sobre UN plato, normalmente porque
//	                 acaba de corregir el texto con el lapiz.
//
// Sin la segunda rama el boton Regenerar era un no-op: respondia 202 con
// encoladas=0, sin error en ningun log y sin que la foto cambiara nunca.
func (q *Queries) PlatosGenerables(ctx context.Context, arg PlatosGenerablesParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, platosGenerables, arg.ImportacionID, arg.SoloEstos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reclamarFoto = `-- name: ReclamarFoto :one
UPDATE plato p
   SET foto_estado    = 'generando',
       foto_tomada_at = now(),
       foto_intentos  = foto_intentos + 1
 WHERE p.id = $1
   AND p.foto_intentos < $2::int
   AND (
        p.foto_estado IN ('pendiente', 'error')
        OR (p.foto_estado = 'generando' AND p.foto_tomada_at < now() - $3::interval)
       )
   AND (SELECT count(*) FROM plato p2
         WHERE p2.importacion_id = $4
           AND p2.foto_estado    = 'generando'
           AND p2.id            <> $1
           AND p2.foto_tomada_at > now() - $3::interval
       ) < $5::int
RETURNING p.id, p.nombre, p.descripcion, p.categoria, p.plato_tipico,
          p.foto_ajuste, p.foto_referencias, p.foto_clave
`

type ReclamarFotoParams struct {
	PlatoID           uuid.UUID
	MaxIntentos       int32
	Rescate           pgtype.Interval
	ImportacionID     uuid.UUID
	MaxPorRestaurante int32
}

type ReclamarFotoRow struct {
	ID              uuid.UUID
	Nombre          string
	Descripcion     string
	Categoria       string
	PlatoTipico     string
	FotoAjuste      string
	FotoReferencias []byte
	FotoClave       string
}

// EL CLAIM. Es lo primero que hace el worker y lo que impide pagar dos veces.
//
// Hace tres cosas en una sola sentencia atomica:
//  1. toma el plato solo si esta disponible (pendiente, con error, o abandonado)
//  2. topea los intentos, porque cada uno cuesta $0.0336
//  3. respeta el techo de fotos en vuelo POR RESTAURANTE
//
// Devolver 0 filas significa "este no me toca" y el worker se retira sin gastar.
//
// La rama de 'generando' con foto_tomada_at vieja es la VENTANA DE RESCATE: sin
// ella, un worker que muere deja el plato en 'generando' para siempre y ninguna
// capa lo recupera. Es el bug de los 30 minutos que documento el servicio hermano.
//
// La subconsulta del final es el techo por restaurante. Con 8 workers y techo 4,
// un restaurante solo usa la mitad de la capacidad y hace sus 60 fotos en ~63 s,
// y dos a la vez van los dos a full sin esperarse. Si fuera mas bajo, el caso mas
// comun del demo —un restaurante solo— iria a la mitad de velocidad sin motivo.
//
// EL TECHO ES DURO, y hace falta un lock para que lo sea.
//
// La primera version no lo tenia y el techo se filtraba: en READ COMMITTED cada
// claim ve una instantanea que NO incluye los UPDATE sin confirmar de los otros
// workers, asi que varios cuentan "hay 3 en vuelo" a la vez y entran todos.
// MEDIDO con el tope en 4: se observaron 6 generando a la vez.
//
// Lo cierra ReclamarFotoConLock, que toma un pg_advisory_xact_lock sobre la
// importacion antes de contar. Serializa los claims de UNA MISMA carta y no toca
// a las demas: dos restaurantes distintos siguen reclamando en paralelo, que es
// justo lo que el techo quiere proteger.
//
// El lock es de transaccion, asi que se suelta solo al confirmar o deshacer. No
// hay forma de olvidarse de liberarlo.
func (q *Queries) ReclamarFoto(ctx context.Context, arg ReclamarFotoParams) (ReclamarFotoRow, error) {
	row := q.db.QueryRow(ctx, reclamarFoto,
		arg.PlatoID,
		arg.MaxIntentos,
		arg.Rescate,
		arg.ImportacionID,
		arg.MaxPorRestaurante,
	)
	var i ReclamarFotoRow
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Descripcion,
		&i.Categoria,
		&i.PlatoTipico,
		&i.FotoAjuste,
		&i.FotoReferencias,
		&i.FotoClave,
	)
	return i, err
}

const reservarPresupuesto = `-- name: ReservarPresupuesto :one
UPDATE importacion
   SET reservado_micros = reservado_micros + $1::bigint
 WHERE id = $2
   AND reservado_micros + $1::bigint <= presupuesto_micros
RETURNING reservado_micros
`

type ReservarPresupuestoParams struct {
	Costo         int64
	ImportacionID uuid.UUID
}

// LA RESERVA DE PRESUPUESTO. Se cobra ANTES de gastar, no despues.
//
// Si se comprobara despues, 60 workers concurrentes leerian todos "aun queda" y
// se pasarian todos a la vez. Aqui la condicion y el incremento son la misma
// sentencia, asi que el ultimo que cabe es el ultimo que entra.
//
// Para imagenes el estimado ES el real (precio fijo por imagen), asi que no hace
// falta reconciliar despues.
func (q *Queries) ReservarPresupuesto(ctx context.Context, arg ReservarPresupuestoParams) (int64, error) {
	row := q.db.QueryRow(ctx, reservarPresupuesto, arg.Costo, arg.ImportacionID)
	var reservado_micros int64
	err := row.Scan(&reservado_micros)
	return reservado_micros, err
}

const restauranteDeImportacion = `-- name: RestauranteDeImportacion :one
SELECT r.id, r.tipos
  FROM restaurante r
  JOIN importacion i ON i.restaurante_id = r.id
 WHERE i.id = $1
`

type RestauranteDeImportacionRow struct {
	ID    uuid.UUID
	Tipos []byte
}

// El restaurante de una importacion, con sus tipos. El worker lo necesita para
// armar la receta y solo tiene el id del plato.
func (q *Queries) RestauranteDeImportacion(ctx context.Context, importacionID uuid.UUID) (RestauranteDeImportacionRow, error) {
	row := q.db.QueryRow(ctx, restauranteDeImportacion, importacionID)
	var i RestauranteDeImportacionRow
	err := row.Scan(&i.ID, &i.Tipos)
	return i, err
}

const vistaDeBase = `-- name: VistaDeBase :one
SELECT vista_clave
  FROM base_foto
 WHERE restaurante_id = $1
   AND categoria = $2
`

type VistaDeBaseParams struct {
	RestauranteID uuid.UUID
	Categoria     string
}

// LA VISTA PREVIA de una categoria, sin plegar.
//
// Al contrario que BaseDeFoto: la vista es la foto de ESTA fila. Heredar la de
// la general enseniaria el plato del restaurante diciendo que es el de la
// seccion, que es justo la duda que la vista existe para resolver.
//
// Sin fila devuelve cero filas y eso significa "todavia no hay vista".
func (q *Queries) VistaDeBase(ctx context.Context, arg VistaDeBaseParams) (string, error) {
	row := q.db.QueryRow(ctx, vistaDeBase, arg.RestauranteID, arg.Categoria)
	var vista_clave string
	err := row.Scan(&vista_clave)
	return vista_clave, err
}
