// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: importacion.sql

package cartadb

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const actualizarMarcas = `-- name: ActualizarMarcas :exec
UPDATE importacion
   SET marcas_revisar   = $1,
       marcas_confirmar = $2,
       actualizado_at   = now()
 WHERE id = $3
`

type ActualizarMarcasParams struct {
	Revisar   int32
	Confirmar int32
	ID        uuid.UUID
}

func (q *Queries) ActualizarMarcas(ctx context.Context, arg ActualizarMarcasParams) error {
	_, err := q.db.Exec(ctx, actualizarMarcas, arg.Revisar, arg.Confirmar, arg.ID)
	return err
}

const actualizarPlato = `-- name: ActualizarPlato :exec
UPDATE plato
   SET precios = $1,
       revisar = $2
 WHERE id = $3
`

type ActualizarPlatoParams struct {
	Precios []byte
	Revisar string
	PlatoID uuid.UUID
}

// El plato tras una edicion del dueno: sus precios y la marca recalculada.
//
// No toca la foto ni el orden: el dueno corrige datos, no reorganiza la carta.
func (q *Queries) ActualizarPlato(ctx context.Context, arg ActualizarPlatoParams) error {
	_, err := q.db.Exec(ctx, actualizarPlato, arg.Precios, arg.Revisar, arg.PlatoID)
	return err
}

const actualizarPlatoLeido = `-- name: ActualizarPlatoLeido :exec
UPDATE plato
   SET categoria       = $1,
       orden_categoria = $2,
       orden           = $3,
       nombre          = $4,
       descripcion     = $5,
       precios         = $6,
       revisar         = $7,
       plato_tipico    = $8,
       tipico_origen   = $9,
       hoja_clave      = $10,
       ausente         = false
 WHERE id = $11
`

type ActualizarPlatoLeidoParams struct {
	Categoria      string
	OrdenCategoria int32
	Orden          int32
	Nombre         string
	Descripcion    string
	Precios        []byte
	Revisar        string
	PlatoTipico    string
	TipicoOrigen   string
	HojaClave      string
	ID             uuid.UUID
}

// El plato que la lectura VOLVIO a traer.
//
// Se actualiza lo IMPRESO y nada mas: la foto, su ajuste y las fotos de ejemplo
// del dueno no salen del papel, asi que ninguna lectura tiene nada que decir
// sobre ellas. Y no se toca el id, que es de donde cuelga la foto.
//
// ausente vuelve a false: si estaba marcado como desaparecido y la carta lo trae
// otra vez, es que sigue ahi.
func (q *Queries) ActualizarPlatoLeido(ctx context.Context, arg ActualizarPlatoLeidoParams) error {
	_, err := q.db.Exec(ctx, actualizarPlatoLeido,
		arg.Categoria,
		arg.OrdenCategoria,
		arg.Orden,
		arg.Nombre,
		arg.Descripcion,
		arg.Precios,
		arg.Revisar,
		arg.PlatoTipico,
		arg.TipicoOrigen,
		arg.HojaClave,
		arg.ID,
	)
	return err
}

const anotarGastoIA = `-- name: AnotarGastoIA :exec
INSERT INTO gasto_ia (
    importacion_id, tarea, modelo,
    tokens_entrada, tokens_salida, imagenes, costo_micros, intentos
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type AnotarGastoIAParams struct {
	ImportacionID *uuid.UUID
	Tarea         string
	Modelo        string
	TokensEntrada int32
	TokensSalida  int32
	Imagenes      int32
	CostoMicros   int64
	Intentos      int32
}

func (q *Queries) AnotarGastoIA(ctx context.Context, arg AnotarGastoIAParams) error {
	_, err := q.db.Exec(ctx, anotarGastoIA,
		arg.ImportacionID,
		arg.Tarea,
		arg.Modelo,
		arg.TokensEntrada,
		arg.TokensSalida,
		arg.Imagenes,
		arg.CostoMicros,
		arg.Intentos,
	)
	return err
}

const borrarPlato = `-- name: BorrarPlato :exec
DELETE FROM plato WHERE id = $1
`

func (q *Queries) BorrarPlato(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, borrarPlato, id)
	return err
}

const borrarPlatosDeImportacion = `-- name: BorrarPlatosDeImportacion :exec
DELETE FROM plato WHERE importacion_id = $1
`

// Borrar antes de insertar hace que reintentar el job de lectura entero sea
// seguro: no quedan platos de la corrida anterior mezclados con los nuevos.
func (q *Queries) BorrarPlatosDeImportacion(ctx context.Context, importacionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, borrarPlatosDeImportacion, importacionID)
	return err
}

const borrarPlatosDeLaHoja = `-- name: BorrarPlatosDeLaHoja :execrows
DELETE FROM plato
 WHERE importacion_id = $1 AND hoja_clave = $2
`

type BorrarPlatosDeLaHojaParams struct {
	ImportacionID uuid.UUID
	HojaClave     string
}

// Los platos que salieron de UNA hoja, borrados de verdad.
//
// Se llega aqui SOLO cuando el dueno lo eligio en el aviso de quitar la hoja, y
// no tiene vuelta atras: si alguno tenia foto, se va con el. La otra opcion del
// aviso —mantenerlos— no llama a nada, que es justo por lo que no hay un
// "borrar por si acaso" en ningun camino automatico.
//
// Los que no tienen hoja atribuida quedan fuera: no sabemos si eran de esta.
func (q *Queries) BorrarPlatosDeLaHoja(ctx context.Context, arg BorrarPlatosDeLaHojaParams) (int64, error) {
	result, err := q.db.Exec(ctx, borrarPlatosDeLaHoja, arg.ImportacionID, arg.HojaClave)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clavesDeImagenes = `-- name: ClavesDeImagenes :one
SELECT imagenes FROM importacion WHERE id = $1
`

// Las claves de las fotos que subio el dueno. El worker las necesita para releer
// las imagenes del almacen: cuando el job corre, la peticion HTTP que las traia
// en memoria ya termino hace rato.
func (q *Queries) ClavesDeImagenes(ctx context.Context, id uuid.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, clavesDeImagenes, id)
	var imagenes []byte
	err := row.Scan(&imagenes)
	return imagenes, err
}

const crearImportacion = `-- name: CrearImportacion :exec
INSERT INTO importacion (id, restaurante_id, estado, ip, imagenes, presupuesto_micros)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CrearImportacionParams struct {
	ID                uuid.UUID
	RestauranteID     uuid.UUID
	Estado            string
	Ip                *netip.Addr
	Imagenes          []byte
	PresupuestoMicros int64
}

func (q *Queries) CrearImportacion(ctx context.Context, arg CrearImportacionParams) error {
	_, err := q.db.Exec(ctx, crearImportacion,
		arg.ID,
		arg.RestauranteID,
		arg.Estado,
		arg.Ip,
		arg.Imagenes,
		arg.PresupuestoMicros,
	)
	return err
}

const crearRestaurante = `-- name: CrearRestaurante :exec
INSERT INTO restaurante (id, nombre, token_hash, tipos)
VALUES ($1, $2, $3, $4)
`

type CrearRestauranteParams struct {
	ID        uuid.UUID
	Nombre    string
	TokenHash []byte
	Tipos     []byte
}

func (q *Queries) CrearRestaurante(ctx context.Context, arg CrearRestauranteParams) error {
	_, err := q.db.Exec(ctx, crearRestaurante,
		arg.ID,
		arg.Nombre,
		arg.TokenHash,
		arg.Tipos,
	)
	return err
}

const gastoPorTarea = `-- name: GastoPorTarea :many
SELECT tarea, count(*) AS llamadas, sum(costo_micros)::bigint AS costo_micros
  FROM gasto_ia
 WHERE importacion_id = $1
 GROUP BY tarea
 ORDER BY costo_micros DESC
`

type GastoPorTareaRow struct {
	Tarea       string
	Llamadas    int64
	CostoMicros int64
}

// El unit economics de una carta, que es la unica pregunta de observabilidad que
// el demo necesita responder.
func (q *Queries) GastoPorTarea(ctx context.Context, importacionID *uuid.UUID) ([]GastoPorTareaRow, error) {
	rows, err := q.db.Query(ctx, gastoPorTarea, importacionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GastoPorTareaRow{}
	for rows.Next() {
		var i GastoPorTareaRow
		if err := rows.Scan(&i.Tarea, &i.Llamadas, &i.CostoMicros); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const guardarHojasIniciales = `-- name: GuardarHojasIniciales :execrows
UPDATE importacion
   SET imagenes = $1, estado = $2
 WHERE id = $3 AND estado IN ('nueva','fallida')
`

type GuardarHojasInicialesParams struct {
	Imagenes []byte
	Estado   string
	ID       uuid.UUID
}

// Las hojas de la carta llegan DESPUES de crear el restaurante, asi que el
// estado viaja con ellas: es lo mismo que las pone en cola de lectura.
//
// El WHERE es la guarda: una carta que ya se esta LEYENDO o que ya se leyo no
// puede volver al principio por aqui. Para anadir hojas a una carta leida esta
// GuardarPaginas, que suma en vez de reemplazar.
//
// 'fallida' SI entra: es el "volver a intentar" del dueno cuando la foto salio
// movida. Sin eso tendria que crear otro restaurante desde cero y perder el
// nombre y los tipos que ya escribio, que es justo lo que este flujo vino a
// arreglar. No hay nada que pisar: una lectura fallida no dejo platos.
func (q *Queries) GuardarHojasIniciales(ctx context.Context, arg GuardarHojasInicialesParams) (int64, error) {
	result, err := q.db.Exec(ctx, guardarHojasIniciales, arg.Imagenes, arg.Estado, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const guardarImagenesDeImportacion = `-- name: GuardarImagenesDeImportacion :exec
UPDATE importacion SET imagenes = $1, actualizado_at = now() WHERE id = $2
`

type GuardarImagenesDeImportacionParams struct {
	Imagenes []byte
	ID       uuid.UUID
}

// Las paginas de la carta. Sirve para las tres cosas que el dueno puede hacer
// con ellas —anadir, quitar y reordenar—: las tres son la misma lista escrita
// entera, y separarlas en tres UPDATE distintos seria el mismo SQL tres veces.
func (q *Queries) GuardarImagenesDeImportacion(ctx context.Context, arg GuardarImagenesDeImportacionParams) error {
	_, err := q.db.Exec(ctx, guardarImagenesDeImportacion, arg.Imagenes, arg.ID)
	return err
}

const guardarLetrero = `-- name: GuardarLetrero :exec
UPDATE restaurante SET letrero_clave = $1 WHERE id = $2
`

type GuardarLetreroParams struct {
	LetreroClave  string
	RestauranteID uuid.UUID
}

func (q *Queries) GuardarLetrero(ctx context.Context, arg GuardarLetreroParams) error {
	_, err := q.db.Exec(ctx, guardarLetrero, arg.LetreroClave, arg.RestauranteID)
	return err
}

const guardarLogo = `-- name: GuardarLogo :exec
UPDATE restaurante SET logo_clave = $1 WHERE id = $2
`

type GuardarLogoParams struct {
	LogoClave     string
	RestauranteID uuid.UUID
}

func (q *Queries) GuardarLogo(ctx context.Context, arg GuardarLogoParams) error {
	_, err := q.db.Exec(ctx, guardarLogo, arg.LogoClave, arg.RestauranteID)
	return err
}

const guardarNombreDeRestaurante = `-- name: GuardarNombreDeRestaurante :exec
UPDATE restaurante SET nombre = $1 WHERE id = $2
`

type GuardarNombreDeRestauranteParams struct {
	Nombre string
	ID     uuid.UUID
}

// El slug NO se toca aqui: se recalcula al publicar. Renombrar sin publicar deja
// la direccion vieja viva, que es justo lo que hay que hacer con una URL que el
// dueno ya repartio por WhatsApp.
func (q *Queries) GuardarNombreDeRestaurante(ctx context.Context, arg GuardarNombreDeRestauranteParams) error {
	_, err := q.db.Exec(ctx, guardarNombreDeRestaurante, arg.Nombre, arg.ID)
	return err
}

const guardarPortada = `-- name: GuardarPortada :exec
UPDATE restaurante SET portada_clave = $1 WHERE id = $2
`

type GuardarPortadaParams struct {
	PortadaClave  string
	RestauranteID uuid.UUID
}

func (q *Queries) GuardarPortada(ctx context.Context, arg GuardarPortadaParams) error {
	_, err := q.db.Exec(ctx, guardarPortada, arg.PortadaClave, arg.RestauranteID)
	return err
}

const importacionPublicadaPorSlug = `-- name: ImportacionPublicadaPorSlug :one
SELECT i.id, r.nombre AS restaurante_nombre, r.slug AS restaurante_slug,
       r.portada_clave AS restaurante_portada,
       r.logo_clave AS restaurante_logo,
       r.letrero_clave AS restaurante_letrero
  FROM restaurante r
  JOIN importacion i ON i.id = r.importacion_publicada_id
 WHERE r.slug = $1
`

type ImportacionPublicadaPorSlugRow struct {
	ID                 uuid.UUID
	RestauranteNombre  string
	RestauranteSlug    *string
	RestaurantePortada string
	RestauranteLogo    string
	RestauranteLetrero string
}

// La carta publica. SIN token: es la que ve el cliente del restaurante.
//
// Va por slug y salta a la importacion PUBLICADA, no a la ultima: seguir
// editando un borrador nuevo no puede cambiar lo que el cliente esta viendo.
func (q *Queries) ImportacionPublicadaPorSlug(ctx context.Context, slug *string) (ImportacionPublicadaPorSlugRow, error) {
	row := q.db.QueryRow(ctx, importacionPublicadaPorSlug, slug)
	var i ImportacionPublicadaPorSlugRow
	err := row.Scan(
		&i.ID,
		&i.RestauranteNombre,
		&i.RestauranteSlug,
		&i.RestaurantePortada,
		&i.RestauranteLogo,
		&i.RestauranteLetrero,
	)
	return i, err
}

const insertarPlato = `-- name: InsertarPlato :exec
INSERT INTO plato (
    id, importacion_id, categoria, orden_categoria, orden,
    nombre, descripcion, precios, revisar,
    plato_tipico, tipico_origen, hoja_clave
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type InsertarPlatoParams struct {
	ID             uuid.UUID
	ImportacionID  uuid.UUID
	Categoria      string
	OrdenCategoria int32
	Orden          int32
	Nombre         string
	Descripcion    string
	Precios        []byte
	Revisar        string
	PlatoTipico    string
	TipicoOrigen   string
	HojaClave      string
}

func (q *Queries) InsertarPlato(ctx context.Context, arg InsertarPlatoParams) error {
	_, err := q.db.Exec(ctx, insertarPlato,
		arg.ID,
		arg.ImportacionID,
		arg.Categoria,
		arg.OrdenCategoria,
		arg.Orden,
		arg.Nombre,
		arg.Descripcion,
		arg.Precios,
		arg.Revisar,
		arg.PlatoTipico,
		arg.TipicoOrigen,
		arg.HojaClave,
	)
	return err
}

const listarEstadoDeFotos = `-- name: ListarEstadoDeFotos :many
SELECT id, foto_estado, foto_clave, foto_origen
  FROM plato
 WHERE importacion_id = $1
 ORDER BY orden_categoria, orden, id
`

type ListarEstadoDeFotosRow struct {
	ID         uuid.UUID
	FotoEstado string
	FotoClave  string
	FotoOrigen string
}

// Lista flaca para el poll del minuto de las fotos: 60 platos son ~7 KB en vez
// de la carta entera. El front ya tiene el catalogo, solo parchea las URLs.
func (q *Queries) ListarEstadoDeFotos(ctx context.Context, importacionID uuid.UUID) ([]ListarEstadoDeFotosRow, error) {
	rows, err := q.db.Query(ctx, listarEstadoDeFotos, importacionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListarEstadoDeFotosRow{}
	for rows.Next() {
		var i ListarEstadoDeFotosRow
		if err := rows.Scan(
			&i.ID,
			&i.FotoEstado,
			&i.FotoClave,
			&i.FotoOrigen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarPlatos = `-- name: ListarPlatos :many
SELECT id, importacion_id, categoria, orden_categoria, orden, nombre, descripcion, precios, revisar, foto_estado, foto_origen, foto_clave, foto_intentos, foto_tomada_at, foto_actualizada_at, foto_ajuste, foto_referencias, plato_tipico, tipico_origen, hoja_clave, ausente FROM plato
 WHERE importacion_id = $1
 ORDER BY orden_categoria, orden, id
`

// El orden es el del catalogo, no el de insercion: lo fija OrganizarCarta y el
// dueno puede cambiarlo despues.
func (q *Queries) ListarPlatos(ctx context.Context, importacionID uuid.UUID) ([]Plato, error) {
	rows, err := q.db.Query(ctx, listarPlatos, importacionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plato{}
	for rows.Next() {
		var i Plato
		if err := rows.Scan(
			&i.ID,
			&i.ImportacionID,
			&i.Categoria,
			&i.OrdenCategoria,
			&i.Orden,
			&i.Nombre,
			&i.Descripcion,
			&i.Precios,
			&i.Revisar,
			&i.FotoEstado,
			&i.FotoOrigen,
			&i.FotoClave,
			&i.FotoIntentos,
			&i.FotoTomadaAt,
			&i.FotoActualizadaAt,
			&i.FotoAjuste,
			&i.FotoReferencias,
			&i.PlatoTipico,
			&i.TipicoOrigen,
			&i.HojaClave,
			&i.Ausente,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const marcaDeRestaurante = `-- name: MarcaDeRestaurante :one
SELECT logo_clave, letrero_clave FROM restaurante WHERE id = $1
`

type MarcaDeRestauranteRow struct {
	LogoClave    string
	LetreroClave string
}

// El logo y su fuente. Se leen antes de pisarlos para poder borrar del almacen lo
// que deja de usarse: sin eso, cada intento deja el anterior pagando sitio.
func (q *Queries) MarcaDeRestaurante(ctx context.Context, id uuid.UUID) (MarcaDeRestauranteRow, error) {
	row := q.db.QueryRow(ctx, marcaDeRestaurante, id)
	var i MarcaDeRestauranteRow
	err := row.Scan(&i.LogoClave, &i.LetreroClave)
	return i, err
}

const marcarEtapa = `-- name: MarcarEtapa :exec
UPDATE importacion SET etapa = $1, actualizado_at = now() WHERE id = $2
`

type MarcarEtapaParams struct {
	Etapa int16
	ID    uuid.UUID
}

func (q *Queries) MarcarEtapa(ctx context.Context, arg MarcarEtapaParams) error {
	_, err := q.db.Exec(ctx, marcarEtapa, arg.Etapa, arg.ID)
	return err
}

const marcarImportacionFallida = `-- name: MarcarImportacionFallida :exec
UPDATE importacion
   SET estado         = 'fallida',
       error          = $2,
       actualizado_at = now()
 WHERE id = $1
`

type MarcarImportacionFallidaParams struct {
	ID    uuid.UUID
	Error string
}

func (q *Queries) MarcarImportacionFallida(ctx context.Context, arg MarcarImportacionFallidaParams) error {
	_, err := q.db.Exec(ctx, marcarImportacionFallida, arg.ID, arg.Error)
	return err
}

const marcarImportacionLista = `-- name: MarcarImportacionLista :exec
UPDATE importacion
   SET estado           = 'lista',
       carta_cruda      = $2,
       marcas_revisar   = $3,
       marcas_confirmar = $4,
       error            = '',
       actualizado_at   = now()
 WHERE id = $1
`

type MarcarImportacionListaParams struct {
	ID              uuid.UUID
	CartaCruda      []byte
	MarcasRevisar   int32
	MarcasConfirmar int32
}

// Guardar el resultado de la lectura. carta_cruda es lo que devolvio el modelo
// tal cual: si manana la extraccion sale mal, se depura sobre esto en vez de
// volver a pagarla.
func (q *Queries) MarcarImportacionLista(ctx context.Context, arg MarcarImportacionListaParams) error {
	_, err := q.db.Exec(ctx, marcarImportacionLista,
		arg.ID,
		arg.CartaCruda,
		arg.MarcasRevisar,
		arg.MarcasConfirmar,
	)
	return err
}

const marcarImportacionPublicada = `-- name: MarcarImportacionPublicada :exec
UPDATE importacion
   SET estado = 'publicada', actualizado_at = now()
 WHERE id = $1
`

func (q *Queries) MarcarImportacionPublicada(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, marcarImportacionPublicada, id)
	return err
}

const marcarPlatosAusentes = `-- name: MarcarPlatosAusentes :exec
UPDATE plato SET ausente = true WHERE id = ANY($1::uuid[])
`

// Los que estaban y esta lectura ya no trajo. Se MARCAN, no se borran: pueden
// tener una foto pagada detras y la lectura pudo equivocarse.
func (q *Queries) MarcarPlatosAusentes(ctx context.Context, ids []uuid.UUID) error {
	_, err := q.db.Exec(ctx, marcarPlatosAusentes, ids)
	return err
}

const motivosDeImportacion = `-- name: MotivosDeImportacion :many
SELECT revisar FROM plato WHERE importacion_id = $1
`

// Los motivos de revision de toda la carta, para recontar las marcas tras una
// edicion.
//
// Se recuentan en Go y no con un COUNT(...) FILTER porque QUE motivo bloquea y
// cual solo pide confirmacion es una regla del dominio (MotivoRevision.Nivel).
// Escrita en SQL, seria la misma regla en dos sitios y el dia que no coincidan
// la barra de publicar mentiria.
func (q *Queries) MotivosDeImportacion(ctx context.Context, importacionID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, motivosDeImportacion, importacionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var revisar string
		if err := rows.Scan(&revisar); err != nil {
			return nil, err
		}
		items = append(items, revisar)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obtenerImportacion = `-- name: ObtenerImportacion :one
SELECT i.id, i.restaurante_id, i.estado, i.ip, i.imagenes, i.carta_cruda, i.marcas_revisar, i.marcas_confirmar, i.presupuesto_micros, i.reservado_micros, i.gastado_micros, i.error, i.creado_at, i.actualizado_at, i.etapa, r.nombre AS restaurante_nombre, r.slug AS restaurante_slug,
       r.portada_clave AS restaurante_portada,
       r.logo_clave AS restaurante_logo,
       r.letrero_clave AS restaurante_letrero
  FROM importacion i
  JOIN restaurante r ON r.id = i.restaurante_id
 WHERE i.id = $1
`

type ObtenerImportacionRow struct {
	ID                 uuid.UUID
	RestauranteID      uuid.UUID
	Estado             string
	Ip                 *netip.Addr
	Imagenes           []byte
	CartaCruda         []byte
	MarcasRevisar      int32
	MarcasConfirmar    int32
	PresupuestoMicros  int64
	ReservadoMicros    int64
	GastadoMicros      int64
	Error              string
	CreadoAt           pgtype.Timestamptz
	ActualizadoAt      pgtype.Timestamptz
	Etapa              int16
	RestauranteNombre  string
	RestauranteSlug    *string
	RestaurantePortada string
	RestauranteLogo    string
	RestauranteLetrero string
}

func (q *Queries) ObtenerImportacion(ctx context.Context, id uuid.UUID) (ObtenerImportacionRow, error) {
	row := q.db.QueryRow(ctx, obtenerImportacion, id)
	var i ObtenerImportacionRow
	err := row.Scan(
		&i.ID,
		&i.RestauranteID,
		&i.Estado,
		&i.Ip,
		&i.Imagenes,
		&i.CartaCruda,
		&i.MarcasRevisar,
		&i.MarcasConfirmar,
		&i.PresupuestoMicros,
		&i.ReservadoMicros,
		&i.GastadoMicros,
		&i.Error,
		&i.CreadoAt,
		&i.ActualizadoAt,
		&i.Etapa,
		&i.RestauranteNombre,
		&i.RestauranteSlug,
		&i.RestaurantePortada,
		&i.RestauranteLogo,
		&i.RestauranteLetrero,
	)
	return i, err
}

const ordenesDeCategorias = `-- name: OrdenesDeCategorias :many

SELECT categoria,
       MIN(orden_categoria)::int AS orden_categoria,
       MAX(orden)::int           AS ultimo
  FROM plato
 WHERE importacion_id = $1
 GROUP BY categoria
`

type OrdenesDeCategoriasRow struct {
	Categoria      string
	OrdenCategoria int32
	Ultimo         int32
}

// GREATEST(0, ...) porque un decremento de mas dejaria el contador en negativo y
// la pantalla diria "leyendo" para siempre.
func (q *Queries) OrdenesDeCategorias(ctx context.Context, importacionID uuid.UUID) ([]OrdenesDeCategoriasRow, error) {
	rows, err := q.db.Query(ctx, ordenesDeCategorias, importacionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrdenesDeCategoriasRow{}
	for rows.Next() {
		var i OrdenesDeCategoriasRow
		if err := rows.Scan(&i.Categoria, &i.OrdenCategoria, &i.Ultimo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const platoPorID = `-- name: PlatoPorID :one
SELECT id, importacion_id, categoria, orden_categoria, orden, nombre, descripcion, precios, revisar, foto_estado, foto_origen, foto_clave, foto_intentos, foto_tomada_at, foto_actualizada_at, foto_ajuste, foto_referencias, plato_tipico, tipico_origen, hoja_clave, ausente FROM plato WHERE id = $1
`

func (q *Queries) PlatoPorID(ctx context.Context, id uuid.UUID) (Plato, error) {
	row := q.db.QueryRow(ctx, platoPorID, id)
	var i Plato
	err := row.Scan(
		&i.ID,
		&i.ImportacionID,
		&i.Categoria,
		&i.OrdenCategoria,
		&i.Orden,
		&i.Nombre,
		&i.Descripcion,
		&i.Precios,
		&i.Revisar,
		&i.FotoEstado,
		&i.FotoOrigen,
		&i.FotoClave,
		&i.FotoIntentos,
		&i.FotoTomadaAt,
		&i.FotoActualizadaAt,
		&i.FotoAjuste,
		&i.FotoReferencias,
		&i.PlatoTipico,
		&i.TipicoOrigen,
		&i.HojaClave,
		&i.Ausente,
	)
	return i, err
}

const platosParaReconciliar = `-- name: PlatosParaReconciliar :many
SELECT id, nombre, hoja_clave FROM plato WHERE importacion_id = $1
`

type PlatosParaReconciliarRow struct {
	ID        uuid.UUID
	Nombre    string
	HojaClave string
}

// Lo minimo para cruzar una lectura contra lo que ya hay.
func (q *Queries) PlatosParaReconciliar(ctx context.Context, importacionID uuid.UUID) ([]PlatosParaReconciliarRow, error) {
	rows, err := q.db.Query(ctx, platosParaReconciliar, importacionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatosParaReconciliarRow{}
	for rows.Next() {
		var i PlatosParaReconciliarRow
		if err := rows.Scan(&i.ID, &i.Nombre, &i.HojaClave); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const portadaDeRestaurante = `-- name: PortadaDeRestaurante :one
SELECT portada_clave FROM restaurante WHERE id = $1
`

// La foto del local que encabeza el catalogo. Se lee la anterior antes de pisarla
// para poder borrarla del almacen: sin eso, cada portada nueva deja la vieja
// pagando sitio en el bucket para siempre.
func (q *Queries) PortadaDeRestaurante(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, portadaDeRestaurante, id)
	var portada_clave string
	err := row.Scan(&portada_clave)
	return portada_clave, err
}

const publicarImportacion = `-- name: PublicarImportacion :exec
UPDATE restaurante
   SET slug                     = $1,
       importacion_publicada_id = $2
 WHERE id = $3
`

type PublicarImportacionParams struct {
	Slug          *string
	ImportacionID *uuid.UUID
	RestauranteID uuid.UUID
}

// PUBLICAR es mover un puntero, no copiar la carta.
//
// El restaurante apunta a la importacion que se ve en publico. Reimportar y
// volver a publicar es cambiar este uuid: sin downtime, y volver atras es
// apuntar a la anterior.
func (q *Queries) PublicarImportacion(ctx context.Context, arg PublicarImportacionParams) error {
	_, err := q.db.Exec(ctx, publicarImportacion, arg.Slug, arg.ImportacionID, arg.RestauranteID)
	return err
}

const recuperarPlato = `-- name: RecuperarPlato :exec
UPDATE plato SET ausente = false WHERE id = $1
`

func (q *Queries) RecuperarPlato(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, recuperarPlato, id)
	return err
}

const releerCarta = `-- name: ReleerCarta :execrows
UPDATE importacion
   SET estado = 'leyendo', etapa = 0, error = ''
 WHERE id = $1 AND estado = 'lista'
`

// Volver a leer la carta ENTERA desde sus hojas.
//
// Solo desde 'lista': una que se esta leyendo ya esta en ello, y una publicada
// tiene un catalogo en la calle que no se puede vaciar por detras.
//
// Devuelve las filas tocadas para que el borde distinga "no se puede" de "no
// existe". El contador de paginas pendientes se pone a cero porque la lectura
// entera reemplaza los platos: una lectura de hoja suelta en vuelo dejaria de
// tener sentido igual.
func (q *Queries) ReleerCarta(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, releerCarta, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const slugTomado = `-- name: SlugTomado :one
SELECT EXISTS (
  SELECT 1 FROM restaurante WHERE slug = $1 AND id <> $2
)
`

type SlugTomadoParams struct {
	Slug          *string
	RestauranteID uuid.UUID
}

// El slug ya lo tiene OTRO restaurante. Se comprueba antes de escribir para
// poder anadir un sufijo en vez de estrellarse contra el UNIQUE.
func (q *Queries) SlugTomado(ctx context.Context, arg SlugTomadoParams) (bool, error) {
	row := q.db.QueryRow(ctx, slugTomado, arg.Slug, arg.RestauranteID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const sumarGastado = `-- name: SumarGastado :exec
UPDATE importacion
   SET gastado_micros = gastado_micros + $2,
       actualizado_at = now()
 WHERE id = $1
`

type SumarGastadoParams struct {
	ID            uuid.UUID
	GastadoMicros int64
}

// Lo real gastado se acumula aparte de lo reservado: reservado_micros es lo que
// el guard compara ANTES de pagar, gastado_micros es lo que costo DESPUES.
func (q *Queries) SumarGastado(ctx context.Context, arg SumarGastadoParams) error {
	_, err := q.db.Exec(ctx, sumarGastado, arg.ID, arg.GastadoMicros)
	return err
}

const tokenHashDeImportacion = `-- name: TokenHashDeImportacion :one
SELECT r.token_hash
  FROM importacion i
  JOIN restaurante r ON r.id = i.restaurante_id
 WHERE i.id = $1
`

// Devuelve el hash del token para compararlo, no el token: lo que se guarda es
// el SHA-256 y la comparacion se hace en Go con subtle.ConstantTimeCompare.
func (q *Queries) TokenHashDeImportacion(ctx context.Context, id uuid.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, tokenHashDeImportacion, id)
	var token_hash []byte
	err := row.Scan(&token_hash)
	return token_hash, err
}
