// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package cartadb

import (
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type BaseFoto struct {
	ID            uuid.UUID
	RestauranteID uuid.UUID
	Categoria     string
	Recipiente    string
	Fondo         string
	Referencias   []byte
	CreadoAt      pgtype.Timestamptz
	ActualizadoAt pgtype.Timestamptz
	VistaClave    string
}

type GastoIum struct {
	ID            int64
	ImportacionID *uuid.UUID
	Tarea         string
	Modelo        string
	TokensEntrada int32
	TokensSalida  int32
	Imagenes      int32
	CostoMicros   int64
	Intentos      int32
	CreadoAt      pgtype.Timestamptz
}

type Importacion struct {
	ID                uuid.UUID
	RestauranteID     uuid.UUID
	Estado            string
	Ip                *netip.Addr
	Imagenes          []byte
	CartaCruda        []byte
	MarcasRevisar     int32
	MarcasConfirmar   int32
	PresupuestoMicros int64
	ReservadoMicros   int64
	GastadoMicros     int64
	Error             string
	CreadoAt          pgtype.Timestamptz
	ActualizadoAt     pgtype.Timestamptz
	Etapa             int16
}

type Plato struct {
	ID                uuid.UUID
	ImportacionID     uuid.UUID
	Categoria         string
	OrdenCategoria    int32
	Orden             int32
	Nombre            string
	Descripcion       string
	Precios           []byte
	Revisar           string
	FotoEstado        string
	FotoOrigen        string
	FotoClave         string
	FotoIntentos      int32
	FotoTomadaAt      pgtype.Timestamptz
	FotoActualizadaAt pgtype.Timestamptz
	FotoAjuste        string
	FotoReferencias   []byte
	PlatoTipico       string
	TipicoOrigen      string
	HojaClave         string
	Ausente           bool
}

type PlatoTipico struct {
	Clave         string
	Nombre        string
	Cocina        string
	Curso         string
	Aspecto       string
	Recipiente    string
	Guarnicion    string
	Jamas         string
	Patrones      []byte
	Ingredientes  []byte
	ImagenUrl     string
	Region        string
	Origen        string
	Revisado      bool
	CreadoAt      pgtype.Timestamptz
	ActualizadoAt pgtype.Timestamptz
	Envasado      bool
}

type Restaurante struct {
	ID                     uuid.UUID
	Nombre                 string
	Slug                   *string
	TokenHash              []byte
	ImportacionPublicadaID *uuid.UUID
	CreadoAt               pgtype.Timestamptz
	Tipos                  []byte
}
