// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tipico.sql

package cartadb

import (
	"context"

	"github.com/google/uuid"
)

const guardarPlatoTipico = `-- name: GuardarPlatoTipico :exec
INSERT INTO plato_tipico
    (clave, nombre, cocina, curso, aspecto, recipiente, guarnicion, jamas, patrones, origen, revisado)
VALUES
    ($1, $2, $3, $4, $5, $6, $7, $8, $9, 'ia', false)
ON CONFLICT (clave) DO UPDATE SET
    aspecto    = EXCLUDED.aspecto,
    recipiente = EXCLUDED.recipiente,
    guarnicion = EXCLUDED.guarnicion,
    jamas      = EXCLUDED.jamas,
    patrones   = EXCLUDED.patrones,
    origen     = 'ia',
    actualizado_at = now()
 WHERE plato_tipico.aspecto = '' AND plato_tipico.origen <> 'canon'
`

type GuardarPlatoTipicoParams struct {
	Clave      string
	Nombre     string
	Cocina     string
	Curso      string
	Aspecto    string
	Recipiente string
	Guarnicion string
	Jamas      string
	Patrones   []byte
}

// Lo que el banco aprende de una carta nueva.
//
// DO NOTHING y no DO UPDATE: si la clave ya existe, gana lo que hay. El canon
// esta escrito y medido a mano, y una respuesta de la IA no puede pisarlo. Lo
// que se aprende nace sin revisar, para poder mirarlo despues con fotocheck.
func (q *Queries) GuardarPlatoTipico(ctx context.Context, arg GuardarPlatoTipicoParams) error {
	_, err := q.db.Exec(ctx, guardarPlatoTipico,
		arg.Clave,
		arg.Nombre,
		arg.Cocina,
		arg.Curso,
		arg.Aspecto,
		arg.Recipiente,
		arg.Guarnicion,
		arg.Jamas,
		arg.Patrones,
	)
	return err
}

const listarPlatosTipicos = `-- name: ListarPlatosTipicos :many

SELECT clave, nombre, cocina, curso, aspecto, recipiente, guarnicion, jamas,
       envasado, patrones, ingredientes
  FROM plato_tipico
 ORDER BY clave
`

type ListarPlatosTipicosRow struct {
	Clave        string
	Nombre       string
	Cocina       string
	Curso        string
	Aspecto      string
	Recipiente   string
	Guarnicion   string
	Jamas        string
	Envasado     bool
	Patrones     []byte
	Ingredientes []byte
}

// El banco de platos: que ES cada plato, para poder fotografiarlo. Ver la
// migracion 00007.
// Se trae entero y no por nombre: emparejar es cosa del dominio —patron mas
// largo, y el descrito le gana al que no lo esta— y esa regla no se escribe dos
// veces, una en Go y otra en SQL. Son 419 filas flacas y se lee una vez por
// carta, no por plato.
func (q *Queries) ListarPlatosTipicos(ctx context.Context) ([]ListarPlatosTipicosRow, error) {
	rows, err := q.db.Query(ctx, listarPlatosTipicos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListarPlatosTipicosRow{}
	for rows.Next() {
		var i ListarPlatosTipicosRow
		if err := rows.Scan(
			&i.Clave,
			&i.Nombre,
			&i.Cocina,
			&i.Curso,
			&i.Aspecto,
			&i.Recipiente,
			&i.Guarnicion,
			&i.Jamas,
			&i.Envasado,
			&i.Patrones,
			&i.Ingredientes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const marcarTipicoDePlato = `-- name: MarcarTipicoDePlato :exec
UPDATE plato
   SET plato_tipico  = $1,
       tipico_origen = $2
 WHERE id = $3
   AND tipico_origen <> 'dueno'
`

type MarcarTipicoDePlatoParams struct {
	Clave   string
	Origen  string
	PlatoID uuid.UUID
}

// Reengancha UN plato con el banco sin tocar nada mas.
//
// No pasa por GuardarCarta a proposito: esa empieza borrando los platos y los
// reinserta con ids nuevos, y de esos ids cuelgan las fotos ya pagadas.
//
// El del DUENO no se pisa: si corrigio a mano que su "Combo Tribuna" es un
// ceviche, ampliar el banco no puede deshacerlo.
func (q *Queries) MarcarTipicoDePlato(ctx context.Context, arg MarcarTipicoDePlatoParams) error {
	_, err := q.db.Exec(ctx, marcarTipicoDePlato, arg.Clave, arg.Origen, arg.PlatoID)
	return err
}

const platoTipicoPorClave = `-- name: PlatoTipicoPorClave :one
SELECT clave, nombre, cocina, curso, aspecto, recipiente, guarnicion, jamas,
       envasado, patrones
  FROM plato_tipico
 WHERE clave = $1
`

type PlatoTipicoPorClaveRow struct {
	Clave      string
	Nombre     string
	Cocina     string
	Curso      string
	Aspecto    string
	Recipiente string
	Guarnicion string
	Jamas      string
	Envasado   bool
	Patrones   []byte
}

// Para la foto ya solo hace falta el que se emparejo al leer.
func (q *Queries) PlatoTipicoPorClave(ctx context.Context, clave string) (PlatoTipicoPorClaveRow, error) {
	row := q.db.QueryRow(ctx, platoTipicoPorClave, clave)
	var i PlatoTipicoPorClaveRow
	err := row.Scan(
		&i.Clave,
		&i.Nombre,
		&i.Cocina,
		&i.Curso,
		&i.Aspecto,
		&i.Recipiente,
		&i.Guarnicion,
		&i.Jamas,
		&i.Envasado,
		&i.Patrones,
	)
	return i, err
}

const platosTipicosSinDescribir = `-- name: PlatosTipicosSinDescribir :many
SELECT clave, nombre, cocina, curso, patrones, ingredientes
  FROM plato_tipico
 WHERE aspecto = '' AND origen <> 'canon'
 ORDER BY clave
 LIMIT $1
`

type PlatosTipicosSinDescribirRow struct {
	Clave        string
	Nombre       string
	Cocina       string
	Curso        string
	Patrones     []byte
	Ingredientes []byte
}

// Lo que trajo la cosecha y nadie ha descrito: nombre e ingredientes, sin una
// sola linea de como se ve. Es la materia prima de cmd/describir.
//
// El canon no entra: esta escrito y medido a mano.
func (q *Queries) PlatosTipicosSinDescribir(ctx context.Context, limite int32) ([]PlatosTipicosSinDescribirRow, error) {
	rows, err := q.db.Query(ctx, platosTipicosSinDescribir, limite)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatosTipicosSinDescribirRow{}
	for rows.Next() {
		var i PlatosTipicosSinDescribirRow
		if err := rows.Scan(
			&i.Clave,
			&i.Nombre,
			&i.Cocina,
			&i.Curso,
			&i.Patrones,
			&i.Ingredientes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
