// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comprobantes.sql

package comprobantedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const actualizarComprobante = `-- name: ActualizarComprobante :exec
UPDATE "comprobantes"
   SET "estado"        = $2,
       "xml"           = $3,
       "cdr"           = $4,
       "ticket"        = $5,
       "codigo_sunat"  = $6,
       "mensaje_sunat" = $7,
       "updated_at"    = now()
 WHERE "id" = $1
`

type ActualizarComprobanteParams struct {
	ID           string
	Estado       string
	Xml          []byte
	Cdr          []byte
	Ticket       *string
	CodigoSunat  *string
	MensajeSunat *string
}

func (q *Queries) ActualizarComprobante(ctx context.Context, arg ActualizarComprobanteParams) error {
	_, err := q.db.Exec(ctx, actualizarComprobante,
		arg.ID,
		arg.Estado,
		arg.Xml,
		arg.Cdr,
		arg.Ticket,
		arg.CodigoSunat,
		arg.MensajeSunat,
	)
	return err
}

const antiguedadDelMasViejoSinResolver = `-- name: AntiguedadDelMasViejoSinResolver :one
SELECT coalesce(extract(epoch FROM now() - min("created_at")), 0)::float8
  FROM "comprobantes"
 WHERE "estado" NOT IN ('aceptado', 'observado', 'rechazado', 'duplicado', 'anulado')
`

// Segundos que lleva esperando el comprobante mas antiguo que aun no llega a un
// estado final. Es la senal mas temprana de que el pipeline se atasco.
func (q *Queries) AntiguedadDelMasViejoSinResolver(ctx context.Context) (float64, error) {
	row := q.db.QueryRow(ctx, antiguedadDelMasViejoSinResolver)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}

const comprobantePorID = `-- name: ComprobantePorID :one
SELECT id, tenant_id, idempotency_key, tipo_doc, serie, correlativo, estado, payload, moneda, importe_total, fecha_emision, xml, cdr, ticket, codigo_sunat, mensaje_sunat, intentos, tomado_at, created_at, updated_at, resumen_id, motivo_baja, webhook_enviado FROM "comprobantes"
 WHERE "tenant_id" = $1 AND "id" = $2
`

type ComprobantePorIDParams struct {
	TenantID string
	ID       string
}

func (q *Queries) ComprobantePorID(ctx context.Context, arg ComprobantePorIDParams) (Comprobante, error) {
	row := q.db.QueryRow(ctx, comprobantePorID, arg.TenantID, arg.ID)
	var i Comprobante
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.IdempotencyKey,
		&i.TipoDoc,
		&i.Serie,
		&i.Correlativo,
		&i.Estado,
		&i.Payload,
		&i.Moneda,
		&i.ImporteTotal,
		&i.FechaEmision,
		&i.Xml,
		&i.Cdr,
		&i.Ticket,
		&i.CodigoSunat,
		&i.MensajeSunat,
		&i.Intentos,
		&i.TomadoAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResumenID,
		&i.MotivoBaja,
		&i.WebhookEnviado,
	)
	return i, err
}

const comprobantePorIdempotencyKey = `-- name: ComprobantePorIdempotencyKey :one
SELECT id, tenant_id, idempotency_key, tipo_doc, serie, correlativo, estado, payload, moneda, importe_total, fecha_emision, xml, cdr, ticket, codigo_sunat, mensaje_sunat, intentos, tomado_at, created_at, updated_at, resumen_id, motivo_baja, webhook_enviado FROM "comprobantes"
 WHERE "tenant_id" = $1 AND "idempotency_key" = $2
`

type ComprobantePorIdempotencyKeyParams struct {
	TenantID       string
	IdempotencyKey string
}

func (q *Queries) ComprobantePorIdempotencyKey(ctx context.Context, arg ComprobantePorIdempotencyKeyParams) (Comprobante, error) {
	row := q.db.QueryRow(ctx, comprobantePorIdempotencyKey, arg.TenantID, arg.IdempotencyKey)
	var i Comprobante
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.IdempotencyKey,
		&i.TipoDoc,
		&i.Serie,
		&i.Correlativo,
		&i.Estado,
		&i.Payload,
		&i.Moneda,
		&i.ImporteTotal,
		&i.FechaEmision,
		&i.Xml,
		&i.Cdr,
		&i.Ticket,
		&i.CodigoSunat,
		&i.MensajeSunat,
		&i.Intentos,
		&i.TomadoAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResumenID,
		&i.MotivoBaja,
		&i.WebhookEnviado,
	)
	return i, err
}

const comprobantesHuerfanos = `-- name: ComprobantesHuerfanos :many
SELECT id, tenant_id, idempotency_key, tipo_doc, serie, correlativo, estado, payload, moneda, importe_total, fecha_emision, xml, cdr, ticket, codigo_sunat, mensaje_sunat, intentos, tomado_at, created_at, updated_at, resumen_id, motivo_baja, webhook_enviado FROM "comprobantes"
 WHERE "estado" IN ('pendiente', 'procesando', 'error')
   AND "updated_at" < now() - make_interval(secs => $2::int)
   AND "intentos" < $3::int
 ORDER BY "created_at"
 LIMIT $1
`

type ComprobantesHuerfanosParams struct {
	Limit              int32
	AntiguedadSegundos int32
	MaxIntentos        int32
}

// Red de seguridad: comprobantes que llevan demasiado tiempo sin avanzar. Su job
// pudo cerrarse por error, descartarse tras agotar reintentos o perderse.
// No hace falta comprobar si ya hay un job encolado: reencolar es inofensivo
// porque Tomar solo deja pasar a un worker, y River deduplica por args.
func (q *Queries) ComprobantesHuerfanos(ctx context.Context, arg ComprobantesHuerfanosParams) ([]Comprobante, error) {
	rows, err := q.db.Query(ctx, comprobantesHuerfanos, arg.Limit, arg.AntiguedadSegundos, arg.MaxIntentos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comprobante{}
	for rows.Next() {
		var i Comprobante
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.IdempotencyKey,
			&i.TipoDoc,
			&i.Serie,
			&i.Correlativo,
			&i.Estado,
			&i.Payload,
			&i.Moneda,
			&i.ImporteTotal,
			&i.FechaEmision,
			&i.Xml,
			&i.Cdr,
			&i.Ticket,
			&i.CodigoSunat,
			&i.MensajeSunat,
			&i.Intentos,
			&i.TomadoAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResumenID,
			&i.MotivoBaja,
			&i.WebhookEnviado,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const comprobantesRequierenAtencion = `-- name: ComprobantesRequierenAtencion :many
SELECT id, tenant_id, idempotency_key, tipo_doc, serie, correlativo, estado, payload, moneda, importe_total, fecha_emision, xml, cdr, ticket, codigo_sunat, mensaje_sunat, intentos, tomado_at, created_at, updated_at, resumen_id, motivo_baja, webhook_enviado FROM "comprobantes"
 WHERE "tenant_id" = $1
   AND ("estado" = 'duplicado'
        OR ("estado" IN ('pendiente', 'procesando', 'error') AND "intentos" >= $3::int))
 ORDER BY "updated_at" DESC
 LIMIT $2
`

type ComprobantesRequierenAtencionParams struct {
	TenantID    string
	Limit       int32
	MaxIntentos int32
}

// Los que ni River ni el barredor pueden arreglar: agotaron reintentos, o SUNAT
// respondio algo que exige decision humana. Nadie mas los va a mirar.
func (q *Queries) ComprobantesRequierenAtencion(ctx context.Context, arg ComprobantesRequierenAtencionParams) ([]Comprobante, error) {
	rows, err := q.db.Query(ctx, comprobantesRequierenAtencion, arg.TenantID, arg.Limit, arg.MaxIntentos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comprobante{}
	for rows.Next() {
		var i Comprobante
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.IdempotencyKey,
			&i.TipoDoc,
			&i.Serie,
			&i.Correlativo,
			&i.Estado,
			&i.Payload,
			&i.Moneda,
			&i.ImporteTotal,
			&i.FechaEmision,
			&i.Xml,
			&i.Cdr,
			&i.Ticket,
			&i.CodigoSunat,
			&i.MensajeSunat,
			&i.Intentos,
			&i.TomadoAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResumenID,
			&i.MotivoBaja,
			&i.WebhookEnviado,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const comprobantesSinNotificar = `-- name: ComprobantesSinNotificar :many
SELECT id, tenant_id, idempotency_key, tipo_doc, serie, correlativo, estado, payload, moneda, importe_total, fecha_emision, xml, cdr, ticket, codigo_sunat, mensaje_sunat, intentos, tomado_at, created_at, updated_at, resumen_id, motivo_baja, webhook_enviado FROM "comprobantes"
 WHERE "webhook_enviado" = false
   AND "estado" IN ('aceptado', 'observado', 'rechazado', 'anulado')
   AND "updated_at" < now() - make_interval(secs => $1::int)
 ORDER BY "updated_at"
 LIMIT $2::int
`

type ComprobantesSinNotificarParams struct {
	AntiguedadSegundos int32
	Limite             int32
}

// Red de seguridad del webhook: si el job de notificacion se pierde o se
// descarta, el cliente nunca se entera de que su comprobante quedo resuelto.
func (q *Queries) ComprobantesSinNotificar(ctx context.Context, arg ComprobantesSinNotificarParams) ([]Comprobante, error) {
	rows, err := q.db.Query(ctx, comprobantesSinNotificar, arg.AntiguedadSegundos, arg.Limite)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comprobante{}
	for rows.Next() {
		var i Comprobante
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.IdempotencyKey,
			&i.TipoDoc,
			&i.Serie,
			&i.Correlativo,
			&i.Estado,
			&i.Payload,
			&i.Moneda,
			&i.ImporteTotal,
			&i.FechaEmision,
			&i.Xml,
			&i.Cdr,
			&i.Ticket,
			&i.CodigoSunat,
			&i.MensajeSunat,
			&i.Intentos,
			&i.TomadoAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResumenID,
			&i.MotivoBaja,
			&i.WebhookEnviado,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const contarComprobantes = `-- name: ContarComprobantes :one
SELECT count(*) FROM "comprobantes" WHERE "tenant_id" = $1
`

func (q *Queries) ContarComprobantes(ctx context.Context, tenantID string) (int64, error) {
	row := q.db.QueryRow(ctx, contarComprobantes, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const contarPorEstado = `-- name: ContarPorEstado :many
SELECT "estado", count(*) AS "total"
  FROM "comprobantes"
 GROUP BY "estado"
`

type ContarPorEstadoRow struct {
	Estado string
	Total  int64
}

// Alimenta las metricas: sin esto no hay forma de ver, en un vistazo, si algo
// se esta acumulando en un estado que no deberia.
func (q *Queries) ContarPorEstado(ctx context.Context) ([]ContarPorEstadoRow, error) {
	rows, err := q.db.Query(ctx, contarPorEstado)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContarPorEstadoRow{}
	for rows.Next() {
		var i ContarPorEstadoRow
		if err := rows.Scan(&i.Estado, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const contarRequierenAtencion = `-- name: ContarRequierenAtencion :one
SELECT count(*) FROM "comprobantes"
 WHERE "estado" = 'duplicado'
    OR ("estado" IN ('pendiente', 'procesando', 'error') AND "intentos" >= $1::int)
`

// Lo mismo que ComprobantesRequierenAtencion pero de todos los emisores: es la
// cifra que tiene que estar en cero, y que hoy nadie mira.
func (q *Queries) ContarRequierenAtencion(ctx context.Context, maxIntentos int32) (int64, error) {
	row := q.db.QueryRow(ctx, contarRequierenAtencion, maxIntentos)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const crearComprobante = `-- name: CrearComprobante :exec
INSERT INTO "comprobantes" (
    "id", "tenant_id", "idempotency_key", "tipo_doc", "serie", "correlativo",
    "estado", "payload", "moneda", "importe_total", "fecha_emision",
    "created_at", "updated_at"
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
`

type CrearComprobanteParams struct {
	ID             string
	TenantID       string
	IdempotencyKey string
	TipoDoc        string
	Serie          string
	Correlativo    int64
	Estado         string
	Payload        []byte
	Moneda         string
	ImporteTotal   pgtype.Numeric
	FechaEmision   pgtype.Date
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) CrearComprobante(ctx context.Context, arg CrearComprobanteParams) error {
	_, err := q.db.Exec(ctx, crearComprobante,
		arg.ID,
		arg.TenantID,
		arg.IdempotencyKey,
		arg.TipoDoc,
		arg.Serie,
		arg.Correlativo,
		arg.Estado,
		arg.Payload,
		arg.Moneda,
		arg.ImporteTotal,
		arg.FechaEmision,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const crearSerie = `-- name: CrearSerie :exec
INSERT INTO "series" ("tenant_id", "tipo_doc", "serie", "correlativo")
VALUES ($1, $2, $3, $4)
ON CONFLICT ("tenant_id", "tipo_doc", "serie") DO NOTHING
`

type CrearSerieParams struct {
	TenantID    string
	TipoDoc     string
	Serie       string
	Correlativo int64
}

func (q *Queries) CrearSerie(ctx context.Context, arg CrearSerieParams) error {
	_, err := q.db.Exec(ctx, crearSerie,
		arg.TenantID,
		arg.TipoDoc,
		arg.Serie,
		arg.Correlativo,
	)
	return err
}

const estadoComprobante = `-- name: EstadoComprobante :one
SELECT "estado" FROM "comprobantes" WHERE "id" = $1
`

func (q *Queries) EstadoComprobante(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, estadoComprobante, id)
	var estado string
	err := row.Scan(&estado)
	return estado, err
}

const listarComprobantes = `-- name: ListarComprobantes :many
SELECT id, tenant_id, idempotency_key, tipo_doc, serie, correlativo, estado, payload, moneda, importe_total, fecha_emision, xml, cdr, ticket, codigo_sunat, mensaje_sunat, intentos, tomado_at, created_at, updated_at, resumen_id, motivo_baja, webhook_enviado FROM "comprobantes"
 WHERE "tenant_id" = $1
 ORDER BY "created_at" DESC
 LIMIT $2 OFFSET $3
`

type ListarComprobantesParams struct {
	TenantID string
	Limit    int32
	Offset   int32
}

func (q *Queries) ListarComprobantes(ctx context.Context, arg ListarComprobantesParams) ([]Comprobante, error) {
	rows, err := q.db.Query(ctx, listarComprobantes, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comprobante{}
	for rows.Next() {
		var i Comprobante
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.IdempotencyKey,
			&i.TipoDoc,
			&i.Serie,
			&i.Correlativo,
			&i.Estado,
			&i.Payload,
			&i.Moneda,
			&i.ImporteTotal,
			&i.FechaEmision,
			&i.Xml,
			&i.Cdr,
			&i.Ticket,
			&i.CodigoSunat,
			&i.MensajeSunat,
			&i.Intentos,
			&i.TomadoAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResumenID,
			&i.MotivoBaja,
			&i.WebhookEnviado,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const marcarWebhookEnviado = `-- name: MarcarWebhookEnviado :exec
UPDATE "comprobantes" SET "webhook_enviado" = true WHERE "id" = $1
`

func (q *Queries) MarcarWebhookEnviado(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, marcarWebhookEnviado, id)
	return err
}

const siguienteCorrelativo = `-- name: SiguienteCorrelativo :one
UPDATE "series"
   SET "correlativo" = "correlativo" + 1
 WHERE "tenant_id" = $1 AND "tipo_doc" = $2 AND "serie" = $3
RETURNING "correlativo"
`

type SiguienteCorrelativoParams struct {
	TenantID string
	TipoDoc  string
	Serie    string
}

// El UPDATE toma un lock de fila, serializando solo por (tenant, tipo, serie).
func (q *Queries) SiguienteCorrelativo(ctx context.Context, arg SiguienteCorrelativoParams) (int64, error) {
	row := q.db.QueryRow(ctx, siguienteCorrelativo, arg.TenantID, arg.TipoDoc, arg.Serie)
	var correlativo int64
	err := row.Scan(&correlativo)
	return correlativo, err
}

const tomarComprobante = `-- name: TomarComprobante :one
UPDATE "comprobantes"
   SET "estado"     = 'procesando',
       "intentos"   = "intentos" + 1,
       "tomado_at"  = now(),
       "updated_at" = now()
 WHERE "id" = $1
   AND (
        "estado" = ANY($2::text[])
        OR ("estado" = 'procesando'
            AND "tomado_at" < now() - make_interval(secs => $3::int))
   )
RETURNING id, tenant_id, idempotency_key, tipo_doc, serie, correlativo, estado, payload, moneda, importe_total, fecha_emision, xml, cdr, ticket, codigo_sunat, mensaje_sunat, intentos, tomado_at, created_at, updated_at, resumen_id, motivo_baja, webhook_enviado
`

type TomarComprobanteParams struct {
	ID              string
	EstadosTomables []string
	TimeoutSegundos int32
}

// Guarda de concurrencia: si River entrega el job dos veces, el segundo UPDATE
// afecta 0 filas y el worker sale sin reintentar.
//
// La segunda condicion rescata comprobantes que quedaron en 'procesando' porque
// el proceso murio a mitad. Sin ella se quedarian ahi para siempre: River
// reintentaria, Tomar devolveria "ya tomado" y el job se cerraria como exitoso
// sin haber emitido nada.
func (q *Queries) TomarComprobante(ctx context.Context, arg TomarComprobanteParams) (Comprobante, error) {
	row := q.db.QueryRow(ctx, tomarComprobante, arg.ID, arg.EstadosTomables, arg.TimeoutSegundos)
	var i Comprobante
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.IdempotencyKey,
		&i.TipoDoc,
		&i.Serie,
		&i.Correlativo,
		&i.Estado,
		&i.Payload,
		&i.Moneda,
		&i.ImporteTotal,
		&i.FechaEmision,
		&i.Xml,
		&i.Cdr,
		&i.Ticket,
		&i.CodigoSunat,
		&i.MensajeSunat,
		&i.Intentos,
		&i.TomadoAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResumenID,
		&i.MotivoBaja,
		&i.WebhookEnviado,
	)
	return i, err
}
