// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package comprobantedb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Comprobante struct {
	ID             string
	TenantID       string
	IdempotencyKey string
	TipoDoc        string
	Serie          string
	Correlativo    int64
	Estado         string
	Payload        []byte
	Moneda         string
	ImporteTotal   pgtype.Numeric
	FechaEmision   pgtype.Date
	Xml            []byte
	Cdr            []byte
	Ticket         *string
	CodigoSunat    *string
	MensajeSunat   *string
	Intentos       int32
	TomadoAt       pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	ResumenID      *string
	MotivoBaja     *string
	WebhookEnviado bool
}

type Resumene struct {
	ID           string
	TenantID     string
	Tipo         string
	FechaRef     pgtype.Date
	Correlativo  int64
	Estado       string
	Ticket       *string
	Xml          []byte
	Cdr          []byte
	CodigoSunat  *string
	MensajeSunat *string
	Intentos     int32
	TomadoAt     pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Series struct {
	TenantID    string
	TipoDoc     string
	Serie       string
	Correlativo int64
}

type SeriesResuman struct {
	TenantID    string
	Tipo        string
	FechaRef    pgtype.Date
	Correlativo int64
}

type Tenant struct {
	ID                   string
	Ruc                  string
	RazonSocial          string
	NombreComercial      *string
	Direccion            string
	Ubigeo               string
	Departamento         string
	Provincia            string
	Distrito             string
	CertCifrado          []byte
	SolUser              string
	SolPassCifrado       []byte
	Produccion           bool
	ApiKeyHash           string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	WebhookUrl           *string
	WebhookSecretCifrado []byte
}
