// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resumenes.sql

package comprobantedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const actualizarResumen = `-- name: ActualizarResumen :exec
UPDATE "resumenes"
   SET "estado"        = $2,
       "ticket"        = $3,
       "xml"           = $4,
       "cdr"           = $5,
       "codigo_sunat"  = $6,
       "mensaje_sunat" = $7,
       "updated_at"    = now()
 WHERE "id" = $1
`

type ActualizarResumenParams struct {
	ID           string
	Estado       string
	Ticket       *string
	Xml          []byte
	Cdr          []byte
	CodigoSunat  *string
	MensajeSunat *string
}

func (q *Queries) ActualizarResumen(ctx context.Context, arg ActualizarResumenParams) error {
	_, err := q.db.Exec(ctx, actualizarResumen,
		arg.ID,
		arg.Estado,
		arg.Ticket,
		arg.Xml,
		arg.Cdr,
		arg.CodigoSunat,
		arg.MensajeSunat,
	)
	return err
}

const asignarResumen = `-- name: AsignarResumen :exec
UPDATE "comprobantes"
   SET "resumen_id" = $1::text, "updated_at" = now()
 WHERE "id" = ANY($2::text[])
`

type AsignarResumenParams struct {
	ResumenID string
	Ids       []string
}

func (q *Queries) AsignarResumen(ctx context.Context, arg AsignarResumenParams) error {
	_, err := q.db.Exec(ctx, asignarResumen, arg.ResumenID, arg.Ids)
	return err
}

const boletasParaResumen = `-- name: BoletasParaResumen :many
SELECT id, tenant_id, idempotency_key, tipo_doc, serie, correlativo, estado, payload, moneda, importe_total, fecha_emision, xml, cdr, ticket, codigo_sunat, mensaje_sunat, intentos, tomado_at, created_at, updated_at, resumen_id, motivo_baja, webhook_enviado FROM "comprobantes"
 WHERE "tenant_id" = $1::text
   AND "fecha_emision" = $2::date
   AND "estado" = 'pendiente_resumen'
   AND "resumen_id" IS NULL
 ORDER BY "correlativo"
 LIMIT $3::int
`

type BoletasParaResumenParams struct {
	TenantID     string
	FechaEmision pgtype.Date
	Limite       int32
}

func (q *Queries) BoletasParaResumen(ctx context.Context, arg BoletasParaResumenParams) ([]Comprobante, error) {
	rows, err := q.db.Query(ctx, boletasParaResumen, arg.TenantID, arg.FechaEmision, arg.Limite)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comprobante{}
	for rows.Next() {
		var i Comprobante
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.IdempotencyKey,
			&i.TipoDoc,
			&i.Serie,
			&i.Correlativo,
			&i.Estado,
			&i.Payload,
			&i.Moneda,
			&i.ImporteTotal,
			&i.FechaEmision,
			&i.Xml,
			&i.Cdr,
			&i.Ticket,
			&i.CodigoSunat,
			&i.MensajeSunat,
			&i.Intentos,
			&i.TomadoAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResumenID,
			&i.MotivoBaja,
			&i.WebhookEnviado,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const comprobantesDeResumen = `-- name: ComprobantesDeResumen :many
SELECT id, tenant_id, idempotency_key, tipo_doc, serie, correlativo, estado, payload, moneda, importe_total, fecha_emision, xml, cdr, ticket, codigo_sunat, mensaje_sunat, intentos, tomado_at, created_at, updated_at, resumen_id, motivo_baja, webhook_enviado FROM "comprobantes"
 WHERE "resumen_id" = $1::text
 ORDER BY "correlativo"
`

func (q *Queries) ComprobantesDeResumen(ctx context.Context, resumenID string) ([]Comprobante, error) {
	rows, err := q.db.Query(ctx, comprobantesDeResumen, resumenID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comprobante{}
	for rows.Next() {
		var i Comprobante
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.IdempotencyKey,
			&i.TipoDoc,
			&i.Serie,
			&i.Correlativo,
			&i.Estado,
			&i.Payload,
			&i.Moneda,
			&i.ImporteTotal,
			&i.FechaEmision,
			&i.Xml,
			&i.Cdr,
			&i.Ticket,
			&i.CodigoSunat,
			&i.MensajeSunat,
			&i.Intentos,
			&i.TomadoAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResumenID,
			&i.MotivoBaja,
			&i.WebhookEnviado,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const crearResumen = `-- name: CrearResumen :exec
INSERT INTO "resumenes" ("id", "tenant_id", "tipo", "fecha_ref", "correlativo", "estado")
VALUES ($1, $2, $3, $4, $5, $6)
`

type CrearResumenParams struct {
	ID          string
	TenantID    string
	Tipo        string
	FechaRef    pgtype.Date
	Correlativo int64
	Estado      string
}

func (q *Queries) CrearResumen(ctx context.Context, arg CrearResumenParams) error {
	_, err := q.db.Exec(ctx, crearResumen,
		arg.ID,
		arg.TenantID,
		arg.Tipo,
		arg.FechaRef,
		arg.Correlativo,
		arg.Estado,
	)
	return err
}

const marcarComprobanteAnulado = `-- name: MarcarComprobanteAnulado :exec
UPDATE "comprobantes"
   SET "estado" = 'anulado', "motivo_baja" = $1::text, "updated_at" = now()
 WHERE "id" = $2::text
`

type MarcarComprobanteAnuladoParams struct {
	Motivo string
	ID     string
}

func (q *Queries) MarcarComprobanteAnulado(ctx context.Context, arg MarcarComprobanteAnuladoParams) error {
	_, err := q.db.Exec(ctx, marcarComprobanteAnulado, arg.Motivo, arg.ID)
	return err
}

const resolverComprobantesDeResumen = `-- name: ResolverComprobantesDeResumen :exec
UPDATE "comprobantes"
   SET "estado"        = $1::text,
       "codigo_sunat"  = $2::text,
       "mensaje_sunat" = $3::text,
       "updated_at"    = now()
 WHERE "resumen_id" = $4::text
`

type ResolverComprobantesDeResumenParams struct {
	Estado       string
	CodigoSunat  string
	MensajeSunat string
	ResumenID    string
}

// El CDR del resumen resuelve de una vez todas las boletas que iban dentro.
func (q *Queries) ResolverComprobantesDeResumen(ctx context.Context, arg ResolverComprobantesDeResumenParams) error {
	_, err := q.db.Exec(ctx, resolverComprobantesDeResumen,
		arg.Estado,
		arg.CodigoSunat,
		arg.MensajeSunat,
		arg.ResumenID,
	)
	return err
}

const resumenPorID = `-- name: ResumenPorID :one
SELECT id, tenant_id, tipo, fecha_ref, correlativo, estado, ticket, xml, cdr, codigo_sunat, mensaje_sunat, intentos, tomado_at, created_at, updated_at FROM "resumenes" WHERE "id" = $1
`

func (q *Queries) ResumenPorID(ctx context.Context, id string) (Resumene, error) {
	row := q.db.QueryRow(ctx, resumenPorID, id)
	var i Resumene
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Tipo,
		&i.FechaRef,
		&i.Correlativo,
		&i.Estado,
		&i.Ticket,
		&i.Xml,
		&i.Cdr,
		&i.CodigoSunat,
		&i.MensajeSunat,
		&i.Intentos,
		&i.TomadoAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resumenesEnCurso = `-- name: ResumenesEnCurso :many
SELECT id, tenant_id, tipo, fecha_ref, correlativo, estado, ticket, xml, cdr, codigo_sunat, mensaje_sunat, intentos, tomado_at, created_at, updated_at FROM "resumenes"
 WHERE "estado" IN ('pendiente', 'procesando', 'ticket_pendiente', 'error')
   AND "updated_at" < now() - make_interval(secs => $1::int)
   AND "intentos" < $2::int
 ORDER BY "created_at"
 LIMIT $3::int
`

type ResumenesEnCursoParams struct {
	AntiguedadSegundos int32
	MaxIntentos        int32
	Limite             int32
}

// Resumenes que todavia no llegaron a un estado final. Se usa tanto para el
// polling de tickets como para el rescate de los que quedaron colgados.
func (q *Queries) ResumenesEnCurso(ctx context.Context, arg ResumenesEnCursoParams) ([]Resumene, error) {
	rows, err := q.db.Query(ctx, resumenesEnCurso, arg.AntiguedadSegundos, arg.MaxIntentos, arg.Limite)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resumene{}
	for rows.Next() {
		var i Resumene
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Tipo,
			&i.FechaRef,
			&i.Correlativo,
			&i.Estado,
			&i.Ticket,
			&i.Xml,
			&i.Cdr,
			&i.CodigoSunat,
			&i.MensajeSunat,
			&i.Intentos,
			&i.TomadoAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const siguienteCorrelativoResumen = `-- name: SiguienteCorrelativoResumen :one
INSERT INTO "series_resumen" ("tenant_id", "tipo", "fecha_ref", "correlativo")
VALUES ($1, $2, $3, 1)
ON CONFLICT ("tenant_id", "tipo", "fecha_ref")
DO UPDATE SET "correlativo" = "series_resumen"."correlativo" + 1
RETURNING "correlativo"
`

type SiguienteCorrelativoResumenParams struct {
	TenantID string
	Tipo     string
	FechaRef pgtype.Date
}

func (q *Queries) SiguienteCorrelativoResumen(ctx context.Context, arg SiguienteCorrelativoResumenParams) (int64, error) {
	row := q.db.QueryRow(ctx, siguienteCorrelativoResumen, arg.TenantID, arg.Tipo, arg.FechaRef)
	var correlativo int64
	err := row.Scan(&correlativo)
	return correlativo, err
}

const tenantsConBoletasPendientes = `-- name: TenantsConBoletasPendientes :many
SELECT DISTINCT "tenant_id", "fecha_emision"
  FROM "comprobantes"
 WHERE "estado" = 'pendiente_resumen'
   AND "resumen_id" IS NULL
 ORDER BY "fecha_emision", "tenant_id"
 LIMIT $1::int
`

type TenantsConBoletasPendientesRow struct {
	TenantID     string
	FechaEmision pgtype.Date
}

// Agrupa por emisor y fecha: cada combinacion produce un resumen diario.
func (q *Queries) TenantsConBoletasPendientes(ctx context.Context, limite int32) ([]TenantsConBoletasPendientesRow, error) {
	rows, err := q.db.Query(ctx, tenantsConBoletasPendientes, limite)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantsConBoletasPendientesRow{}
	for rows.Next() {
		var i TenantsConBoletasPendientesRow
		if err := rows.Scan(&i.TenantID, &i.FechaEmision); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tomarResumen = `-- name: TomarResumen :one
UPDATE "resumenes"
   SET "estado"     = 'procesando',
       "intentos"   = "intentos" + 1,
       "tomado_at"  = now(),
       "updated_at" = now()
 WHERE "id" = $1
   AND (
        "estado" IN ('pendiente', 'error')
        OR ("estado" = 'procesando'
            AND "tomado_at" < now() - make_interval(secs => $2::int))
   )
RETURNING id, tenant_id, tipo, fecha_ref, correlativo, estado, ticket, xml, cdr, codigo_sunat, mensaje_sunat, intentos, tomado_at, created_at, updated_at
`

type TomarResumenParams struct {
	ID              string
	TimeoutSegundos int32
}

func (q *Queries) TomarResumen(ctx context.Context, arg TomarResumenParams) (Resumene, error) {
	row := q.db.QueryRow(ctx, tomarResumen, arg.ID, arg.TimeoutSegundos)
	var i Resumene
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Tipo,
		&i.FechaRef,
		&i.Correlativo,
		&i.Estado,
		&i.Ticket,
		&i.Xml,
		&i.Cdr,
		&i.CodigoSunat,
		&i.MensajeSunat,
		&i.Intentos,
		&i.TomadoAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
