// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package comprobantedb

import (
	"context"
)

const crearTenant = `-- name: CrearTenant :exec
INSERT INTO "tenants" (
    "id", "ruc", "razon_social", "nombre_comercial", "direccion",
    "ubigeo", "departamento", "provincia", "distrito",
    "cert_cifrado", "sol_user", "sol_pass_cifrado", "produccion", "api_key_hash",
    "webhook_url", "webhook_secret_cifrado"
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
)
`

type CrearTenantParams struct {
	ID                   string
	Ruc                  string
	RazonSocial          string
	NombreComercial      *string
	Direccion            string
	Ubigeo               string
	Departamento         string
	Provincia            string
	Distrito             string
	CertCifrado          []byte
	SolUser              string
	SolPassCifrado       []byte
	Produccion           bool
	ApiKeyHash           string
	WebhookUrl           *string
	WebhookSecretCifrado []byte
}

func (q *Queries) CrearTenant(ctx context.Context, arg CrearTenantParams) error {
	_, err := q.db.Exec(ctx, crearTenant,
		arg.ID,
		arg.Ruc,
		arg.RazonSocial,
		arg.NombreComercial,
		arg.Direccion,
		arg.Ubigeo,
		arg.Departamento,
		arg.Provincia,
		arg.Distrito,
		arg.CertCifrado,
		arg.SolUser,
		arg.SolPassCifrado,
		arg.Produccion,
		arg.ApiKeyHash,
		arg.WebhookUrl,
		arg.WebhookSecretCifrado,
	)
	return err
}

const tenantPorAPIKeyHash = `-- name: TenantPorAPIKeyHash :one
SELECT id, ruc, razon_social, nombre_comercial, direccion, ubigeo, departamento, provincia, distrito, cert_cifrado, sol_user, sol_pass_cifrado, produccion, api_key_hash, created_at, updated_at, webhook_url, webhook_secret_cifrado FROM "tenants" WHERE "api_key_hash" = $1
`

func (q *Queries) TenantPorAPIKeyHash(ctx context.Context, apiKeyHash string) (Tenant, error) {
	row := q.db.QueryRow(ctx, tenantPorAPIKeyHash, apiKeyHash)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Ruc,
		&i.RazonSocial,
		&i.NombreComercial,
		&i.Direccion,
		&i.Ubigeo,
		&i.Departamento,
		&i.Provincia,
		&i.Distrito,
		&i.CertCifrado,
		&i.SolUser,
		&i.SolPassCifrado,
		&i.Produccion,
		&i.ApiKeyHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WebhookUrl,
		&i.WebhookSecretCifrado,
	)
	return i, err
}

const tenantPorID = `-- name: TenantPorID :one
SELECT id, ruc, razon_social, nombre_comercial, direccion, ubigeo, departamento, provincia, distrito, cert_cifrado, sol_user, sol_pass_cifrado, produccion, api_key_hash, created_at, updated_at, webhook_url, webhook_secret_cifrado FROM "tenants" WHERE "id" = $1
`

func (q *Queries) TenantPorID(ctx context.Context, id string) (Tenant, error) {
	row := q.db.QueryRow(ctx, tenantPorID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Ruc,
		&i.RazonSocial,
		&i.NombreComercial,
		&i.Direccion,
		&i.Ubigeo,
		&i.Departamento,
		&i.Provincia,
		&i.Distrito,
		&i.CertCifrado,
		&i.SolUser,
		&i.SolPassCifrado,
		&i.Produccion,
		&i.ApiKeyHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WebhookUrl,
		&i.WebhookSecretCifrado,
	)
	return i, err
}
